"""Generate the E2 unified-schema migration for the AI domain.

Input: the frozen AI migrations (byte-immutable, already validated against PostgreSQL)
and the E0 table map. Output: a new platform migration that recreates every AI-domain
table inside the `platform` schema under its unified name.

Why a textual transform instead of re-emitting DDL from a parse tree: the frozen
migrations are the validated source of truth. Re-emitting from a parser would risk
dropping CHECK constraints, defaults or type nuances it did not model. Rewriting
identifiers keeps column definitions, constraints and comments byte-identical apart
from the table name and the schema qualifier.

Transformations (all anchored on the explicit rename map):
  1. whole-identifier rename of each legacy table name -> unified name
  2. schema qualification of CREATE/ALTER/COMMENT/INDEX/REFERENCES targets
  3. format('%I', tbl) inside the guarded DO blocks -> format('platform.%I', tbl)
  4. CREATE TABLE / CREATE INDEX made idempotent for upgrade rehearsals

Usage: python generate-unified-migration.py <aiMigrationsDir> <tableMapJson> <outFile>
"""
import json
import os
import re
import sys

# Statements whose target object must be schema-qualified.
QUALIFY = [
    (re.compile(r"(\bCREATE\s+TABLE\s+(?:IF\s+NOT\s+EXISTS\s+)?)(?!platform\.)", re.I), r"\1platform."),
    (re.compile(r"(\bALTER\s+TABLE\s+(?:IF\s+EXISTS\s+)?(?:ONLY\s+)?)(?!platform\.)", re.I), r"\1platform."),
    (re.compile(r"(\bCOMMENT\s+ON\s+TABLE\s+)(?!platform\.)", re.I), r"\1platform."),
    (re.compile(r"(\bCOMMENT\s+ON\s+COLUMN\s+)(?!platform\.)", re.I), r"\1platform."),
    (re.compile(r"(\bCREATE\s+(?:UNIQUE\s+)?INDEX\s+(?:CONCURRENTLY\s+)?(?:IF\s+NOT\s+EXISTS\s+)?[a-z_]\w*\s+ON\s+)(?!platform\.)", re.I), r"\1platform."),
    (re.compile(r"(\bREFERENCES\s+)(?!platform\.)", re.I), r"\1platform."),
]

IDEMPOTENT_TABLE = re.compile(r"(\bCREATE\s+TABLE\s+)(?!IF\s+NOT\s+EXISTS)", re.I)
IDEMPOTENT_INDEX = re.compile(r"(\bCREATE\s+(?:UNIQUE\s+)?INDEX\s+)(?!CONCURRENTLY)(?!IF\s+NOT\s+EXISTS)", re.I)
VERSION = re.compile(r"V(\d+)__")

HEADER = """-- ---------------------------------------------------------------------------
-- E2 unified AI domain: AI business and runtime tables recreated inside the
-- single `platform` schema under their unified names.
--
-- Generated by scripts/db/generate-unified-migration.py from the frozen AI
-- migrations (services/ai/resources/database/postgres/migrations, V1..V12) plus
-- the E0 table map (mydocs/platform-embedded/03-table-map.json). Do not hand-edit
-- the generated body: change the mapping and regenerate, so the table map and the
-- migration cannot drift apart.
--
-- The AI migrations themselves are never modified: their history stays byte-exact,
-- and this migration is the only forward chain from here on.
-- ---------------------------------------------------------------------------

"""


def load_rename_map(table_map_path):
    doc = json.load(open(table_map_path, encoding="utf-8"))
    mapping = {}
    for entry in doc["tables"]:
        src = entry.get("source", {})
        tgt = entry.get("target") or {}
        if src.get("schema") != "ai":
            continue
        old, new = src.get("table"), tgt.get("table")
        if old and new and old != new:
            mapping[old] = new
    return mapping


def rename_identifiers(sql, mapping):
    """Whole-identifier replacement, longest name first so t_message_feedback wins over t_message."""
    for old in sorted(mapping, key=len, reverse=True):
        sql = re.sub(r"(?<![\w.])%s(?![\w])" % re.escape(old), mapping[old], sql)
    return sql


def qualify_targets(sql):
    for pattern, repl in QUALIFY:
        sql = pattern.sub(repl, sql)
    return sql


def qualify_dynamic_sql(sql):
    """The V4/V7 DO blocks build statements with format('%I', table) over a table array."""
    sql = sql.replace("format('ALTER TABLE %I", "format('ALTER TABLE platform.%I")
    sql = sql.replace("format('SELECT count(*) FROM %I", "format('SELECT count(*) FROM platform.%I")
    return sql


def tables_created(sql):
    return sorted(set(re.findall(
        r"CREATE\s+TABLE\s+(?:IF\s+NOT\s+EXISTS\s+)?platform\.([a-z_]\w*)", sql, re.I)))


def main():
    ai_dir, map_path, out_path = sys.argv[1], sys.argv[2], sys.argv[3]
    mapping = load_rename_map(map_path)
    if not mapping:
        print("no AI table mapping found; refusing to emit an empty migration", file=sys.stderr)
        return 1

    # numeric version order: a plain string sort replays V10..V12 before V2 and would
    # apply an ALTER to a table that has not been created yet
    files = sorted(
        (f for f in os.listdir(ai_dir) if re.match(r"V\d+__.*\.sql$", f)),
        key=lambda f: int(VERSION.match(f).group(1)),
    )

    chunks = [HEADER]
    total = set()
    for fn in files:
        raw = open(os.path.join(ai_dir, fn), encoding="utf-8").read()
        body = rename_identifiers(raw, mapping)
        body = qualify_targets(body)
        body = qualify_dynamic_sql(body)
        body = IDEMPOTENT_TABLE.sub(r"\1IF NOT EXISTS ", body)
        body = IDEMPOTENT_INDEX.sub(r"\1IF NOT EXISTS ", body)
        total |= set(tables_created(body))
        chunks.append("\n-- ===== from %s =====\n" % fn)
        chunks.append(body.rstrip() + "\n")

    out = "".join(chunks)
    os.makedirs(os.path.dirname(out_path), exist_ok=True)
    open(out_path, "w", encoding="utf-8", newline="\n").write(out)

    targets = {t.get("target", {}).get("table") for t in
               json.load(open(map_path, encoding="utf-8"))["tables"] if t.get("target")}
    unexpected = sorted(t for t in total if t not in targets)
    print("wrote %s" % out_path)
    print("source files: %d, tables created: %d" % (len(files), len(total)))
    if unexpected:
        print("WARNING created tables absent from the table map:", unexpected, file=sys.stderr)
    return 0


if __name__ == "__main__":
    sys.exit(main())
