"""Generate the E2 data-migration migration (copies legacy AI rows into the unified schema).

The DDL migration (V7) creates the unified tables empty. This generator emits the
upgrade-only companion that copies rows across when a legacy `ai` schema is present.

Design notes:
  * The legacy and unified tables carry identical column definitions (the DDL migration
    is a rename of the frozen AI DDL), so the copy can use SELECT * -- but only after the
    DO block has verified that the column count and column names really do match. A
    mismatch raises instead of copying the wrong data into the wrong columns.
  * Copies are ON CONFLICT DO NOTHING, so a re-run after a partial failure is safe.
  * The legacy tables are deliberately NOT dropped: they stay as read-only evidence until
    the retirement unit (E8) after the new reads are accepted. Only the AI Flyway history
    table is renamed, so nothing writes a second migration chain into it.
  * Row counts before/after are recorded in platform.ai_unified_migration_audit.

Usage: python generate-unified-copy.py <tableMapJson> <outFile>
"""
import json
import os
import sys

HEADER = """-- ---------------------------------------------------------------------------
-- E2 unified AI domain: copy legacy `ai` schema rows into the unified tables.
--
-- Generated by scripts/db/generate-unified-copy.py from the E0 table map
-- (mydocs/platform-embedded/03-table-map.json). Do not hand-edit the generated
-- body: change the mapping and regenerate.
--
-- This migration is a no-op on a fresh install (no legacy `ai` schema) and does the
-- data move on an upgrade from an existing two-schema deployment. Legacy tables are
-- left in place as read-only evidence; only the AI history table is renamed so it can
-- never be used as a second migration chain.
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS platform.ai_unified_migration_audit (
    audit_id        bigserial    PRIMARY KEY,
    legacy_schema   varchar(64)  NOT NULL,
    legacy_table    varchar(128) NOT NULL,
    unified_table   varchar(128) NOT NULL,
    rows_copied     bigint       NOT NULL,
    unified_rows    bigint       NOT NULL,
    recorded_at     timestamp    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_ai_unified_audit UNIQUE (legacy_table)
);
COMMENT ON TABLE platform.ai_unified_migration_audit IS 'E2 统一迁移对账记录：每个旧表复制到统一表后的行数';

-- Archive the AI migration history so it can never be mistaken for an active chain.
DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM information_schema.tables
               WHERE table_schema = 'ai' AND table_name = 'flyway_schema_history')
       AND NOT EXISTS (SELECT 1 FROM information_schema.tables
                       WHERE table_schema = 'ai' AND table_name = 'flyway_schema_history_ai_legacy')
    THEN
        ALTER TABLE ai.flyway_schema_history RENAME TO flyway_schema_history_ai_legacy;
        RAISE NOTICE 'archived ai.flyway_schema_history as flyway_schema_history_ai_legacy';
    END IF;
END $$;
"""

FOOTER = """
-- Final reconciliation: fail loudly if a copy lost rows.
DO $$
DECLARE
    bad record;
BEGIN
    FOR bad IN
        SELECT a.legacy_table, a.rows_copied, a.unified_rows
        FROM platform.ai_unified_migration_audit a
        WHERE a.legacy_schema = 'ai' AND a.unified_rows < a.rows_copied
    LOOP
        RAISE EXCEPTION 'unified copy lost rows for % (copied %, present %)',
            bad.legacy_table, bad.rows_copied, bad.unified_rows;
    END LOOP;
END $$;
"""


def load_pairs(table_map_path):
    doc = json.load(open(table_map_path, encoding="utf-8"))
    pairs = []
    for entry in doc["tables"]:
        src = entry.get("source", {})
        tgt = entry.get("target") or {}
        if src.get("schema") != "ai" or not tgt.get("table"):
            continue
        if entry.get("status") == "excluded":
            continue
        pairs.append((src["table"], tgt["table"]))
    return sorted(set(pairs))


BLOCK = '''
-- ===== {legacy} -> {unified} =====
DO $$
DECLARE
    copied bigint := 0;
    present bigint := 0;
    legacy_cols int;
    unified_cols int;
    legacy_names text;
    unified_names text;
BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.tables
                   WHERE table_schema = 'ai' AND table_name = '{legacy}')
    THEN
        RETURN;
    END IF;

    -- 列名与列数必须一致，否则拒绝复制（不做隐式列映射）
    SELECT count(*), string_agg(column_name, ',' ORDER BY ordinal_position)
      INTO legacy_cols, legacy_names
      FROM information_schema.columns
     WHERE table_schema = 'ai' AND table_name = '{legacy}';
    SELECT count(*), string_agg(column_name, ',' ORDER BY ordinal_position)
      INTO unified_cols, unified_names
      FROM information_schema.columns
     WHERE table_schema = 'platform' AND table_name = '{unified}';

    IF legacy_cols IS DISTINCT FROM unified_cols OR legacy_names IS DISTINCT FROM unified_names THEN
        RAISE EXCEPTION 'column mismatch for ai.{legacy} -> platform.{unified}: legacy(%) unified(%)',
            legacy_names, unified_names;
    END IF;

    SELECT count(*) INTO copied FROM ai.{legacy};
    INSERT INTO platform.{unified}
        SELECT * FROM ai.{legacy}
        ON CONFLICT DO NOTHING;
    SELECT count(*) INTO present FROM platform.{unified};

    INSERT INTO platform.ai_unified_migration_audit
        (legacy_schema, legacy_table, unified_table, rows_copied, unified_rows)
    VALUES ('ai', '{legacy}', '{unified}', copied, present)
    ON CONFLICT (legacy_table) DO UPDATE
       SET rows_copied = EXCLUDED.rows_copied,
           unified_rows = EXCLUDED.unified_rows,
           recorded_at = CURRENT_TIMESTAMP;
END $$;
'''


def main():
    map_path, out_path = sys.argv[1], sys.argv[2]
    pairs = load_pairs(map_path)
    if not pairs:
        print("no AI table pairs found; refusing to emit an empty migration", file=sys.stderr)
        return 1
    body = [HEADER]
    for legacy, unified in pairs:
        body.append(BLOCK.format(legacy=legacy, unified=unified))
    body.append(FOOTER)
    os.makedirs(os.path.dirname(out_path), exist_ok=True)
    open(out_path, "w", encoding="utf-8", newline="\n").write("".join(body))
    print("wrote %s with %d table copies" % (out_path, len(pairs)))
    return 0


if __name__ == "__main__":
    sys.exit(main())
