"""Convert the legacy ruoyi-ai MySQL DDL for AI-domain tables into PostgreSQL DDL.

The platform's AI domain (chat / agent / knowledge / mcp / aiflow / trace / short-drama)
only ever shipped MySQL DDL, so on PostgreSQL those tables simply did not exist. This
converter produces the missing PostgreSQL definitions for the E2 unified schema.

It is deliberately strict: anything it cannot map is reported as a warning instead of
being dropped, so a reviewer can see exactly which MySQL features did not survive the
conversion. Known, intentional differences:

  * ON UPDATE CURRENT_TIMESTAMP -- PostgreSQL has no column-level equivalent. The
    platform fills update_time in its MyBatis meta object handler, so the behaviour is
    preserved at the application layer; the note is emitted per column.
  * FULLTEXT KEY -- no direct equivalent; reported so it can be replaced by a GIN index
    or dropped deliberately rather than silently.
  * MySQL inline COMMENT -- emitted as a separate COMMENT ON COLUMN statement.
  * AUTO_INCREMENT -- emitted as GENERATED BY DEFAULT AS IDENTITY. MyBatis-Plus assigns
    ids itself (idType=ASSIGN_ID), but the identity keeps direct SQL inserts working.
  * ENGINE/CHARSET/COLLATE/ROW_FORMAT -- MySQL storage options, dropped.

Usage: python mysql-to-postgres.py <mysqlSql> <outFile>
"""
import re
import sys

TYPE_MAP = [
    (re.compile(r"^bigint(\(\d+\))?$", re.I), "bigint"),
    (re.compile(r"^int(\(\d+\))?$", re.I), "integer"),
    (re.compile(r"^tinyint(\(\d+\))?$", re.I), "smallint"),
    (re.compile(r"^smallint(\(\d+\))?$", re.I), "smallint"),
    (re.compile(r"^mediumint(\(\d+\))?$", re.I), "integer"),
    (re.compile(r"^(long|medium)?text$", re.I), "text"),
    (re.compile(r"^(long|medium|tiny)?blob$", re.I), "bytea"),
    (re.compile(r"^datetime(\(\d+\))?$", re.I), "timestamp"),
    (re.compile(r"^timestamp(\(\d+\))?$", re.I), "timestamp"),
    (re.compile(r"^double(\(\d+(,\d+)?\))?$", re.I), "double precision"),
    (re.compile(r"^float(\(\d+(,\d+)?\))?$", re.I), "real"),
    (re.compile(r"^json$", re.I), "jsonb"),
    (re.compile(r"^bit(\(\d+\))?$", re.I), "smallint"),
    (re.compile(r"^decimal", re.I), "numeric"),
    (re.compile(r"^date$", re.I), "date"),
    (re.compile(r"^time$", re.I), "time"),
    (re.compile(r"^char\((\d+)\)$", re.I), None),      # keep as char(n)
    (re.compile(r"^varchar\((\d+)\)$", re.I), None),    # keep as varchar(n)
]

# table -> unified name, per mydocs/platform-embedded/03-table-map.json
RENAME = {
    "chat_model": "ai_model",
    "chat_provider": "ai_model_provider",
    "chat_config": "ai_model_config",
    "chat_session": "ai_conversation",
    "chat_message": "ai_message",
    "agent_info": "ai_agent_profile",
    "knowledge_info": "ai_knowledge_base",
    "knowledge_attach": "ai_knowledge_document",
    "knowledge_fragment": "ai_knowledge_chunk",
    "mcp_market_info": "ai_mcp_market",
    "mcp_market_tool": "ai_mcp_market_tool",
    "mcp_tool_info": "ai_mcp_tool",
    "t_workflow": "ai_flow_workflow",
    "t_workflow_component": "ai_flow_component",
    "t_workflow_edge": "ai_flow_edge",
    "t_workflow_node": "ai_flow_node",
    "t_workflow_runtime": "ai_flow_runtime",
    "t_workflow_runtime_node": "ai_flow_runtime_node",
    "trace_run": "ai_flow_trace_run",
    "trace_node": "ai_flow_trace_node",
    "short_drama_project": "ai_short_drama_project",
    "short_drama_script": "ai_short_drama_script",
    "short_drama_storyboard": "ai_short_drama_storyboard",
    "short_drama_character": "ai_short_drama_character",
    "short_drama_character_appearance": "ai_short_drama_character_appearance",
    "short_drama_location": "ai_short_drama_location",
    "short_drama_audio": "ai_short_drama_audio",
}

WARNINGS = []


def warn(msg):
    WARNINGS.append(msg)


def map_type(mysql_type):
    t = mysql_type.strip()
    # enum/set become text with the original option list preserved as a CHECK-able comment
    m = re.match(r"^(enum|set)\s*\((.*)\)$", t, re.I | re.S)
    if m:
        warn("enum/set converted to varchar(64): %s" % t[:80])
        return "varchar(64)"
    for pattern, replacement in TYPE_MAP:
        if pattern.match(t):
            return replacement if replacement is not None else t.lower()
    warn("unmapped type kept verbatim: %s" % t)
    return t


def split_defs(body):
    """Split on top-level commas, ignoring parentheses AND quoted strings.

    MySQL column comments carry commas and JSON braces (COMMENT 'type=chat, category=chat'),
    so a parenthesis-only splitter tears those definitions apart.
    """
    parts, depth, cur, in_quote = [], 0, [], False
    i = 0
    while i < len(body):
        ch = body[i]
        if in_quote:
            cur.append(ch)
            if ch == "'":
                if i + 1 < len(body) and body[i + 1] == "'":
                    cur.append("'")
                    i += 2
                    continue
                in_quote = False
            elif ch == "\\":
                if i + 1 < len(body):
                    cur.append(body[i + 1])
                    i += 2
                    continue
        else:
            if ch == "'":
                in_quote = True
                cur.append(ch)
            elif ch == "(":
                depth += 1
                cur.append(ch)
            elif ch == ")":
                depth -= 1
                cur.append(ch)
            elif ch == "," and depth == 0:
                parts.append("".join(cur))
                cur = []
            else:
                cur.append(ch)
        i += 1
    if cur:
        parts.append("".join(cur))
    return [p.strip() for p in parts if p.strip()]


def find_body(src, start):
    depth = 0
    for i in range(start, len(src)):
        if src[i] == "(":
            depth += 1
        elif src[i] == ")":
            depth -= 1
            if depth == 0:
                return src[start + 1:i]
    return ""


def convert_table(mysql_name, body, table_comment):
    pg_name = RENAME[mysql_name]
    columns, comments, constraints, indexes, warnings = [], [], [], [], []
    pk_cols = None

    for definition in split_defs(body):
        d = definition.strip()
        head = d.split()[0] if d.split() else ""
        if re.match(r"^(PRIMARY\s+KEY|UNIQUE\s+(?:KEY|INDEX)|KEY|INDEX|FULLTEXT\s+(?:KEY|INDEX)|SPATIAL\s+(?:KEY|INDEX)|CONSTRAINT)", d, re.I):
            if re.match(r"^PRIMARY\s+KEY", d, re.I):
                cols = re.findall(r"`(\w+)`", d)
                pk_cols = cols
            elif re.match(r"^UNIQUE\s+(KEY|INDEX)", d, re.I):
                m = re.match(r"^UNIQUE\s+(?:KEY|INDEX)\s+`(\w+)`\s*\(([^)]*)\)", d, re.I)
                if m:
                    cols = clean_index_cols(m.group(2))
                    constraints.append("CONSTRAINT %s UNIQUE (%s)" % (m.group(1), ", ".join(cols)))
                else:
                    warn("%s: unparsed UNIQUE KEY: %s" % (mysql_name, d[:80]))
            elif re.match(r"^(KEY|INDEX)", d, re.I):
                m = re.match(r"^(?:KEY|INDEX)\s+`(\w+)`\s*\(([^)]*)\)", d, re.I)
                if m:
                    cols = ", ".join(clean_index_cols(m.group(2)))
                    indexes.append((m.group(1), cols))
                else:
                    warn("%s: unparsed KEY: %s" % (mysql_name, d[:80]))
            elif re.match(r"^FULLTEXT\s+(KEY|INDEX)", d, re.I):
                warn("%s: FULLTEXT index dropped (no direct PostgreSQL equivalent; replace with a GIN index if needed): %s" % (mysql_name, d[:80]))
            else:
                warn("%s: unparsed table-level clause: %s" % (mysql_name, d[:80]))
            continue

        if not head.startswith("`"):
            warn("%s: unparsed definition: %s" % (mysql_name, d[:80]))
            continue

        col = head.strip("`")
        rest = d[len(head):].strip()
        type_match = re.match(r"([a-z]+(?:\s*\([^)]*\))?)", rest, re.I)
        mysql_type = type_match.group(1) if type_match else ""
        pg_type = map_type(mysql_type)
        remainder = rest[len(mysql_type):]

        comment = None
        cm = re.search(r"COMMENT\s+'((?:[^']|'')*)'", remainder, re.I)
        if cm:
            comment = cm.group(1).replace("''", "'")
            remainder = remainder[:cm.start()] + remainder[cm.end():]

        has_auto_inc = bool(re.search(r"\bAUTO_INCREMENT\b", remainder, re.I))
        if has_auto_inc:
            remainder = re.sub(r"\bAUTO_INCREMENT\b", "", remainder, flags=re.I)
        if re.search(r"ON\s+UPDATE\s+CURRENT_TIMESTAMP", remainder, re.I):
            warn("%s.%s: ON UPDATE CURRENT_TIMESTAMP dropped; application fills update_time" % (mysql_name, col))
            remainder = re.sub(r"ON\s+UPDATE\s+CURRENT_TIMESTAMP(\(\d+\))?", "", remainder, flags=re.I)

        unsigned = bool(re.search(r"\bunsigned\b", remainder, re.I))
        if unsigned:
            warn("%s.%s: UNSIGNED dropped (PostgreSQL has no unsigned integers)" % (mysql_name, col))
            remainder = re.sub(r"\bunsigned\b", "", remainder, flags=re.I)

        not_null = bool(re.search(r"\bNOT\s+NULL\b", remainder, re.I))
        default = None
        dm = re.search(r"\bDEFAULT\s+('(?:[^']|'')*'|[^\s,]+)", remainder, re.I)
        if dm:
            default = dm.group(1)
            if default.upper() in ("CURRENT_TIMESTAMP", "NOW()", "CURRENT_TIMESTAMP()"):
                default = "CURRENT_TIMESTAMP"
            elif default.upper() in ("NULL",):
                default = "NULL"
        null_clause = " NOT NULL" if not_null else ""
        default_clause = " DEFAULT %s" % default if default else ""
        identity = " GENERATED BY DEFAULT AS IDENTITY" if has_auto_inc else ""
        columns.append('    "%s" %s%s%s%s' % (col, pg_type, identity, null_clause, default_clause))
        if comment:
            comments.append('COMMENT ON COLUMN platform.%s."%s" IS %s;' % (pg_name, col, quote(comment)))

    lines = ["CREATE TABLE IF NOT EXISTS platform.%s (" % pg_name]
    body_lines = list(columns)
    if pk_cols:
        body_lines.append("    PRIMARY KEY (%s)" % ", ".join('"%s"' % c for c in pk_cols))
    body_lines.extend("    %s" % c for c in constraints)
    lines.append(",\n".join(body_lines))
    lines.append(");")
    if table_comment:
        lines.append("COMMENT ON TABLE platform.%s IS %s;" % (pg_name, quote(table_comment)))
    lines.extend(comments)
    for name, cols in indexes:
        lines.append("CREATE INDEX IF NOT EXISTS %s ON platform.%s (%s);" % (name, pg_name, cols))
    return "\n".join(lines), warnings


def clean_index_cols(raw_cols):
    """Drop MySQL index modifiers (ASC/DESC, prefix lengths, USING BTREE) from column lists.

    Implemented as token filtering rather than regex substitution so the modifier handling
    does not depend on escape sequences that are easy to corrupt when the file is patched
    by tooling.
    """
    out = []
    for chunk in raw_cols.split(","):
        kept = []
        for token in chunk.split():
            if token.upper() in ("ASC", "DESC", "USING", "BTREE", "HASH"):
                continue
            kept.append(token)
        name = " ".join(kept).strip().strip("`").strip()
        if "(" in name and name.endswith(")"):
            name = name[: name.index("(")]
        if name:
            out.append(name)
    return out


def quote(text):
    return "'%s'" % text.replace("'", "''")


def main():
    src_path, out_path = sys.argv[1], sys.argv[2]
    raw = open(src_path, encoding="utf-8", errors="replace").read()
    # strip MySQL line comments so they cannot confuse the parser
    raw = "\n".join(re.sub(r"^\s*--.*$", "", line) for line in raw.splitlines())

    blocks, found = [], []
    for mysql_name in RENAME:
        pattern = re.compile(r"CREATE TABLE (?:IF NOT EXISTS )?`%s`\s*\(" % re.escape(mysql_name), re.I)
        m = pattern.search(raw)
        if not m:
            warn("table not found in source: %s" % mysql_name)
            continue
        body = find_body(raw, m.end() - 1)
        tail = raw[m.end() - 1 + len(body) + 1: m.end() - 1 + len(body) + 400]
        tc = re.search(r"COMMENT\s*=\s*'((?:[^']|'')*)'", tail, re.I)
        table_comment = tc.group(1).replace("''", "'") if tc else None
        sql, _ = convert_table(mysql_name, body, table_comment)
        blocks.append("-- ===== %s -> %s =====\n%s\n" % (mysql_name, RENAME[mysql_name], sql))
        found.append(mysql_name)

    header = """-- ---------------------------------------------------------------------------
-- E2 unified AI domain: PostgreSQL DDL for the AI-domain tables that only ever
-- shipped MySQL DDL (chat / agent / knowledge / mcp / aiflow / trace / short-drama).
--
-- Generated by scripts/db/mysql-to-postgres.py from the legacy MySQL install script
-- (services/platform/docs/script/sql/ruoyi-ai.sql and its update/ deltas) plus the E0
-- table map (mydocs/platform-embedded/03-table-map.json).
--
-- Conventions and intentional differences are documented in the generator header.
-- Anything the converter could not map is reported at generation time rather than
-- dropped silently; see the E2 spec for the outstanding list.
-- ---------------------------------------------------------------------------

"""
    open(out_path, "w", encoding="utf-8", newline="\n").write(header + "\n".join(blocks))
    print("tables converted: %d of %d" % (len(found), len(RENAME)))
    if WARNINGS:
        print("warnings (%d):" % len(WARNINGS))
        for w in WARNINGS:
            print("  -", w)
    return 0


if __name__ == "__main__":
    sys.exit(main())
