-- ---------------------------------------------------------------------------
-- E2 unified AI domain: move the legacy MySQL AI-domain rows into `platform`.
--
-- Generated by scripts/db/generate-legacy-ai-copy.py from the E0 table map
-- (mydocs/platform-embedded/03-table-map.json), the legacy MySQL install script
-- (mysql/ruoyi-ai.sql), the frozen AI migrations and the unified DDL (V7..V10).
-- Do not hand-edit the generated parts: change the generator and regenerate.
--
-- Why this exists: V8 copies the legacy `ai` schema and V9/V10 authored the PostgreSQL DDL
-- for the MySQL-only AI domain, but nothing moved *those* rows (E2 spec §5.1b).
--
-- Contract:
--   * The legacy rows must first be loaded into the staging schema `legacy_mysql` with their
--     original MySQL column names (see docs/script/sql/legacy-mysql/10-legacy-ai-domain-staging.sql
--     and the README next to it). No staging schema -> every table is recorded as `absent`
--     and the migration is a no-op, which is the normal fresh-install case.
--   * A table is copied only when every NOT NULL unified column without a default is covered
--     by a same-named legacy column. Otherwise it is recorded as `blocked` with the exact
--     columns that need a platform-side adaptation (E2 §5.1c, E5). Nothing is invented and
--     nothing is mapped by position.
--   * Copies are idempotent: a row whose key is already present is left untouched and counted
--     in rows_skipped_existing.
--   * Narrowing columns are pre-checked; over-long values abort the migration with the row
--     count and samples instead of being truncated.
--   * Every table gets an audit row in platform.ai_legacy_domain_migration_audit and the
--     footer fails the migration if the row accounting does not add up.
-- ---------------------------------------------------------------------------


-- ---------------------------------------------------------------------------
-- 1. Registry: what to copy, how each column maps, and how legacy values translate.
--    All three tables hold generated data; the driver below reads them.
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS platform.ai_legacy_domain_migration_table_map (
    legacy_source   varchar(64)  NOT NULL,
    legacy_table    varchar(128) NOT NULL,
    unified_table   varchar(128) NOT NULL,
    mode            varchar(16)  NOT NULL,
    key_columns     text[]       NOT NULL,
    blocked_reason  text,
    recorded_at     timestamp    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_ai_legacy_domain_table_map PRIMARY KEY (legacy_source, legacy_table),
    CONSTRAINT ck_ai_legacy_domain_table_mode CHECK (mode IN ('copy', 'blocked'))
);
COMMENT ON TABLE platform.ai_legacy_domain_migration_table_map IS
    'E2 旧 MySQL AI 域行迁移：逐表模式（copy=可复制 / blocked=需平台侧适配，原因见 blocked_reason）';
COMMENT ON COLUMN platform.ai_legacy_domain_migration_table_map.key_columns IS
    '幂等判定的键（统一表主键）：复制时按 IS NOT DISTINCT FROM 反连接，已存在的行不改写';

CREATE TABLE IF NOT EXISTS platform.ai_legacy_domain_migration_map (
    legacy_source    varchar(64)  NOT NULL,
    legacy_table     varchar(128) NOT NULL,
    unified_table    varchar(128) NOT NULL,
    legacy_column    varchar(128),
    unified_column   varchar(128) NOT NULL,
    transform        varchar(24)  NOT NULL,
    transform_arg    text,
    legacy_type      varchar(64),
    unified_type     varchar(64),
    unified_length   integer,
    narrowing        boolean      NOT NULL DEFAULT false,
    note             text,
    CONSTRAINT pk_ai_legacy_domain_column_map PRIMARY KEY (legacy_source, legacy_table, unified_column),
    CONSTRAINT ck_ai_legacy_domain_transform
        CHECK (transform IN ('identity', 'cast_text', 'enum', 'coalesce_text', 'constant'))
);
COMMENT ON TABLE platform.ai_legacy_domain_migration_map IS
    'E2 旧 MySQL AI 域行迁移：显式列映射（绝不按位置/隐式映射；transform=enum 时 transform_arg 指向枚举域）';
COMMENT ON COLUMN platform.ai_legacy_domain_migration_map.narrowing IS
    '旧列宽于统一列：复制前做超长预检，超长即报错拒绝，不截断';

CREATE TABLE IF NOT EXISTS platform.ai_legacy_domain_enum_map (
    domain         varchar(64) NOT NULL,
    source_value   varchar(64) NOT NULL,
    target_value   varchar(64) NOT NULL,
    note           text,
    CONSTRAINT pk_ai_legacy_domain_enum_map PRIMARY KEY (domain, source_value)
);
COMMENT ON TABLE platform.ai_legacy_domain_enum_map IS
    'E2 旧 MySQL AI 域行迁移：枚举编码映射（例如 knowledge_attach.status smallint → DocumentStatus 字符串码）';

CREATE TABLE IF NOT EXISTS platform.ai_legacy_domain_migration_audit (
    legacy_source         varchar(64)  NOT NULL,
    legacy_table          varchar(128) NOT NULL,
    unified_table         varchar(128) NOT NULL,
    mode                  varchar(16)  NOT NULL,
    rows_read             bigint       NOT NULL DEFAULT 0,
    rows_inserted         bigint       NOT NULL DEFAULT 0,
    rows_skipped_existing bigint       NOT NULL DEFAULT 0,
    rows_defaulted        bigint       NOT NULL DEFAULT 0,
    unified_rows_before   bigint,
    unified_rows          bigint,
    blocked_reason        text,
    recorded_at           timestamp    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_ai_legacy_domain_audit PRIMARY KEY (legacy_source, legacy_table),
    CONSTRAINT ck_ai_legacy_domain_audit_mode CHECK (mode IN ('copied', 'blocked', 'absent'))
);
COMMENT ON TABLE platform.ai_legacy_domain_migration_audit IS
    'E2 旧 MySQL AI 域行迁移：逐表行数对账（read = inserted + skipped；unified_rows = before + inserted）';
COMMENT ON COLUMN platform.ai_legacy_domain_migration_audit.rows_defaulted IS
    '旧值为 NULL、按注册表取目标侧空表示的行数（coalesce_text），用于让替代可见而非静默';

-- ---------------------------------------------------------------------------
-- 2. Value (enum) mapping, bound to the Java enums that define both sides.
-- ---------------------------------------------------------------------------
-- domain knowledge_document_status: knowledge_attach.status -> ai_knowledge_document.status
--   legacy enum: services/platform/ruoyi-modules/ruoyi-chat/src/main/java/org/ruoyi/enums/KnowledgeAttachStatus.java
--   unified enum: services/ai/rag/src/main/java/com/nageoffer/ai/ragent/knowledge/enums/DocumentStatus.java
INSERT INTO platform.ai_legacy_domain_enum_map
    (domain, source_value, target_value, note)
VALUES
    ('knowledge_document_status', '0', 'pending', 'KnowledgeAttachStatus.WAITING(0) 待解析 → DocumentStatus.PENDING'),
    ('knowledge_document_status', '1', 'running', 'KnowledgeAttachStatus.PARSING(1) 解析中 → DocumentStatus.RUNNING'),
    ('knowledge_document_status', '2', 'success', 'KnowledgeAttachStatus.COMPLETED(2) 已解析 → DocumentStatus.SUCCESS'),
    ('knowledge_document_status', '3', 'failed', 'KnowledgeAttachStatus.FAILED(3) 解析失败 → DocumentStatus.FAILED')
ON CONFLICT (domain, source_value) DO UPDATE
   SET target_value = EXCLUDED.target_value, note = EXCLUDED.note;

-- ---------------------------------------------------------------------------
-- 3. Registry contents (generated). Replaced wholesale for this legacy source so
--    the generator, not the database, decides what the mapping is.
-- ---------------------------------------------------------------------------
DELETE FROM platform.ai_legacy_domain_migration_map WHERE legacy_source = 'mysql/ruoyi-ai.sql';
DELETE FROM platform.ai_legacy_domain_migration_table_map WHERE legacy_source = 'mysql/ruoyi-ai.sql';
INSERT INTO platform.ai_legacy_domain_migration_table_map
    (legacy_source, legacy_table, unified_table, mode, key_columns, blocked_reason)
VALUES
    ('mysql/ruoyi-ai.sql', 'agent_info', 'ai_agent_profile', 'blocked', ARRAY['id']::text[], '统一表 NOT NULL 且无默认值、旧表无同名列：name'),
    ('mysql/ruoyi-ai.sql', 'chat_config', 'ai_model_config', 'copy', ARRAY['id']::text[], NULL),
    ('mysql/ruoyi-ai.sql', 'chat_message', 'ai_message', 'blocked', ARRAY['id']::text[], '统一表 NOT NULL 且无默认值、旧表无同名列：conversation_id, member_id'),
    ('mysql/ruoyi-ai.sql', 'chat_model', 'ai_model', 'copy', ARRAY['id']::text[], NULL),
    ('mysql/ruoyi-ai.sql', 'chat_provider', 'ai_model_provider', 'copy', ARRAY['id']::text[], NULL),
    ('mysql/ruoyi-ai.sql', 'chat_session', 'ai_conversation', 'blocked', ARRAY['id']::text[], '统一表 NOT NULL 且无默认值、旧表无同名列：member_id, title'),
    ('mysql/ruoyi-ai.sql', 'knowledge_attach', 'ai_knowledge_document', 'blocked', ARRAY['id']::text[], '统一表 NOT NULL 且无默认值、旧表无同名列：created_by, doc_name, file_type, file_url, kb_id'),
    ('mysql/ruoyi-ai.sql', 'knowledge_fragment', 'ai_knowledge_chunk', 'blocked', ARRAY['id']::text[], '统一表 NOT NULL 且无默认值、旧表无同名列：chunk_index, created_by, kb_id'),
    ('mysql/ruoyi-ai.sql', 'knowledge_info', 'ai_knowledge_base', 'blocked', ARRAY['id']::text[], '统一表 NOT NULL 且无默认值、旧表无同名列：collection_name, created_by, owner_member_id'),
    ('mysql/ruoyi-ai.sql', 'mcp_market_info', 'ai_mcp_market', 'copy', ARRAY['id']::text[], NULL),
    ('mysql/ruoyi-ai.sql', 'mcp_market_tool', 'ai_mcp_market_tool', 'copy', ARRAY['id']::text[], NULL),
    ('mysql/ruoyi-ai.sql', 'mcp_tool_info', 'ai_mcp_tool', 'copy', ARRAY['id']::text[], NULL),
    ('mysql/ruoyi-ai.sql', 'short_drama_audio', 'ai_short_drama_audio', 'copy', ARRAY['id']::text[], NULL),
    ('mysql/ruoyi-ai.sql', 'short_drama_character', 'ai_short_drama_character', 'copy', ARRAY['id']::text[], NULL),
    ('mysql/ruoyi-ai.sql', 'short_drama_character_appearance', 'ai_short_drama_character_appearance', 'copy', ARRAY['id']::text[], NULL),
    ('mysql/ruoyi-ai.sql', 'short_drama_location', 'ai_short_drama_location', 'copy', ARRAY['id']::text[], NULL),
    ('mysql/ruoyi-ai.sql', 'short_drama_project', 'ai_short_drama_project', 'copy', ARRAY['id']::text[], NULL),
    ('mysql/ruoyi-ai.sql', 'short_drama_script', 'ai_short_drama_script', 'copy', ARRAY['id']::text[], NULL),
    ('mysql/ruoyi-ai.sql', 'short_drama_storyboard', 'ai_short_drama_storyboard', 'copy', ARRAY['id']::text[], NULL),
    ('mysql/ruoyi-ai.sql', 't_workflow', 'ai_flow_workflow', 'copy', ARRAY['id']::text[], NULL),
    ('mysql/ruoyi-ai.sql', 't_workflow_component', 'ai_flow_component', 'copy', ARRAY['id']::text[], NULL),
    ('mysql/ruoyi-ai.sql', 't_workflow_edge', 'ai_flow_edge', 'copy', ARRAY['id']::text[], NULL),
    ('mysql/ruoyi-ai.sql', 't_workflow_node', 'ai_flow_node', 'copy', ARRAY['id']::text[], NULL),
    ('mysql/ruoyi-ai.sql', 't_workflow_runtime', 'ai_flow_runtime', 'copy', ARRAY['id']::text[], NULL),
    ('mysql/ruoyi-ai.sql', 't_workflow_runtime_node', 'ai_flow_runtime_node', 'copy', ARRAY['id']::text[], NULL),
    ('mysql/ruoyi-ai.sql', 'trace_node', 'ai_flow_trace_node', 'copy', ARRAY['id']::text[], NULL),
    ('mysql/ruoyi-ai.sql', 'trace_run', 'ai_flow_trace_run', 'copy', ARRAY['id']::text[], NULL);
INSERT INTO platform.ai_legacy_domain_migration_map
    (legacy_source, legacy_table, unified_table, legacy_column, unified_column,
     transform, transform_arg, legacy_type, unified_type, unified_length,
     narrowing, note)
VALUES
    ('mysql/ruoyi-ai.sql', 'agent_info', 'ai_agent_profile', 'agent_describe', 'agent_describe', 'identity', NULL, 'varchar', 'varchar', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 'agent_info', 'ai_agent_profile', 'agent_name', 'agent_name', 'identity', NULL, 'varchar', 'varchar', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 'agent_info', 'ai_agent_profile', 'agent_show', 'agent_show', 'identity', NULL, 'varchar', 'varchar', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 'agent_info', 'ai_agent_profile', 'create_by', 'create_by', 'cast_text', NULL, 'bigint null', 'varchar', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 'agent_info', 'ai_agent_profile', 'create_dept', 'create_dept', 'identity', NULL, 'bigint null', 'bigint', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 'agent_info', 'ai_agent_profile', 'create_time', 'create_time', 'identity', NULL, 'datetime null', 'timestamp', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 'agent_info', 'ai_agent_profile', 'enable_thinking', 'enable_thinking', 'identity', NULL, 'char', 'char', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 'agent_info', 'ai_agent_profile', 'id', 'id', 'cast_text', NULL, 'bigint', 'varchar', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 'agent_info', 'ai_agent_profile', 'knowledge_ids', 'knowledge_ids', 'identity', NULL, 'varchar', 'varchar', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 'agent_info', 'ai_agent_profile', 'mcp_tool_ids', 'mcp_tool_ids', 'identity', NULL, 'varchar', 'varchar', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 'agent_info', 'ai_agent_profile', 'model_id', 'model_id', 'identity', NULL, 'bigint', 'bigint', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 'agent_info', 'ai_agent_profile', 'remark', 'remark', 'identity', NULL, 'varchar', 'varchar', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 'agent_info', 'ai_agent_profile', 'skill_names', 'skill_names', 'identity', NULL, 'varchar', 'varchar', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 'agent_info', 'ai_agent_profile', 'status', 'status', 'identity', NULL, 'char', 'char', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 'agent_info', 'ai_agent_profile', 'system_prompt', 'system_prompt', 'cast_text', NULL, '', 'text', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 'agent_info', 'ai_agent_profile', 'tenant_id', 'tenant_id', 'cast_text', NULL, 'bigint', 'varchar', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 'agent_info', 'ai_agent_profile', 'update_by', 'update_by', 'cast_text', NULL, 'bigint null', 'varchar', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 'agent_info', 'ai_agent_profile', 'update_time', 'update_time', 'identity', NULL, 'datetime null', 'timestamp', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 'chat_config', 'ai_model_config', 'category', 'category', 'identity', NULL, 'varchar', 'varchar', NULL, false, '旧表在任何脚本中都没有 DDL（V10 依据 Java 实体 org.ruoyi.system.domain.ChatConfig 补写）：列名沿用目标列名，实际形状以 MySQL 目录为准，不一致时迁移拒绝复制'),
    ('mysql/ruoyi-ai.sql', 'chat_config', 'ai_model_config', 'config_dict', 'config_dict', 'identity', NULL, 'varchar', 'varchar', NULL, false, '旧表在任何脚本中都没有 DDL（V10 依据 Java 实体 org.ruoyi.system.domain.ChatConfig 补写）：列名沿用目标列名，实际形状以 MySQL 目录为准，不一致时迁移拒绝复制'),
    ('mysql/ruoyi-ai.sql', 'chat_config', 'ai_model_config', 'config_name', 'config_name', 'identity', NULL, 'varchar', 'varchar', NULL, false, '旧表在任何脚本中都没有 DDL（V10 依据 Java 实体 org.ruoyi.system.domain.ChatConfig 补写）：列名沿用目标列名，实际形状以 MySQL 目录为准，不一致时迁移拒绝复制'),
    ('mysql/ruoyi-ai.sql', 'chat_config', 'ai_model_config', 'config_value', 'config_value', 'identity', NULL, 'varchar', 'varchar', NULL, false, '旧表在任何脚本中都没有 DDL（V10 依据 Java 实体 org.ruoyi.system.domain.ChatConfig 补写）：列名沿用目标列名，实际形状以 MySQL 目录为准，不一致时迁移拒绝复制'),
    ('mysql/ruoyi-ai.sql', 'chat_config', 'ai_model_config', 'create_by', 'create_by', 'identity', NULL, 'bigint', 'bigint', NULL, false, '旧表在任何脚本中都没有 DDL（V10 依据 Java 实体 org.ruoyi.system.domain.ChatConfig 补写）：列名沿用目标列名，实际形状以 MySQL 目录为准，不一致时迁移拒绝复制'),
    ('mysql/ruoyi-ai.sql', 'chat_config', 'ai_model_config', 'create_dept', 'create_dept', 'identity', NULL, 'bigint', 'bigint', NULL, false, '旧表在任何脚本中都没有 DDL（V10 依据 Java 实体 org.ruoyi.system.domain.ChatConfig 补写）：列名沿用目标列名，实际形状以 MySQL 目录为准，不一致时迁移拒绝复制'),
    ('mysql/ruoyi-ai.sql', 'chat_config', 'ai_model_config', 'create_time', 'create_time', 'identity', NULL, 'timestamp', 'timestamp', NULL, false, '旧表在任何脚本中都没有 DDL（V10 依据 Java 实体 org.ruoyi.system.domain.ChatConfig 补写）：列名沿用目标列名，实际形状以 MySQL 目录为准，不一致时迁移拒绝复制'),
    ('mysql/ruoyi-ai.sql', 'chat_config', 'ai_model_config', 'del_flag', 'del_flag', 'identity', NULL, 'char', 'char', NULL, false, '旧表在任何脚本中都没有 DDL（V10 依据 Java 实体 org.ruoyi.system.domain.ChatConfig 补写）：列名沿用目标列名，实际形状以 MySQL 目录为准，不一致时迁移拒绝复制'),
    ('mysql/ruoyi-ai.sql', 'chat_config', 'ai_model_config', 'id', 'id', 'identity', NULL, 'bigint', 'bigint', NULL, false, '旧表在任何脚本中都没有 DDL（V10 依据 Java 实体 org.ruoyi.system.domain.ChatConfig 补写）：列名沿用目标列名，实际形状以 MySQL 目录为准，不一致时迁移拒绝复制'),
    ('mysql/ruoyi-ai.sql', 'chat_config', 'ai_model_config', 'remark', 'remark', 'identity', NULL, 'varchar', 'varchar', NULL, false, '旧表在任何脚本中都没有 DDL（V10 依据 Java 实体 org.ruoyi.system.domain.ChatConfig 补写）：列名沿用目标列名，实际形状以 MySQL 目录为准，不一致时迁移拒绝复制'),
    ('mysql/ruoyi-ai.sql', 'chat_config', 'ai_model_config', 'tenant_id', 'tenant_id', 'identity', NULL, 'varchar', 'varchar', NULL, false, '旧表在任何脚本中都没有 DDL（V10 依据 Java 实体 org.ruoyi.system.domain.ChatConfig 补写）：列名沿用目标列名，实际形状以 MySQL 目录为准，不一致时迁移拒绝复制'),
    ('mysql/ruoyi-ai.sql', 'chat_config', 'ai_model_config', 'update_by', 'update_by', 'identity', NULL, 'bigint', 'bigint', NULL, false, '旧表在任何脚本中都没有 DDL（V10 依据 Java 实体 org.ruoyi.system.domain.ChatConfig 补写）：列名沿用目标列名，实际形状以 MySQL 目录为准，不一致时迁移拒绝复制'),
    ('mysql/ruoyi-ai.sql', 'chat_config', 'ai_model_config', 'update_ip', 'update_ip', 'identity', NULL, 'varchar', 'varchar', NULL, false, '旧表在任何脚本中都没有 DDL（V10 依据 Java 实体 org.ruoyi.system.domain.ChatConfig 补写）：列名沿用目标列名，实际形状以 MySQL 目录为准，不一致时迁移拒绝复制'),
    ('mysql/ruoyi-ai.sql', 'chat_config', 'ai_model_config', 'update_time', 'update_time', 'identity', NULL, 'timestamp', 'timestamp', NULL, false, '旧表在任何脚本中都没有 DDL（V10 依据 Java 实体 org.ruoyi.system.domain.ChatConfig 补写）：列名沿用目标列名，实际形状以 MySQL 目录为准，不一致时迁移拒绝复制'),
    ('mysql/ruoyi-ai.sql', 'chat_config', 'ai_model_config', 'version', 'version', 'identity', NULL, 'bigint', 'bigint', NULL, false, '旧表在任何脚本中都没有 DDL（V10 依据 Java 实体 org.ruoyi.system.domain.ChatConfig 补写）：列名沿用目标列名，实际形状以 MySQL 目录为准，不一致时迁移拒绝复制'),
    ('mysql/ruoyi-ai.sql', 'chat_message', 'ai_message', 'content', 'content', 'cast_text', NULL, '', 'text', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 'chat_message', 'ai_message', 'create_by', 'create_by', 'identity', NULL, 'bigint null', 'bigint', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 'chat_message', 'ai_message', 'create_dept', 'create_dept', 'identity', NULL, 'bigint null', 'bigint', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 'chat_message', 'ai_message', 'create_time', 'create_time', 'identity', NULL, 'datetime null', 'timestamp', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 'chat_message', 'ai_message', 'id', 'id', 'cast_text', NULL, 'bigint', 'varchar', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 'chat_message', 'ai_message', 'model_name', 'model_name', 'identity', NULL, 'varchar', 'varchar', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 'chat_message', 'ai_message', 'remark', 'remark', 'identity', NULL, 'varchar', 'varchar', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 'chat_message', 'ai_message', 'role', 'role', 'identity', NULL, 'varchar', 'varchar', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 'chat_message', 'ai_message', 'session_id', 'session_id', 'identity', NULL, 'bigint null', 'bigint', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 'chat_message', 'ai_message', 'tenant_id', 'tenant_id', 'cast_text', NULL, 'bigint', 'varchar', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 'chat_message', 'ai_message', 'total_tokens', 'total_tokens', 'identity', NULL, 'int null', 'integer', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 'chat_message', 'ai_message', 'update_by', 'update_by', 'identity', NULL, 'bigint null', 'bigint', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 'chat_message', 'ai_message', 'update_time', 'update_time', 'identity', NULL, 'datetime null', 'timestamp', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 'chat_message', 'ai_message', 'user_id', 'user_id', 'cast_text', NULL, 'bigint', 'varchar', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 'chat_model', 'ai_model', 'api_host', 'api_host', 'identity', NULL, 'varchar', 'varchar', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 'chat_model', 'ai_model', 'api_key', 'api_key', 'identity', NULL, 'varchar', 'varchar', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 'chat_model', 'ai_model', 'category', 'category', 'identity', NULL, 'varchar', 'varchar', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 'chat_model', 'ai_model', 'create_by', 'create_by', 'identity', NULL, 'bigint null', 'bigint', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 'chat_model', 'ai_model', 'create_dept', 'create_dept', 'identity', NULL, 'bigint null', 'bigint', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 'chat_model', 'ai_model', 'create_time', 'create_time', 'identity', NULL, 'datetime null', 'timestamp', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 'chat_model', 'ai_model', 'id', 'id', 'identity', NULL, 'bigint', 'bigint', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 'chat_model', 'ai_model', 'model_describe', 'model_describe', 'identity', NULL, 'varchar', 'varchar', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 'chat_model', 'ai_model', 'model_dimension', 'model_dimension', 'identity', NULL, 'int null', 'integer', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 'chat_model', 'ai_model', 'model_name', 'model_name', 'identity', NULL, 'varchar', 'varchar', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 'chat_model', 'ai_model', 'model_show', 'model_show', 'identity', NULL, 'char', 'char', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 'chat_model', 'ai_model', 'provider_code', 'provider_code', 'identity', NULL, 'varchar', 'varchar', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 'chat_model', 'ai_model', 'remark', 'remark', 'identity', NULL, 'varchar', 'varchar', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 'chat_model', 'ai_model', 'tenant_id', 'tenant_id', 'cast_text', NULL, 'bigint', 'varchar', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 'chat_model', 'ai_model', 'update_by', 'update_by', 'identity', NULL, 'bigint null', 'bigint', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 'chat_model', 'ai_model', 'update_time', 'update_time', 'identity', NULL, 'datetime null', 'timestamp', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 'chat_provider', 'ai_model_provider', 'api_host', 'api_host', 'identity', NULL, 'varchar', 'varchar', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 'chat_provider', 'ai_model_provider', 'create_by', 'create_by', 'identity', NULL, 'varchar', 'varchar', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 'chat_provider', 'ai_model_provider', 'create_dept', 'create_dept', 'identity', NULL, 'bigint null', 'bigint', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 'chat_provider', 'ai_model_provider', 'create_time', 'create_time', 'identity', NULL, 'datetime null', 'timestamp', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 'chat_provider', 'ai_model_provider', 'del_flag', 'del_flag', 'identity', NULL, 'char', 'char', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 'chat_provider', 'ai_model_provider', 'id', 'id', 'identity', NULL, 'bigint', 'bigint', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 'chat_provider', 'ai_model_provider', 'provider_code', 'provider_code', 'identity', NULL, 'varchar', 'varchar', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 'chat_provider', 'ai_model_provider', 'provider_desc', 'provider_desc', 'identity', NULL, 'varchar', 'varchar', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 'chat_provider', 'ai_model_provider', 'provider_icon', 'provider_icon', 'identity', NULL, 'varchar', 'varchar', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 'chat_provider', 'ai_model_provider', 'provider_name', 'provider_name', 'identity', NULL, 'varchar', 'varchar', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 'chat_provider', 'ai_model_provider', 'remark', 'remark', 'identity', NULL, 'varchar', 'varchar', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 'chat_provider', 'ai_model_provider', 'sort_order', 'sort_order', 'identity', NULL, 'int null', 'integer', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 'chat_provider', 'ai_model_provider', 'status', 'status', 'identity', NULL, 'char', 'char', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 'chat_provider', 'ai_model_provider', 'tenant_id', 'tenant_id', 'cast_text', NULL, 'bigint', 'varchar', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 'chat_provider', 'ai_model_provider', 'update_by', 'update_by', 'identity', NULL, 'varchar', 'varchar', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 'chat_provider', 'ai_model_provider', 'update_ip', 'update_ip', 'identity', NULL, 'varchar', 'varchar', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 'chat_provider', 'ai_model_provider', 'update_time', 'update_time', 'identity', NULL, 'datetime null', 'timestamp', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 'chat_provider', 'ai_model_provider', 'version', 'version', 'identity', NULL, 'int null', 'integer', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 'chat_session', 'ai_conversation', 'conversation_id', 'conversation_id', 'identity', NULL, 'varchar', 'varchar', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 'chat_session', 'ai_conversation', 'create_by', 'create_by', 'identity', NULL, 'bigint null', 'bigint', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 'chat_session', 'ai_conversation', 'create_dept', 'create_dept', 'identity', NULL, 'varchar', 'varchar', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 'chat_session', 'ai_conversation', 'create_time', 'create_time', 'identity', NULL, 'datetime null', 'timestamp', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 'chat_session', 'ai_conversation', 'id', 'id', 'cast_text', NULL, 'bigint', 'varchar', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 'chat_session', 'ai_conversation', 'remark', 'remark', 'identity', NULL, 'varchar', 'varchar', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 'chat_session', 'ai_conversation', 'session_content', 'session_content', 'cast_text', NULL, '', 'text', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 'chat_session', 'ai_conversation', 'session_title', 'session_title', 'identity', NULL, 'varchar', 'varchar', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 'chat_session', 'ai_conversation', 'tenant_id', 'tenant_id', 'cast_text', NULL, 'bigint', 'varchar', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 'chat_session', 'ai_conversation', 'update_by', 'update_by', 'identity', NULL, 'bigint null', 'bigint', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 'chat_session', 'ai_conversation', 'update_time', 'update_time', 'identity', NULL, 'datetime null', 'timestamp', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 'chat_session', 'ai_conversation', 'user_id', 'user_id', 'cast_text', NULL, 'bigint null', 'varchar', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 'knowledge_attach', 'ai_knowledge_document', 'create_by', 'create_by', 'identity', NULL, 'varchar', 'varchar', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 'knowledge_attach', 'ai_knowledge_document', 'create_dept', 'create_dept', 'identity', NULL, 'varchar', 'varchar', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 'knowledge_attach', 'ai_knowledge_document', 'create_time', 'create_time', 'identity', NULL, 'datetime null', 'timestamp', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 'knowledge_attach', 'ai_knowledge_document', 'doc_id', 'doc_id', 'identity', NULL, 'varchar', 'varchar', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 'knowledge_attach', 'ai_knowledge_document', 'file_hash', 'file_hash', 'identity', NULL, 'varchar', 'varchar', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 'knowledge_attach', 'ai_knowledge_document', 'id', 'id', 'cast_text', NULL, 'bigint', 'varchar', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 'knowledge_attach', 'ai_knowledge_document', 'knowledge_id', 'knowledge_id', 'identity', NULL, 'bigint', 'bigint', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 'knowledge_attach', 'ai_knowledge_document', 'name', 'name', 'identity', NULL, 'varchar', 'varchar', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 'knowledge_attach', 'ai_knowledge_document', 'oss_id', 'oss_id', 'identity', NULL, 'bigint null', 'bigint', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 'knowledge_attach', 'ai_knowledge_document', 'remark', 'remark', 'identity', NULL, 'varchar', 'varchar', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 'knowledge_attach', 'ai_knowledge_document', 'status', 'status', 'enum', 'knowledge_document_status', 'tinyint null', 'varchar', NULL, false, '枚举编码映射（domain=knowledge_document_status）：smallint 编码 → 字符串状态码，取值映射见 platform.ai_legacy_domain_enum_map'),
    ('mysql/ruoyi-ai.sql', 'knowledge_attach', 'ai_knowledge_document', 'tenant_id', 'tenant_id', 'cast_text', NULL, 'bigint', 'varchar', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 'knowledge_attach', 'ai_knowledge_document', 'type', 'type', 'identity', NULL, 'varchar', 'varchar', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 'knowledge_attach', 'ai_knowledge_document', 'update_by', 'update_by', 'identity', NULL, 'bigint null', 'bigint', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 'knowledge_attach', 'ai_knowledge_document', 'update_time', 'update_time', 'identity', NULL, 'datetime null', 'timestamp', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 'knowledge_fragment', 'ai_knowledge_chunk', 'content', 'content', 'cast_text', NULL, '', 'text', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 'knowledge_fragment', 'ai_knowledge_chunk', 'create_by', 'create_by', 'identity', NULL, 'varchar', 'varchar', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 'knowledge_fragment', 'ai_knowledge_chunk', 'create_dept', 'create_dept', 'identity', NULL, 'varchar', 'varchar', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 'knowledge_fragment', 'ai_knowledge_chunk', 'create_time', 'create_time', 'identity', NULL, 'datetime null', 'timestamp', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 'knowledge_fragment', 'ai_knowledge_chunk', 'doc_id', 'doc_id', 'identity', NULL, 'varchar', 'varchar', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 'knowledge_fragment', 'ai_knowledge_chunk', 'fid', 'fid', 'identity', NULL, 'varchar', 'varchar', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 'knowledge_fragment', 'ai_knowledge_chunk', 'id', 'id', 'cast_text', NULL, 'bigint', 'varchar', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 'knowledge_fragment', 'ai_knowledge_chunk', 'idx', 'idx', 'identity', NULL, 'int', 'integer', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 'knowledge_fragment', 'ai_knowledge_chunk', 'knowledge_id', 'knowledge_id', 'identity', NULL, 'bigint null', 'bigint', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 'knowledge_fragment', 'ai_knowledge_chunk', 'remark', 'remark', 'identity', NULL, 'varchar', 'varchar', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 'knowledge_fragment', 'ai_knowledge_chunk', 'tenant_id', 'tenant_id', 'cast_text', NULL, 'bigint', 'varchar', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 'knowledge_fragment', 'ai_knowledge_chunk', 'update_by', 'update_by', 'identity', NULL, 'bigint null', 'bigint', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 'knowledge_fragment', 'ai_knowledge_chunk', 'update_time', 'update_time', 'identity', NULL, 'datetime null', 'timestamp', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 'knowledge_info', 'ai_knowledge_base', 'create_by', 'create_by', 'identity', NULL, 'varchar', 'varchar', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 'knowledge_info', 'ai_knowledge_base', 'create_dept', 'create_dept', 'identity', NULL, 'varchar', 'varchar', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 'knowledge_info', 'ai_knowledge_base', 'create_time', 'create_time', 'identity', NULL, 'datetime null', 'timestamp', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 'knowledge_info', 'ai_knowledge_base', 'description', 'description', 'identity', NULL, 'varchar', 'varchar', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 'knowledge_info', 'ai_knowledge_base', 'embedding_model', 'embedding_model', 'identity', NULL, 'varchar', 'varchar', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 'knowledge_info', 'ai_knowledge_base', 'enable_hybrid', 'enable_hybrid', 'identity', NULL, 'tinyint', 'smallint', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 'knowledge_info', 'ai_knowledge_base', 'enable_rerank', 'enable_rerank', 'identity', NULL, 'tinyint null', 'smallint', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 'knowledge_info', 'ai_knowledge_base', 'hybrid_alpha', 'hybrid_alpha', 'identity', NULL, 'double null', 'double precision', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 'knowledge_info', 'ai_knowledge_base', 'id', 'id', 'cast_text', NULL, 'bigint', 'varchar', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 'knowledge_info', 'ai_knowledge_base', 'name', 'name', 'identity', NULL, 'varchar', 'varchar', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 'knowledge_info', 'ai_knowledge_base', 'overlap_char', 'overlap_char', 'identity', NULL, 'int null', 'integer', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 'knowledge_info', 'ai_knowledge_base', 'remark', 'remark', 'identity', NULL, 'varchar', 'varchar', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 'knowledge_info', 'ai_knowledge_base', 'rerank_model', 'rerank_model', 'identity', NULL, 'varchar', 'varchar', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 'knowledge_info', 'ai_knowledge_base', 'rerank_score_threshold', 'rerank_score_threshold', 'identity', NULL, 'double null', 'double precision', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 'knowledge_info', 'ai_knowledge_base', 'rerank_top_n', 'rerank_top_n', 'identity', NULL, 'int null', 'integer', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 'knowledge_info', 'ai_knowledge_base', 'retrieve_limit', 'retrieve_limit', 'identity', NULL, 'int null', 'integer', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 'knowledge_info', 'ai_knowledge_base', 'separator', 'separator', 'identity', NULL, 'varchar', 'varchar', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 'knowledge_info', 'ai_knowledge_base', 'share', 'share', 'identity', NULL, 'tinyint null', 'smallint', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 'knowledge_info', 'ai_knowledge_base', 'similarity_threshold', 'similarity_threshold', 'identity', NULL, 'double null', 'double precision', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 'knowledge_info', 'ai_knowledge_base', 'system_prompt', 'system_prompt', 'cast_text', NULL, '', 'text', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 'knowledge_info', 'ai_knowledge_base', 'tenant_id', 'tenant_id', 'cast_text', NULL, 'bigint', 'varchar', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 'knowledge_info', 'ai_knowledge_base', 'text_block_size', 'text_block_size', 'identity', NULL, 'int null', 'integer', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 'knowledge_info', 'ai_knowledge_base', 'update_by', 'update_by', 'identity', NULL, 'bigint null', 'bigint', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 'knowledge_info', 'ai_knowledge_base', 'update_time', 'update_time', 'identity', NULL, 'datetime null', 'timestamp', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 'knowledge_info', 'ai_knowledge_base', 'user_id', 'user_id', 'identity', NULL, 'bigint', 'bigint', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 'knowledge_info', 'ai_knowledge_base', 'vector_model', 'vector_model', 'identity', NULL, 'varchar', 'varchar', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 'mcp_market_info', 'ai_mcp_market', 'auth_config', 'auth_config', 'cast_text', NULL, '', 'text', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 'mcp_market_info', 'ai_mcp_market', 'create_by', 'create_by', 'identity', NULL, 'bigint null', 'bigint', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 'mcp_market_info', 'ai_mcp_market', 'create_dept', 'create_dept', 'identity', NULL, 'bigint null', 'bigint', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 'mcp_market_info', 'ai_mcp_market', 'create_time', 'create_time', 'identity', NULL, 'datetime null', 'timestamp', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 'mcp_market_info', 'ai_mcp_market', 'del_flag', 'del_flag', 'identity', NULL, 'char', 'char', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 'mcp_market_info', 'ai_mcp_market', 'description', 'description', 'cast_text', NULL, '', 'text', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 'mcp_market_info', 'ai_mcp_market', 'id', 'id', 'identity', NULL, 'bigint', 'bigint', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 'mcp_market_info', 'ai_mcp_market', 'name', 'name', 'identity', NULL, 'varchar', 'varchar', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 'mcp_market_info', 'ai_mcp_market', 'status', 'status', 'identity', NULL, 'varchar', 'varchar', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 'mcp_market_info', 'ai_mcp_market', 'tenant_id', 'tenant_id', 'identity', NULL, 'varchar', 'varchar', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 'mcp_market_info', 'ai_mcp_market', 'update_by', 'update_by', 'identity', NULL, 'bigint null', 'bigint', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 'mcp_market_info', 'ai_mcp_market', 'update_time', 'update_time', 'identity', NULL, 'datetime null', 'timestamp', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 'mcp_market_info', 'ai_mcp_market', 'url', 'url', 'identity', NULL, 'varchar', 'varchar', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 'mcp_market_tool', 'ai_mcp_market_tool', 'create_by', 'create_by', 'identity', NULL, 'bigint null', 'bigint', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 'mcp_market_tool', 'ai_mcp_market_tool', 'create_dept', 'create_dept', 'identity', NULL, 'bigint null', 'bigint', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 'mcp_market_tool', 'ai_mcp_market_tool', 'create_time', 'create_time', 'identity', NULL, 'datetime null', 'timestamp', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 'mcp_market_tool', 'ai_mcp_market_tool', 'id', 'id', 'identity', NULL, 'bigint', 'bigint', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 'mcp_market_tool', 'ai_mcp_market_tool', 'is_loaded', 'is_loaded', 'identity', NULL, 'tinyint', 'smallint', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 'mcp_market_tool', 'ai_mcp_market_tool', 'local_tool_id', 'local_tool_id', 'identity', NULL, 'bigint null', 'bigint', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 'mcp_market_tool', 'ai_mcp_market_tool', 'market_id', 'market_id', 'identity', NULL, 'bigint', 'bigint', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 'mcp_market_tool', 'ai_mcp_market_tool', 'tenant_id', 'tenant_id', 'identity', NULL, 'varchar', 'varchar', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 'mcp_market_tool', 'ai_mcp_market_tool', 'tool_description', 'tool_description', 'cast_text', NULL, '', 'text', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 'mcp_market_tool', 'ai_mcp_market_tool', 'tool_metadata', 'tool_metadata', 'identity', NULL, '', 'jsonb', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 'mcp_market_tool', 'ai_mcp_market_tool', 'tool_name', 'tool_name', 'identity', NULL, 'varchar', 'varchar', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 'mcp_market_tool', 'ai_mcp_market_tool', 'tool_version', 'tool_version', 'identity', NULL, 'varchar', 'varchar', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 'mcp_market_tool', 'ai_mcp_market_tool', 'update_by', 'update_by', 'identity', NULL, 'bigint null', 'bigint', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 'mcp_market_tool', 'ai_mcp_market_tool', 'update_time', 'update_time', 'identity', NULL, 'datetime null', 'timestamp', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 'mcp_tool_info', 'ai_mcp_tool', 'config_json', 'config_json', 'cast_text', NULL, '', 'text', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 'mcp_tool_info', 'ai_mcp_tool', 'create_by', 'create_by', 'identity', NULL, 'bigint null', 'bigint', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 'mcp_tool_info', 'ai_mcp_tool', 'create_dept', 'create_dept', 'identity', NULL, 'bigint null', 'bigint', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 'mcp_tool_info', 'ai_mcp_tool', 'create_time', 'create_time', 'identity', NULL, 'datetime null', 'timestamp', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 'mcp_tool_info', 'ai_mcp_tool', 'del_flag', 'del_flag', 'identity', NULL, 'char', 'char', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 'mcp_tool_info', 'ai_mcp_tool', 'description', 'description', 'cast_text', NULL, '', 'text', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 'mcp_tool_info', 'ai_mcp_tool', 'id', 'id', 'identity', NULL, 'bigint', 'bigint', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 'mcp_tool_info', 'ai_mcp_tool', 'name', 'name', 'identity', NULL, 'varchar', 'varchar', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 'mcp_tool_info', 'ai_mcp_tool', 'status', 'status', 'identity', NULL, 'varchar', 'varchar', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 'mcp_tool_info', 'ai_mcp_tool', 'tenant_id', 'tenant_id', 'identity', NULL, 'varchar', 'varchar', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 'mcp_tool_info', 'ai_mcp_tool', 'type', 'type', 'identity', NULL, 'varchar', 'varchar', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 'mcp_tool_info', 'ai_mcp_tool', 'update_by', 'update_by', 'identity', NULL, 'bigint null', 'bigint', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 'mcp_tool_info', 'ai_mcp_tool', 'update_time', 'update_time', 'identity', NULL, 'datetime null', 'timestamp', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 'short_drama_audio', 'ai_short_drama_audio', 'audio_oss_id', 'audio_oss_id', 'identity', NULL, 'bigint null', 'bigint', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 'short_drama_audio', 'ai_short_drama_audio', 'audio_type', 'audio_type', 'identity', NULL, 'varchar', 'varchar', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 'short_drama_audio', 'ai_short_drama_audio', 'audio_url', 'audio_url', 'cast_text', NULL, '', 'text', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 'short_drama_audio', 'ai_short_drama_audio', 'create_by', 'create_by', 'identity', NULL, 'bigint null', 'bigint', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 'short_drama_audio', 'ai_short_drama_audio', 'create_dept', 'create_dept', 'identity', NULL, 'bigint null', 'bigint', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 'short_drama_audio', 'ai_short_drama_audio', 'create_time', 'create_time', 'identity', NULL, 'datetime null', 'timestamp', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 'short_drama_audio', 'ai_short_drama_audio', 'duration_seconds', 'duration_seconds', 'identity', NULL, 'int null', 'integer', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 'short_drama_audio', 'ai_short_drama_audio', 'id', 'id', 'identity', NULL, 'bigint', 'bigint', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 'short_drama_audio', 'ai_short_drama_audio', 'linked_storyboard_id', 'linked_storyboard_id', 'identity', NULL, 'bigint null', 'bigint', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 'short_drama_audio', 'ai_short_drama_audio', 'name', 'name', 'identity', NULL, 'varchar', 'varchar', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 'short_drama_audio', 'ai_short_drama_audio', 'project_id', 'project_id', 'identity', NULL, 'bigint', 'bigint', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 'short_drama_audio', 'ai_short_drama_audio', 'tenant_id', 'tenant_id', 'cast_text', NULL, 'bigint', 'varchar', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 'short_drama_audio', 'ai_short_drama_audio', 'text', 'text', 'cast_text', NULL, '', 'text', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 'short_drama_audio', 'ai_short_drama_audio', 'update_by', 'update_by', 'identity', NULL, 'bigint null', 'bigint', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 'short_drama_audio', 'ai_short_drama_audio', 'update_time', 'update_time', 'identity', NULL, 'datetime null', 'timestamp', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 'short_drama_audio', 'ai_short_drama_audio', 'voice', 'voice', 'identity', NULL, 'varchar', 'varchar', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 'short_drama_character', 'ai_short_drama_character', 'age_range', 'age_range', 'identity', NULL, 'varchar', 'varchar', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 'short_drama_character', 'ai_short_drama_character', 'aliases', 'aliases', 'identity', NULL, 'varchar', 'varchar', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 'short_drama_character', 'ai_short_drama_character', 'costume_tier', 'costume_tier', 'identity', NULL, 'int null', 'integer', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 'short_drama_character', 'ai_short_drama_character', 'create_by', 'create_by', 'identity', NULL, 'bigint null', 'bigint', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 'short_drama_character', 'ai_short_drama_character', 'create_dept', 'create_dept', 'identity', NULL, 'bigint null', 'bigint', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 'short_drama_character', 'ai_short_drama_character', 'create_time', 'create_time', 'identity', NULL, 'datetime null', 'timestamp', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 'short_drama_character', 'ai_short_drama_character', 'gender', 'gender', 'identity', NULL, 'varchar', 'varchar', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 'short_drama_character', 'ai_short_drama_character', 'id', 'id', 'identity', NULL, 'bigint', 'bigint', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 'short_drama_character', 'ai_short_drama_character', 'introduction', 'introduction', 'cast_text', NULL, '', 'text', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 'short_drama_character', 'ai_short_drama_character', 'name', 'name', 'identity', NULL, 'varchar', 'varchar', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 'short_drama_character', 'ai_short_drama_character', 'personality_tags', 'personality_tags', 'identity', NULL, 'varchar', 'varchar', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 'short_drama_character', 'ai_short_drama_character', 'project_id', 'project_id', 'identity', NULL, 'bigint', 'bigint', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 'short_drama_character', 'ai_short_drama_character', 'reference_image_url', 'reference_image_url', 'cast_text', NULL, '', 'text', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 'short_drama_character', 'ai_short_drama_character', 'role_level', 'role_level', 'identity', NULL, 'varchar', 'varchar', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 'short_drama_character', 'ai_short_drama_character', 'tenant_id', 'tenant_id', 'cast_text', NULL, 'bigint', 'varchar', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 'short_drama_character', 'ai_short_drama_character', 'update_by', 'update_by', 'identity', NULL, 'bigint null', 'bigint', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 'short_drama_character', 'ai_short_drama_character', 'update_time', 'update_time', 'identity', NULL, 'datetime null', 'timestamp', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 'short_drama_character', 'ai_short_drama_character', 'visual_description', 'visual_description', 'cast_text', NULL, '', 'text', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 'short_drama_character_appearance', 'ai_short_drama_character_appearance', 'appearance_index', 'appearance_index', 'identity', NULL, 'int', 'integer', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 'short_drama_character_appearance', 'ai_short_drama_character_appearance', 'change_reason', 'change_reason', 'identity', NULL, 'varchar', 'varchar', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 'short_drama_character_appearance', 'ai_short_drama_character_appearance', 'character_id', 'character_id', 'identity', NULL, 'bigint', 'bigint', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 'short_drama_character_appearance', 'ai_short_drama_character_appearance', 'create_by', 'create_by', 'identity', NULL, 'bigint null', 'bigint', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 'short_drama_character_appearance', 'ai_short_drama_character_appearance', 'create_dept', 'create_dept', 'identity', NULL, 'bigint null', 'bigint', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 'short_drama_character_appearance', 'ai_short_drama_character_appearance', 'create_time', 'create_time', 'identity', NULL, 'datetime null', 'timestamp', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 'short_drama_character_appearance', 'ai_short_drama_character_appearance', 'description', 'description', 'cast_text', NULL, '', 'text', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 'short_drama_character_appearance', 'ai_short_drama_character_appearance', 'id', 'id', 'identity', NULL, 'bigint', 'bigint', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 'short_drama_character_appearance', 'ai_short_drama_character_appearance', 'image_descriptions', 'image_descriptions', 'cast_text', NULL, '', 'text', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 'short_drama_character_appearance', 'ai_short_drama_character_appearance', 'image_urls', 'image_urls', 'cast_text', NULL, '', 'text', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 'short_drama_character_appearance', 'ai_short_drama_character_appearance', 'previous_descriptions', 'previous_descriptions', 'cast_text', NULL, '', 'text', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 'short_drama_character_appearance', 'ai_short_drama_character_appearance', 'previous_image_urls', 'previous_image_urls', 'cast_text', NULL, '', 'text', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 'short_drama_character_appearance', 'ai_short_drama_character_appearance', 'reference_image_url', 'reference_image_url', 'cast_text', NULL, '', 'text', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 'short_drama_character_appearance', 'ai_short_drama_character_appearance', 'selected_image_index', 'selected_image_index', 'identity', NULL, 'int null', 'integer', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 'short_drama_character_appearance', 'ai_short_drama_character_appearance', 'tenant_id', 'tenant_id', 'cast_text', NULL, 'bigint', 'varchar', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 'short_drama_character_appearance', 'ai_short_drama_character_appearance', 'update_by', 'update_by', 'identity', NULL, 'bigint null', 'bigint', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 'short_drama_character_appearance', 'ai_short_drama_character_appearance', 'update_time', 'update_time', 'identity', NULL, 'datetime null', 'timestamp', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 'short_drama_character_appearance', 'ai_short_drama_character_appearance', 'voice', 'voice', 'identity', NULL, 'varchar', 'varchar', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 'short_drama_location', 'ai_short_drama_location', 'available_slots', 'available_slots', 'cast_text', NULL, '', 'text', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 'short_drama_location', 'ai_short_drama_location', 'create_by', 'create_by', 'identity', NULL, 'bigint null', 'bigint', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 'short_drama_location', 'ai_short_drama_location', 'create_dept', 'create_dept', 'identity', NULL, 'bigint null', 'bigint', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 'short_drama_location', 'ai_short_drama_location', 'create_time', 'create_time', 'identity', NULL, 'datetime null', 'timestamp', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 'short_drama_location', 'ai_short_drama_location', 'crowd_description', 'crowd_description', 'identity', NULL, 'varchar', 'varchar', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 'short_drama_location', 'ai_short_drama_location', 'descriptions', 'descriptions', 'cast_text', NULL, '', 'text', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 'short_drama_location', 'ai_short_drama_location', 'has_crowd', 'has_crowd', 'identity', NULL, 'tinyint', 'smallint', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 'short_drama_location', 'ai_short_drama_location', 'id', 'id', 'identity', NULL, 'bigint', 'bigint', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 'short_drama_location', 'ai_short_drama_location', 'image_descriptions', 'image_descriptions', 'cast_text', NULL, '', 'text', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 'short_drama_location', 'ai_short_drama_location', 'image_urls', 'image_urls', 'cast_text', NULL, '', 'text', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 'short_drama_location', 'ai_short_drama_location', 'name', 'name', 'identity', NULL, 'varchar', 'varchar', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 'short_drama_location', 'ai_short_drama_location', 'previous_descriptions', 'previous_descriptions', 'cast_text', NULL, '', 'text', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 'short_drama_location', 'ai_short_drama_location', 'previous_image_urls', 'previous_image_urls', 'cast_text', NULL, '', 'text', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 'short_drama_location', 'ai_short_drama_location', 'project_id', 'project_id', 'identity', NULL, 'bigint', 'bigint', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 'short_drama_location', 'ai_short_drama_location', 'reference_image_url', 'reference_image_url', 'cast_text', NULL, '', 'text', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 'short_drama_location', 'ai_short_drama_location', 'selected_image_index', 'selected_image_index', 'identity', NULL, 'int null', 'integer', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 'short_drama_location', 'ai_short_drama_location', 'summary', 'summary', 'identity', NULL, 'varchar', 'varchar', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 'short_drama_location', 'ai_short_drama_location', 'tenant_id', 'tenant_id', 'cast_text', NULL, 'bigint', 'varchar', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 'short_drama_location', 'ai_short_drama_location', 'update_by', 'update_by', 'identity', NULL, 'bigint null', 'bigint', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 'short_drama_location', 'ai_short_drama_location', 'update_time', 'update_time', 'identity', NULL, 'datetime null', 'timestamp', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 'short_drama_project', 'ai_short_drama_project', 'art_style', 'art_style', 'identity', NULL, 'varchar', 'varchar', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 'short_drama_project', 'ai_short_drama_project', 'compose_aspect_ratio', 'compose_aspect_ratio', 'identity', NULL, 'varchar', 'varchar', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 'short_drama_project', 'ai_short_drama_project', 'compose_error_message', 'compose_error_message', 'identity', NULL, 'varchar', 'varchar', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 'short_drama_project', 'ai_short_drama_project', 'compose_job_id', 'compose_job_id', 'identity', NULL, 'varchar', 'varchar', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 'short_drama_project', 'ai_short_drama_project', 'compose_progress', 'compose_progress', 'identity', NULL, 'int', 'integer', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 'short_drama_project', 'ai_short_drama_project', 'compose_status', 'compose_status', 'identity', NULL, 'varchar', 'varchar', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 'short_drama_project', 'ai_short_drama_project', 'compose_transition_duration_seconds', 'compose_transition_duration_seconds', 'identity', NULL, 'decimal', 'numeric', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 'short_drama_project', 'ai_short_drama_project', 'compose_transition_type', 'compose_transition_type', 'identity', NULL, 'varchar', 'varchar', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 'short_drama_project', 'ai_short_drama_project', 'composed_at', 'composed_at', 'identity', NULL, 'datetime null', 'timestamp', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 'short_drama_project', 'ai_short_drama_project', 'composed_video_duration_seconds', 'composed_video_duration_seconds', 'identity', NULL, 'decimal', 'numeric', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 'short_drama_project', 'ai_short_drama_project', 'composed_video_oss_id', 'composed_video_oss_id', 'identity', NULL, 'bigint null', 'bigint', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 'short_drama_project', 'ai_short_drama_project', 'create_by', 'create_by', 'identity', NULL, 'bigint null', 'bigint', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 'short_drama_project', 'ai_short_drama_project', 'create_dept', 'create_dept', 'identity', NULL, 'bigint null', 'bigint', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 'short_drama_project', 'ai_short_drama_project', 'create_time', 'create_time', 'identity', NULL, 'datetime null', 'timestamp', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 'short_drama_project', 'ai_short_drama_project', 'description', 'description', 'cast_text', NULL, '', 'text', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 'short_drama_project', 'ai_short_drama_project', 'id', 'id', 'identity', NULL, 'bigint', 'bigint', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 'short_drama_project', 'ai_short_drama_project', 'project_name', 'project_name', 'identity', NULL, 'varchar', 'varchar', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 'short_drama_project', 'ai_short_drama_project', 'status', 'status', 'identity', NULL, 'varchar', 'varchar', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 'short_drama_project', 'ai_short_drama_project', 'tenant_id', 'tenant_id', 'cast_text', NULL, 'bigint', 'varchar', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 'short_drama_project', 'ai_short_drama_project', 'update_by', 'update_by', 'identity', NULL, 'bigint null', 'bigint', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 'short_drama_project', 'ai_short_drama_project', 'update_time', 'update_time', 'identity', NULL, 'datetime null', 'timestamp', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 'short_drama_project', 'ai_short_drama_project', 'user_id', 'user_id', 'identity', NULL, 'bigint', 'bigint', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 'short_drama_script', 'ai_short_drama_script', 'create_by', 'create_by', 'identity', NULL, 'bigint null', 'bigint', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 'short_drama_script', 'ai_short_drama_script', 'create_dept', 'create_dept', 'identity', NULL, 'bigint null', 'bigint', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 'short_drama_script', 'ai_short_drama_script', 'create_time', 'create_time', 'identity', NULL, 'datetime null', 'timestamp', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 'short_drama_script', 'ai_short_drama_script', 'id', 'id', 'identity', NULL, 'bigint', 'bigint', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 'short_drama_script', 'ai_short_drama_script', 'outline_text', 'outline_text', 'cast_text', NULL, '', 'text', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 'short_drama_script', 'ai_short_drama_script', 'project_id', 'project_id', 'identity', NULL, 'bigint', 'bigint', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 'short_drama_script', 'ai_short_drama_script', 'script_name', 'script_name', 'identity', NULL, 'varchar', 'varchar', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 'short_drama_script', 'ai_short_drama_script', 'script_text', 'script_text', 'cast_text', NULL, '', 'text', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 'short_drama_script', 'ai_short_drama_script', 'source_type', 'source_type', 'identity', NULL, 'varchar', 'varchar', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 'short_drama_script', 'ai_short_drama_script', 'tenant_id', 'tenant_id', 'cast_text', NULL, 'bigint', 'varchar', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 'short_drama_script', 'ai_short_drama_script', 'tone', 'tone', 'identity', NULL, 'varchar', 'varchar', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 'short_drama_script', 'ai_short_drama_script', 'update_by', 'update_by', 'identity', NULL, 'bigint null', 'bigint', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 'short_drama_script', 'ai_short_drama_script', 'update_time', 'update_time', 'identity', NULL, 'datetime null', 'timestamp', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 'short_drama_storyboard', 'ai_short_drama_storyboard', 'acting_notes', 'acting_notes', 'cast_text', NULL, '', 'text', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 'short_drama_storyboard', 'ai_short_drama_storyboard', 'camera_move', 'camera_move', 'identity', NULL, 'varchar', 'varchar', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 'short_drama_storyboard', 'ai_short_drama_storyboard', 'characters_json', 'characters_json', 'cast_text', NULL, '', 'text', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 'short_drama_storyboard', 'ai_short_drama_storyboard', 'continuity_json', 'continuity_json', 'cast_text', NULL, '', 'text', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 'short_drama_storyboard', 'ai_short_drama_storyboard', 'create_by', 'create_by', 'identity', NULL, 'bigint null', 'bigint', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 'short_drama_storyboard', 'ai_short_drama_storyboard', 'create_dept', 'create_dept', 'identity', NULL, 'bigint null', 'bigint', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 'short_drama_storyboard', 'ai_short_drama_storyboard', 'create_time', 'create_time', 'identity', NULL, 'datetime null', 'timestamp', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 'short_drama_storyboard', 'ai_short_drama_storyboard', 'duration_seconds', 'duration_seconds', 'identity', NULL, 'int', 'integer', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 'short_drama_storyboard', 'ai_short_drama_storyboard', 'id', 'id', 'identity', NULL, 'bigint', 'bigint', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 'short_drama_storyboard', 'ai_short_drama_storyboard', 'image_prompt', 'image_prompt', 'cast_text', NULL, '', 'text', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 'short_drama_storyboard', 'ai_short_drama_storyboard', 'last_frame_url', 'last_frame_url', 'cast_text', NULL, '', 'text', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 'short_drama_storyboard', 'ai_short_drama_storyboard', 'location_name', 'location_name', 'identity', NULL, 'varchar', 'varchar', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 'short_drama_storyboard', 'ai_short_drama_storyboard', 'photography_rules', 'photography_rules', 'cast_text', NULL, '', 'text', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 'short_drama_storyboard', 'ai_short_drama_storyboard', 'project_id', 'project_id', 'identity', NULL, 'bigint', 'bigint', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 'short_drama_storyboard', 'ai_short_drama_storyboard', 'scene_no', 'scene_no', 'identity', NULL, 'int', 'integer', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 'short_drama_storyboard', 'ai_short_drama_storyboard', 'scene_text', 'scene_text', 'cast_text', NULL, '', 'text', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 'short_drama_storyboard', 'ai_short_drama_storyboard', 'scene_title', 'scene_title', 'identity', NULL, 'varchar', 'varchar', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 'short_drama_storyboard', 'ai_short_drama_storyboard', 'scene_type', 'scene_type', 'identity', NULL, 'varchar', 'varchar', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 'short_drama_storyboard', 'ai_short_drama_storyboard', 'script_id', 'script_id', 'identity', NULL, 'bigint', 'bigint', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 'short_drama_storyboard', 'ai_short_drama_storyboard', 'shot_type', 'shot_type', 'identity', NULL, 'varchar', 'varchar', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 'short_drama_storyboard', 'ai_short_drama_storyboard', 'source_text', 'source_text', 'cast_text', NULL, '', 'text', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 'short_drama_storyboard', 'ai_short_drama_storyboard', 'tenant_id', 'tenant_id', 'cast_text', NULL, 'bigint', 'varchar', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 'short_drama_storyboard', 'ai_short_drama_storyboard', 'update_by', 'update_by', 'identity', NULL, 'bigint null', 'bigint', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 'short_drama_storyboard', 'ai_short_drama_storyboard', 'update_time', 'update_time', 'identity', NULL, 'datetime null', 'timestamp', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 'short_drama_storyboard', 'ai_short_drama_storyboard', 'video_id', 'video_id', 'identity', NULL, 'varchar', 'varchar', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 'short_drama_storyboard', 'ai_short_drama_storyboard', 'video_prompt', 'video_prompt', 'cast_text', NULL, '', 'text', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 'short_drama_storyboard', 'ai_short_drama_storyboard', 'video_status', 'video_status', 'identity', NULL, 'varchar', 'varchar', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 'short_drama_storyboard', 'ai_short_drama_storyboard', 'video_url', 'video_url', 'cast_text', NULL, '', 'text', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 't_workflow', 'ai_flow_workflow', 'create_time', 'create_time', 'identity', NULL, 'datetime', 'timestamp', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 't_workflow', 'ai_flow_workflow', 'id', 'id', 'identity', NULL, 'bigint', 'bigint', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 't_workflow', 'ai_flow_workflow', 'is_deleted', 'is_deleted', 'identity', NULL, 'tinyint', 'smallint', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 't_workflow', 'ai_flow_workflow', 'is_enable', 'is_enable', 'identity', NULL, 'tinyint', 'smallint', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 't_workflow', 'ai_flow_workflow', 'is_public', 'is_public', 'identity', NULL, 'tinyint', 'smallint', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 't_workflow', 'ai_flow_workflow', 'remark', 'remark', 'cast_text', NULL, '', 'text', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 't_workflow', 'ai_flow_workflow', 'tenant_id', 'tenant_id', 'identity', NULL, 'varchar', 'varchar', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 't_workflow', 'ai_flow_workflow', 'title', 'title', 'identity', NULL, 'varchar', 'varchar', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 't_workflow', 'ai_flow_workflow', 'update_time', 'update_time', 'identity', NULL, 'datetime', 'timestamp', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 't_workflow', 'ai_flow_workflow', 'user_id', 'user_id', 'identity', NULL, 'bigint', 'bigint', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 't_workflow', 'ai_flow_workflow', 'uuid', 'uuid', 'identity', NULL, 'varchar', 'varchar', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 't_workflow_component', 'ai_flow_component', 'create_time', 'create_time', 'identity', NULL, 'datetime', 'timestamp', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 't_workflow_component', 'ai_flow_component', 'display_order', 'display_order', 'identity', NULL, 'int', 'integer', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 't_workflow_component', 'ai_flow_component', 'id', 'id', 'identity', NULL, 'bigint', 'bigint', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 't_workflow_component', 'ai_flow_component', 'is_deleted', 'is_deleted', 'identity', NULL, 'tinyint', 'smallint', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 't_workflow_component', 'ai_flow_component', 'is_enable', 'is_enable', 'identity', NULL, 'tinyint', 'smallint', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 't_workflow_component', 'ai_flow_component', 'name', 'name', 'identity', NULL, 'varchar', 'varchar', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 't_workflow_component', 'ai_flow_component', 'remark', 'remark', 'cast_text', NULL, '', 'text', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 't_workflow_component', 'ai_flow_component', 'tenant_id', 'tenant_id', 'identity', NULL, 'varchar', 'varchar', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 't_workflow_component', 'ai_flow_component', 'title', 'title', 'identity', NULL, 'varchar', 'varchar', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 't_workflow_component', 'ai_flow_component', 'update_time', 'update_time', 'identity', NULL, 'datetime', 'timestamp', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 't_workflow_component', 'ai_flow_component', 'uuid', 'uuid', 'identity', NULL, 'varchar', 'varchar', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 't_workflow_edge', 'ai_flow_edge', 'create_time', 'create_time', 'identity', NULL, 'datetime', 'timestamp', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 't_workflow_edge', 'ai_flow_edge', 'id', 'id', 'identity', NULL, 'bigint', 'bigint', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 't_workflow_edge', 'ai_flow_edge', 'is_deleted', 'is_deleted', 'identity', NULL, 'tinyint', 'smallint', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 't_workflow_edge', 'ai_flow_edge', 'source_handle', 'source_handle', 'identity', NULL, 'varchar', 'varchar', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 't_workflow_edge', 'ai_flow_edge', 'source_node_uuid', 'source_node_uuid', 'identity', NULL, 'varchar', 'varchar', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 't_workflow_edge', 'ai_flow_edge', 'target_node_uuid', 'target_node_uuid', 'identity', NULL, 'varchar', 'varchar', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 't_workflow_edge', 'ai_flow_edge', 'tenant_id', 'tenant_id', 'identity', NULL, 'varchar', 'varchar', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 't_workflow_edge', 'ai_flow_edge', 'update_time', 'update_time', 'identity', NULL, 'datetime', 'timestamp', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 't_workflow_edge', 'ai_flow_edge', 'uuid', 'uuid', 'identity', NULL, 'varchar', 'varchar', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 't_workflow_edge', 'ai_flow_edge', 'workflow_id', 'workflow_id', 'identity', NULL, 'bigint', 'bigint', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 't_workflow_node', 'ai_flow_node', 'create_time', 'create_time', 'identity', NULL, 'datetime', 'timestamp', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 't_workflow_node', 'ai_flow_node', 'id', 'id', 'identity', NULL, 'bigint', 'bigint', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 't_workflow_node', 'ai_flow_node', 'input_config', 'input_config', 'identity', NULL, 'json', 'jsonb', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 't_workflow_node', 'ai_flow_node', 'is_deleted', 'is_deleted', 'identity', NULL, 'tinyint', 'smallint', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 't_workflow_node', 'ai_flow_node', 'node_config', 'node_config', 'identity', NULL, '', 'jsonb', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 't_workflow_node', 'ai_flow_node', 'position_x', 'position_x', 'identity', NULL, 'double', 'double precision', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 't_workflow_node', 'ai_flow_node', 'position_y', 'position_y', 'identity', NULL, 'double', 'double precision', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 't_workflow_node', 'ai_flow_node', 'remark', 'remark', 'identity', NULL, 'varchar', 'varchar', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 't_workflow_node', 'ai_flow_node', 'tenant_id', 'tenant_id', 'identity', NULL, 'varchar', 'varchar', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 't_workflow_node', 'ai_flow_node', 'title', 'title', 'identity', NULL, 'varchar', 'varchar', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 't_workflow_node', 'ai_flow_node', 'update_time', 'update_time', 'identity', NULL, 'datetime', 'timestamp', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 't_workflow_node', 'ai_flow_node', 'user_id', 'user_id', 'identity', NULL, 'bigint', 'bigint', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 't_workflow_node', 'ai_flow_node', 'uuid', 'uuid', 'identity', NULL, 'varchar', 'varchar', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 't_workflow_node', 'ai_flow_node', 'workflow_component_id', 'workflow_component_id', 'identity', NULL, 'bigint', 'bigint', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 't_workflow_node', 'ai_flow_node', 'workflow_id', 'workflow_id', 'identity', NULL, 'bigint', 'bigint', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 't_workflow_runtime', 'ai_flow_runtime', 'create_time', 'create_time', 'identity', NULL, 'datetime', 'timestamp', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 't_workflow_runtime', 'ai_flow_runtime', 'id', 'id', 'identity', NULL, 'bigint', 'bigint', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 't_workflow_runtime', 'ai_flow_runtime', 'input', 'input', 'identity', NULL, '', 'jsonb', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 't_workflow_runtime', 'ai_flow_runtime', 'is_deleted', 'is_deleted', 'identity', NULL, 'tinyint', 'smallint', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 't_workflow_runtime', 'ai_flow_runtime', 'output', 'output', 'identity', NULL, '', 'jsonb', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 't_workflow_runtime', 'ai_flow_runtime', 'status', 'status', 'identity', NULL, 'smallint', 'smallint', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 't_workflow_runtime', 'ai_flow_runtime', 'status_remark', 'status_remark', 'identity', NULL, 'varchar', 'varchar', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 't_workflow_runtime', 'ai_flow_runtime', 'tenant_id', 'tenant_id', 'identity', NULL, 'varchar', 'varchar', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 't_workflow_runtime', 'ai_flow_runtime', 'update_time', 'update_time', 'identity', NULL, 'datetime', 'timestamp', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 't_workflow_runtime', 'ai_flow_runtime', 'user_id', 'user_id', 'identity', NULL, 'bigint', 'bigint', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 't_workflow_runtime', 'ai_flow_runtime', 'uuid', 'uuid', 'identity', NULL, 'varchar', 'varchar', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 't_workflow_runtime', 'ai_flow_runtime', 'workflow_id', 'workflow_id', 'identity', NULL, 'bigint', 'bigint', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 't_workflow_runtime_node', 'ai_flow_runtime_node', 'create_time', 'create_time', 'identity', NULL, 'datetime', 'timestamp', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 't_workflow_runtime_node', 'ai_flow_runtime_node', 'id', 'id', 'identity', NULL, 'bigint', 'bigint', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 't_workflow_runtime_node', 'ai_flow_runtime_node', 'input', 'input', 'identity', NULL, '', 'jsonb', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 't_workflow_runtime_node', 'ai_flow_runtime_node', 'is_deleted', 'is_deleted', 'identity', NULL, 'tinyint', 'smallint', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 't_workflow_runtime_node', 'ai_flow_runtime_node', 'node_id', 'node_id', 'identity', NULL, 'bigint', 'bigint', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 't_workflow_runtime_node', 'ai_flow_runtime_node', 'output', 'output', 'identity', NULL, '', 'jsonb', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 't_workflow_runtime_node', 'ai_flow_runtime_node', 'status', 'status', 'identity', NULL, 'smallint', 'smallint', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 't_workflow_runtime_node', 'ai_flow_runtime_node', 'status_remark', 'status_remark', 'identity', NULL, 'varchar', 'varchar', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 't_workflow_runtime_node', 'ai_flow_runtime_node', 'tenant_id', 'tenant_id', 'identity', NULL, 'varchar', 'varchar', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 't_workflow_runtime_node', 'ai_flow_runtime_node', 'update_time', 'update_time', 'identity', NULL, 'datetime', 'timestamp', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 't_workflow_runtime_node', 'ai_flow_runtime_node', 'user_id', 'user_id', 'identity', NULL, 'bigint', 'bigint', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 't_workflow_runtime_node', 'ai_flow_runtime_node', 'uuid', 'uuid', 'identity', NULL, 'varchar', 'varchar', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 't_workflow_runtime_node', 'ai_flow_runtime_node', 'workflow_runtime_id', 'workflow_runtime_id', 'identity', NULL, 'bigint', 'bigint', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 'trace_node', 'ai_flow_trace_node', 'class_name', 'class_name', 'identity', NULL, 'varchar', 'varchar', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 'trace_node', 'ai_flow_trace_node', 'create_by', 'create_by', 'identity', NULL, 'bigint', 'bigint', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 'trace_node', 'ai_flow_trace_node', 'create_dept', 'create_dept', 'identity', NULL, 'bigint', 'bigint', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 'trace_node', 'ai_flow_trace_node', 'create_time', 'create_time', 'identity', NULL, 'datetime', 'timestamp', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 'trace_node', 'ai_flow_trace_node', 'del_flag', 'del_flag', 'identity', NULL, 'char', 'char', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 'trace_node', 'ai_flow_trace_node', 'depth', 'depth', 'identity', NULL, 'int', 'integer', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 'trace_node', 'ai_flow_trace_node', 'duration_ms', 'duration_ms', 'identity', NULL, 'bigint', 'bigint', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 'trace_node', 'ai_flow_trace_node', 'end_time', 'end_time', 'identity', NULL, 'datetime', 'timestamp', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 'trace_node', 'ai_flow_trace_node', 'error_message', 'error_message', 'identity', NULL, 'varchar', 'varchar', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 'trace_node', 'ai_flow_trace_node', 'id', 'id', 'identity', NULL, 'bigint', 'bigint', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 'trace_node', 'ai_flow_trace_node', 'input_payload', 'input_payload', 'identity', NULL, 'text', 'text', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 'trace_node', 'ai_flow_trace_node', 'metadata', 'metadata', 'identity', NULL, 'text', 'text', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 'trace_node', 'ai_flow_trace_node', 'method_name', 'method_name', 'identity', NULL, 'varchar', 'varchar', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 'trace_node', 'ai_flow_trace_node', 'node_id', 'node_id', 'identity', NULL, 'varchar', 'varchar', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 'trace_node', 'ai_flow_trace_node', 'node_name', 'node_name', 'identity', NULL, 'varchar', 'varchar', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 'trace_node', 'ai_flow_trace_node', 'node_type', 'node_type', 'identity', NULL, 'varchar', 'varchar', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 'trace_node', 'ai_flow_trace_node', 'output_payload', 'output_payload', 'identity', NULL, 'text', 'text', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 'trace_node', 'ai_flow_trace_node', 'parent_node_id', 'parent_node_id', 'identity', NULL, 'varchar', 'varchar', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 'trace_node', 'ai_flow_trace_node', 'sort_order', 'sort_order', 'identity', NULL, 'int', 'integer', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 'trace_node', 'ai_flow_trace_node', 'start_time', 'start_time', 'identity', NULL, 'datetime', 'timestamp', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 'trace_node', 'ai_flow_trace_node', 'status', 'status', 'identity', NULL, 'varchar', 'varchar', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 'trace_node', 'ai_flow_trace_node', 'tenant_id', 'tenant_id', 'identity', NULL, 'varchar', 'varchar', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 'trace_node', 'ai_flow_trace_node', 'trace_id', 'trace_id', 'identity', NULL, 'varchar', 'varchar', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 'trace_node', 'ai_flow_trace_node', 'update_by', 'update_by', 'identity', NULL, 'bigint', 'bigint', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 'trace_node', 'ai_flow_trace_node', 'update_time', 'update_time', 'identity', NULL, 'datetime', 'timestamp', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 'trace_run', 'ai_flow_trace_run', 'business_id', 'business_id', 'identity', NULL, 'varchar', 'varchar', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 'trace_run', 'ai_flow_trace_run', 'business_type', 'business_type', 'identity', NULL, 'varchar', 'varchar', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 'trace_run', 'ai_flow_trace_run', 'create_by', 'create_by', 'identity', NULL, 'bigint', 'bigint', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 'trace_run', 'ai_flow_trace_run', 'create_dept', 'create_dept', 'identity', NULL, 'bigint', 'bigint', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 'trace_run', 'ai_flow_trace_run', 'create_time', 'create_time', 'identity', NULL, 'datetime', 'timestamp', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 'trace_run', 'ai_flow_trace_run', 'del_flag', 'del_flag', 'identity', NULL, 'char', 'char', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 'trace_run', 'ai_flow_trace_run', 'duration_ms', 'duration_ms', 'identity', NULL, 'bigint', 'bigint', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 'trace_run', 'ai_flow_trace_run', 'end_time', 'end_time', 'identity', NULL, 'datetime', 'timestamp', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 'trace_run', 'ai_flow_trace_run', 'error_message', 'error_message', 'identity', NULL, 'varchar', 'varchar', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 'trace_run', 'ai_flow_trace_run', 'id', 'id', 'identity', NULL, 'bigint', 'bigint', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 'trace_run', 'ai_flow_trace_run', 'metadata', 'metadata', 'identity', NULL, 'text', 'text', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 'trace_run', 'ai_flow_trace_run', 'start_time', 'start_time', 'identity', NULL, 'datetime', 'timestamp', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 'trace_run', 'ai_flow_trace_run', 'status', 'status', 'identity', NULL, 'varchar', 'varchar', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 'trace_run', 'ai_flow_trace_run', 'tenant_id', 'tenant_id', 'identity', NULL, 'varchar', 'varchar', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 'trace_run', 'ai_flow_trace_run', 'trace_id', 'trace_id', 'identity', NULL, 'varchar', 'varchar', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 'trace_run', 'ai_flow_trace_run', 'trace_name', 'trace_name', 'identity', NULL, 'varchar', 'varchar', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 'trace_run', 'ai_flow_trace_run', 'update_by', 'update_by', 'identity', NULL, 'bigint', 'bigint', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 'trace_run', 'ai_flow_trace_run', 'update_time', 'update_time', 'identity', NULL, 'datetime', 'timestamp', NULL, false, NULL),
    ('mysql/ruoyi-ai.sql', 'trace_run', 'ai_flow_trace_run', 'user_id', 'user_id', 'identity', NULL, 'bigint', 'bigint', NULL, false, NULL);

-- ---------------------------------------------------------------------------
-- Driver. Everything table-specific comes from the registry above, so a table can be
-- unblocked (E5) by adding registry rows instead of editing this migration.
-- ---------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION platform.ai_legacy_domain_expr(
    p_transform text, p_legacy_column text, p_arg text, p_alias text)
RETURNS text
LANGUAGE sql
IMMUTABLE
AS $expr$
    SELECT CASE p_transform
        WHEN 'identity'      THEN format('%I.%I', p_alias, p_legacy_column)
        WHEN 'cast_text'     THEN format('%I.%I::text', p_alias, p_legacy_column)
        WHEN 'enum'          THEN format(
            '(SELECT e.target_value FROM platform.ai_legacy_domain_enum_map e'
            ' WHERE e.domain = %L AND e.source_value = %I.%I::text)',
            p_arg, p_alias, p_legacy_column)
        WHEN 'coalesce_text' THEN format('COALESCE(%I.%I::text, %L)', p_alias, p_legacy_column, '')
        WHEN 'constant'      THEN format('%L', p_arg)
        ELSE NULL
    END
$expr$;
COMMENT ON FUNCTION platform.ai_legacy_domain_expr(text, text, text, text) IS
    'E2 旧 MySQL AI 域行迁移：把注册表里的 transform 展开成 SQL 表达式（别名限定）';

CREATE OR REPLACE FUNCTION platform.ai_legacy_domain_audit(
    p_source text, p_legacy text, p_target text, p_mode text,
    p_read bigint, p_inserted bigint, p_skipped bigint, p_defaulted bigint,
    p_before bigint, p_present bigint, p_reason text)
RETURNS void
LANGUAGE sql
AS $audit$
    INSERT INTO platform.ai_legacy_domain_migration_audit
        (legacy_source, legacy_table, unified_table, mode, rows_read, rows_inserted,
         rows_skipped_existing, rows_defaulted, unified_rows_before, unified_rows,
         blocked_reason, recorded_at)
    VALUES (p_source, p_legacy, p_target, p_mode, p_read, p_inserted, p_skipped,
            p_defaulted, p_before, p_present, p_reason, CURRENT_TIMESTAMP)
    ON CONFLICT (legacy_source, legacy_table) DO UPDATE
       SET unified_table = EXCLUDED.unified_table,
           mode = EXCLUDED.mode,
           rows_read = EXCLUDED.rows_read,
           rows_inserted = EXCLUDED.rows_inserted,
           rows_skipped_existing = EXCLUDED.rows_skipped_existing,
           rows_defaulted = EXCLUDED.rows_defaulted,
           unified_rows_before = EXCLUDED.unified_rows_before,
           unified_rows = EXCLUDED.unified_rows,
           blocked_reason = EXCLUDED.blocked_reason,
           recorded_at = CURRENT_TIMESTAMP
$audit$;
COMMENT ON FUNCTION platform.ai_legacy_domain_audit(text, text, text, text, bigint, bigint,
    bigint, bigint, bigint, bigint, text) IS
    'E2 旧 MySQL AI 域行迁移：逐表对账写入（幂等 upsert）';

CREATE OR REPLACE FUNCTION platform.ai_legacy_domain_copy_table(
    p_source text, p_legacy text, p_staging text DEFAULT 'legacy_mysql')
RETURNS text
LANGUAGE plpgsql
AS $copy$
DECLARE
    v_target     text;
    v_mode       text;
    v_reason     text;
    v_keys       text[];
    v_cols       text;
    v_exprs      text;
    v_key_pred   text;
    v_null_pred  text;
    v_read       bigint := 0;
    v_inserted   bigint := 0;
    v_skipped    bigint := 0;
    v_existing   bigint := 0;
    v_defaulted  bigint := 0;
    v_before     bigint := 0;
    v_present    bigint := 0;
    v_missing    text;
    v_unmapped   text;
    v_wide       bigint;
    v_samples    text;
    v_enum       text;
    v_seq        text;
    r            record;
BEGIN
    SELECT m.unified_table, m.mode, m.blocked_reason, m.key_columns
      INTO v_target, v_mode, v_reason, v_keys
      FROM platform.ai_legacy_domain_migration_table_map m
     WHERE m.legacy_source = p_source AND m.legacy_table = p_legacy;
    IF v_target IS NULL THEN
        RAISE EXCEPTION 'no legacy-domain mapping registered for %.%', p_source, p_legacy;
    END IF;

    -- A deployment that never ran the MySQL platform AI domain has no staging schema.
    -- That is the normal fresh-install case: record it and move on.
    IF NOT EXISTS (SELECT 1 FROM information_schema.tables t
                    WHERE t.table_schema = p_staging AND t.table_name = p_legacy) THEN
        PERFORM platform.ai_legacy_domain_audit(p_source, p_legacy, v_target, 'absent',
            0, 0, 0, 0, NULL, NULL,
            format('staging table %s.%s not present', p_staging, p_legacy));
        RETURN 'absent';
    END IF;

    -- Guard 1: every legacy column the registry names must exist in the staging table.
    -- A column-count/name mismatch is refused, never resolved by position.
    SELECT string_agg(m.legacy_column, ', ' ORDER BY m.legacy_column) INTO v_missing
      FROM platform.ai_legacy_domain_migration_map m
     WHERE m.legacy_source = p_source AND m.legacy_table = p_legacy
       AND m.legacy_column IS NOT NULL
       AND NOT EXISTS (SELECT 1 FROM information_schema.columns c
                        WHERE c.table_schema = p_staging AND c.table_name = p_legacy
                          AND c.column_name = m.legacy_column);
    IF v_missing IS NOT NULL THEN
        RAISE EXCEPTION 'staging table %.% is missing mapped column(s): % (refusing to guess a mapping)',
            p_staging, p_legacy, v_missing;
    END IF;

    -- Guard 2: every unified column the registry names must exist in the target.
    SELECT string_agg(m.unified_column, ', ' ORDER BY m.unified_column) INTO v_missing
      FROM platform.ai_legacy_domain_migration_map m
     WHERE m.legacy_source = p_source AND m.legacy_table = p_legacy
       AND m.unified_column IS NOT NULL
       AND NOT EXISTS (SELECT 1 FROM information_schema.columns c
                        WHERE c.table_schema = 'platform' AND c.table_name = v_target
                          AND c.column_name = m.unified_column);
    IF v_missing IS NOT NULL THEN
        RAISE EXCEPTION 'unified table platform.% is missing mapped column(s): %',
            v_target, v_missing;
    END IF;

    -- Guard 3 (value level): every distinct legacy value of an enum-mapped column must be
    -- in the value map. Runs even when the table is blocked, so the mapping is validated
    -- against the real data now instead of when the copy is unblocked later.
    FOR r IN SELECT m.legacy_column, m.transform_arg
               FROM platform.ai_legacy_domain_migration_map m
              WHERE m.legacy_source = p_source AND m.legacy_table = p_legacy
                AND m.transform = 'enum'
              ORDER BY m.legacy_column
    LOOP
        EXECUTE format(
            'SELECT string_agg(DISTINCT COALESCE(src.%I::text, %L), %L) FROM %I.%I src'
            ' WHERE src.%I IS NULL OR NOT EXISTS (SELECT 1 FROM platform.ai_legacy_domain_enum_map e'
            '  WHERE e.domain = %L AND e.source_value = src.%I::text)',
            r.legacy_column, '<null>', ', ', p_staging, p_legacy, r.legacy_column,
            r.transform_arg, r.legacy_column)
          INTO v_enum;
        IF v_enum IS NOT NULL THEN
            RAISE EXCEPTION 'legacy value(s) [%] in %.%.% have no mapping in enum domain "%"; add them to platform.ai_legacy_domain_enum_map before copying',
                v_enum, p_staging, p_legacy, r.legacy_column, r.transform_arg;
        END IF;
    END LOOP;

    -- Guard 4: a NOT NULL unified column without a default and without a mapped source
    -- cannot be filled. That is a platform-side adaptation (E2 §5.1c / E5), so the table is
    -- recorded as blocked instead of being filled with an invented value.
    SELECT string_agg(c.column_name, ', ' ORDER BY c.column_name) INTO v_unmapped
      FROM information_schema.columns c
     WHERE c.table_schema = 'platform' AND c.table_name = v_target
       AND c.is_nullable = 'NO' AND c.column_default IS NULL
       AND NOT EXISTS (SELECT 1 FROM platform.ai_legacy_domain_migration_map m
                        WHERE m.legacy_source = p_source AND m.legacy_table = p_legacy
                          AND m.unified_column = c.column_name);
    IF v_unmapped IS NOT NULL THEN
        PERFORM platform.ai_legacy_domain_audit(p_source, p_legacy, v_target, 'blocked',
            0, 0, 0, 0, NULL, NULL,
            format('unified NOT NULL column(s) without a mapped legacy source: %s', v_unmapped));
        RETURN 'blocked';
    END IF;

    IF v_mode <> 'copy' THEN
        PERFORM platform.ai_legacy_domain_audit(p_source, p_legacy, v_target, 'blocked',
            0, 0, 0, 0, NULL, NULL, COALESCE(v_reason, 'declared blocked'));
        RETURN 'blocked';
    END IF;

    -- Guard 5: narrowing columns. PostgreSQL would raise "value too long" on the first
    -- offending row; report the count and samples up front so the operator sees the exact
    -- problem instead of a half-applied copy.
    FOR r IN SELECT m.legacy_column, m.unified_column, m.unified_length
               FROM platform.ai_legacy_domain_migration_map m
              WHERE m.legacy_source = p_source AND m.legacy_table = p_legacy
                AND m.narrowing AND m.unified_length IS NOT NULL
              ORDER BY m.unified_column
    LOOP
        EXECUTE format('SELECT count(*) FROM %I.%I src WHERE src.%I IS NOT NULL AND length(src.%I::text) > %s',
                       p_staging, p_legacy, r.legacy_column, r.legacy_column, r.unified_length)
          INTO v_wide;
        IF v_wide > 0 THEN
            EXECUTE format('SELECT string_agg(DISTINCT left(src.%I::text, 60), %L) FROM %I.%I src WHERE src.%I IS NOT NULL AND length(src.%I::text) > %s',
                           r.legacy_column, ' | ', p_staging, p_legacy, r.legacy_column,
                           r.legacy_column, r.unified_length)
              INTO v_samples;
            RAISE EXCEPTION '% row(s) in %.%.% exceed the unified width % of platform.% (%): %',
                v_wide, p_staging, p_legacy, r.legacy_column, r.unified_length, v_target,
                r.unified_column, v_samples;
        END IF;
    END LOOP;

    SELECT string_agg(format('%I', m.unified_column), ', ' ORDER BY m.unified_column),
           string_agg(platform.ai_legacy_domain_expr(m.transform, m.legacy_column,
                                                     m.transform_arg, 'src'),
                      ', ' ORDER BY m.unified_column)
      INTO v_cols, v_exprs
      FROM platform.ai_legacy_domain_migration_map m
     WHERE m.legacy_source = p_source AND m.legacy_table = p_legacy
       AND m.legacy_column IS NOT NULL;
    IF v_exprs IS NULL OR v_cols IS NULL THEN
        RAISE EXCEPTION 'no column mapping registered for %.%', p_source, p_legacy;
    END IF;

    -- Key predicate: the copy is re-runnable and never overwrites a row that is already
    -- there (the AI-side rows from V8 may legitimately share ids).
    SELECT string_agg(format('t.%I IS NOT DISTINCT FROM %s', m.unified_column,
                             platform.ai_legacy_domain_expr(m.transform, m.legacy_column,
                                                            m.transform_arg, 'src')),
                      ' AND ' ORDER BY m.unified_column)
      INTO v_key_pred
      FROM platform.ai_legacy_domain_migration_map m
     WHERE m.legacy_source = p_source AND m.legacy_table = p_legacy
       AND m.unified_column = ANY (v_keys);
    IF v_key_pred IS NULL THEN
        RAISE EXCEPTION 'registered key column(s) % are not mapped for %.%',
            array_to_string(v_keys, ','), p_source, p_legacy;
    END IF;

    EXECUTE format('SELECT count(*) FROM %I.%I', p_staging, p_legacy) INTO v_read;
    EXECUTE format('SELECT count(*) FROM platform.%I', v_target) INTO v_before;
    EXECUTE format('SELECT count(*) FROM %I.%I src WHERE EXISTS (SELECT 1 FROM platform.%I t WHERE %s)',
                   p_staging, p_legacy, v_target, v_key_pred) INTO v_existing;

    -- rows that take the target's own representation of "no value" (documented in the
    -- registry note); counted so the substitution is visible in the audit, not silent
    SELECT string_agg(format('src.%I IS NULL', m.legacy_column), ' OR ')
      INTO v_null_pred
      FROM platform.ai_legacy_domain_migration_map m
     WHERE m.legacy_source = p_source AND m.legacy_table = p_legacy
       AND m.transform = 'coalesce_text';
    IF v_null_pred IS NOT NULL THEN
        EXECUTE format('SELECT count(*) FROM %I.%I src WHERE %s', p_staging, p_legacy, v_null_pred)
          INTO v_defaulted;
    END IF;

    EXECUTE format(
        'INSERT INTO platform.%I (%s) SELECT %s FROM %I.%I src'
        ' WHERE NOT EXISTS (SELECT 1 FROM platform.%I t WHERE %s)'
        ' ON CONFLICT DO NOTHING',
        v_target, v_cols, v_exprs, p_staging, p_legacy, v_target, v_key_pred);
    GET DIAGNOSTICS v_inserted = ROW_COUNT;
    v_skipped := v_existing;
    -- ON CONFLICT DO NOTHING also swallows a collision on any *other* unique constraint, and
    -- a duplicate key inside the staging data. Either way a row silently disappears, so the
    -- accounting is checked rather than assumed.
    IF v_inserted <> v_read - v_existing THEN
        RAISE EXCEPTION 'copy of %.% inserted % row(s) but % were expected (% read, % already present by key); row(s) were dropped by another constraint or the staging data has duplicate keys',
            p_staging, p_legacy, v_inserted, v_read - v_existing, v_read, v_existing;
    END IF;
    EXECUTE format('SELECT count(*) FROM platform.%I', v_target) INTO v_present;

    -- Explicit ids were inserted into an identity column; move the sequence past them so a
    -- later application insert cannot collide with a migrated row.
    IF array_length(v_keys, 1) = 1 THEN
        v_seq := pg_get_serial_sequence('platform.' || v_target, v_keys[1]);
        IF v_seq IS NOT NULL THEN
            EXECUTE format('SELECT setval(%L, GREATEST((SELECT COALESCE(max(%I), 0) FROM platform.%I), 1), true)',
                           v_seq, v_keys[1], v_target);
        END IF;
    END IF;

    PERFORM platform.ai_legacy_domain_audit(p_source, p_legacy, v_target, 'copied',
        v_read, v_inserted, v_skipped, v_defaulted, v_before, v_present,
        CASE WHEN v_skipped > 0
             THEN format('%s row(s) already present by key and left untouched', v_skipped)
             ELSE NULL END);
    RETURN 'copied';
END
$copy$;
COMMENT ON FUNCTION platform.ai_legacy_domain_copy_table(text, text, text) IS
    'E2 旧 MySQL AI 域行迁移驱动器：按注册表复制；列不一致即拒绝，绝不隐式映射';

-- ---------------------------------------------------------------------------
-- 5. Run. Copy-mode tables are copied; blocked/absent tables are validated and recorded.
-- ---------------------------------------------------------------------------
DO $$
DECLARE
    t        record;
    v_result text;
    v_notes  text[] := ARRAY[]::text[];
BEGIN
    FOR t IN SELECT legacy_table
               FROM platform.ai_legacy_domain_migration_table_map
              WHERE legacy_source = 'mysql/ruoyi-ai.sql'
              ORDER BY legacy_table
    LOOP
        v_result := platform.ai_legacy_domain_copy_table('mysql/ruoyi-ai.sql', t.legacy_table);
        IF v_result <> 'copied' THEN
            v_notes := v_notes || (t.legacy_table || '=' || v_result);
        END IF;
    END LOOP;
    IF array_length(v_notes, 1) > 0 THEN
        RAISE NOTICE 'legacy MySQL AI domain: not copied: %', array_to_string(v_notes, ', ');
    END IF;
END $$;

-- ---------------------------------------------------------------------------
-- Reconciliation. A copy that cannot account for every source row fails the migration;
-- a blocked table is a recorded, reviewable state (not a silent loss).
-- ---------------------------------------------------------------------------
DO $$
DECLARE
    bad         record;
    v_copied    bigint;
    v_blocked   bigint;
    v_absent    bigint;
    v_unaudited text;
    v_list      text;
BEGIN
    SELECT string_agg(tm.legacy_table, ', ' ORDER BY tm.legacy_table) INTO v_unaudited
      FROM platform.ai_legacy_domain_migration_table_map tm
     WHERE NOT EXISTS (SELECT 1 FROM platform.ai_legacy_domain_migration_audit a
                        WHERE a.legacy_source = tm.legacy_source
                          AND a.legacy_table = tm.legacy_table);
    IF v_unaudited IS NOT NULL THEN
        RAISE EXCEPTION 'legacy-domain table(s) without an audit row: %', v_unaudited;
    END IF;

    FOR bad IN
        SELECT a.legacy_table, a.rows_read, a.rows_inserted, a.rows_skipped_existing,
               a.unified_rows_before, a.unified_rows
          FROM platform.ai_legacy_domain_migration_audit a
         WHERE a.mode = 'copied'
           AND (a.rows_read <> a.rows_inserted + a.rows_skipped_existing
                OR a.unified_rows <> a.unified_rows_before + a.rows_inserted)
    LOOP
        RAISE EXCEPTION 'row accounting failed for % (read %, inserted %, skipped %, before %, after %)',
            bad.legacy_table, bad.rows_read, bad.rows_inserted, bad.rows_skipped_existing,
            bad.unified_rows_before, bad.unified_rows;
    END LOOP;

    SELECT count(*) FILTER (WHERE mode = 'copied'),
           count(*) FILTER (WHERE mode = 'blocked'),
           count(*) FILTER (WHERE mode = 'absent'),
           string_agg(legacy_table, ', ' ORDER BY legacy_table) FILTER (WHERE mode = 'blocked')
      INTO v_copied, v_blocked, v_absent, v_list
      FROM platform.ai_legacy_domain_migration_audit a
     WHERE a.legacy_source = 'mysql/ruoyi-ai.sql';

    RAISE NOTICE 'legacy MySQL AI domain: % copied, % blocked, % absent',
        v_copied, v_blocked, v_absent;
    IF v_blocked > 0 THEN
        RAISE WARNING 'legacy MySQL AI-domain rows not copied (platform-side adaptation pending, see platform.ai_legacy_domain_migration_audit.blocked_reason): %',
            v_list;
    END IF;
END $$;
