-- ---------------------------------------------------------------------------
-- E2 unified AI domain (continued): PostgreSQL DDL for the AI-domain tables that
-- only ever shipped MySQL DDL, plus one table that had no DDL at all.
--
-- Generated by scripts/db/mysql-to-postgres.py from the legacy MySQL install script
-- (services/platform/docs/script/sql/ruoyi-ai.sql) and the E0 table map
-- (mydocs/platform-embedded/03-table-map.json); the ai_model_config block is
-- hand-written because no source SQL exists for it.
--
-- Conversion conventions (also documented in the generator header):
--   * MySQL inline COMMENT becomes COMMENT ON COLUMN
--   * AUTO_INCREMENT becomes GENERATED BY DEFAULT AS IDENTITY
--   * ON UPDATE CURRENT_TIMESTAMP is dropped: PostgreSQL has no column-level
--     equivalent and the application fills update_time in its meta object handler
--   * FULLTEXT indexes are dropped (no direct equivalent) and were reported at
--     generation time so the omission is deliberate
--   * UNSIGNED is dropped
--
-- NOT VERIFIED against a live PostgreSQL yet; see the E2 spec risk E2-R2.
-- ---------------------------------------------------------------------------

-- ===== chat_model -> ai_model =====
CREATE TABLE IF NOT EXISTS platform.ai_model (
    "id" bigint NOT NULL,
    "category" varchar(20) DEFAULT NULL,
    "model_name" varchar(50) DEFAULT NULL,
    "provider_code" varchar(20) DEFAULT NULL,
    "model_describe" varchar(255) DEFAULT NULL,
    "model_dimension" integer DEFAULT NULL,
    "model_show" char(1) DEFAULT NULL,
    "api_host" varchar(255) DEFAULT NULL,
    "api_key" varchar(255) DEFAULT NULL,
    "create_dept" bigint DEFAULT NULL,
    "create_by" bigint DEFAULT NULL,
    "create_time" timestamp DEFAULT NULL,
    "update_by" bigint DEFAULT NULL,
    "update_time" timestamp DEFAULT NULL,
    "remark" varchar(500) DEFAULT NULL,
    "tenant_id" bigint NOT NULL DEFAULT 0,
    PRIMARY KEY ("id")
);
COMMENT ON TABLE platform.ai_model IS '模型管理';
COMMENT ON COLUMN platform.ai_model."id" IS '主键';
COMMENT ON COLUMN platform.ai_model."category" IS '模型分类';
COMMENT ON COLUMN platform.ai_model."model_name" IS '模型名称';
COMMENT ON COLUMN platform.ai_model."provider_code" IS '模型供应商';
COMMENT ON COLUMN platform.ai_model."model_describe" IS '模型描述';
COMMENT ON COLUMN platform.ai_model."model_dimension" IS '模型维度';
COMMENT ON COLUMN platform.ai_model."model_show" IS '是否显示';
COMMENT ON COLUMN platform.ai_model."api_host" IS '请求地址';
COMMENT ON COLUMN platform.ai_model."api_key" IS '密钥';
COMMENT ON COLUMN platform.ai_model."create_dept" IS '创建部门';
COMMENT ON COLUMN platform.ai_model."create_by" IS '创建者';
COMMENT ON COLUMN platform.ai_model."create_time" IS '创建时间';
COMMENT ON COLUMN platform.ai_model."update_by" IS '更新者';
COMMENT ON COLUMN platform.ai_model."update_time" IS '更新时间';
COMMENT ON COLUMN platform.ai_model."remark" IS '备注';
COMMENT ON COLUMN platform.ai_model."tenant_id" IS '租户Id';

-- ===== chat_provider -> ai_model_provider =====
CREATE TABLE IF NOT EXISTS platform.ai_model_provider (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "provider_name" varchar(100) NOT NULL,
    "provider_code" varchar(50) NOT NULL,
    "provider_icon" varchar(1000) DEFAULT NULL,
    "provider_desc" varchar(500) DEFAULT NULL,
    "api_host" varchar(255) DEFAULT NULL,
    "status" char(1) DEFAULT '0',
    "sort_order" integer DEFAULT 0,
    "create_dept" bigint DEFAULT NULL,
    "create_time" timestamp DEFAULT NULL,
    "create_by" varchar(64) DEFAULT '',
    "update_by" varchar(64) DEFAULT '',
    "update_time" timestamp DEFAULT NULL,
    "remark" varchar(500) DEFAULT NULL,
    "version" integer DEFAULT NULL,
    "del_flag" char(1) DEFAULT '0',
    "update_ip" varchar(128) DEFAULT NULL,
    "tenant_id" bigint NOT NULL DEFAULT 0,
    PRIMARY KEY ("id"),
    CONSTRAINT unique_provider_code UNIQUE (provider_code, tenant_id, del_flag)
);
COMMENT ON TABLE platform.ai_model_provider IS '厂商管理表';
COMMENT ON COLUMN platform.ai_model_provider."id" IS '主键';
COMMENT ON COLUMN platform.ai_model_provider."provider_name" IS '厂商名称';
COMMENT ON COLUMN platform.ai_model_provider."provider_code" IS '厂商编码';
COMMENT ON COLUMN platform.ai_model_provider."provider_icon" IS '厂商图标';
COMMENT ON COLUMN platform.ai_model_provider."provider_desc" IS '厂商描述';
COMMENT ON COLUMN platform.ai_model_provider."api_host" IS 'API地址';
COMMENT ON COLUMN platform.ai_model_provider."status" IS '状态（0正常 1停用）';
COMMENT ON COLUMN platform.ai_model_provider."sort_order" IS '排序';
COMMENT ON COLUMN platform.ai_model_provider."create_dept" IS '创建部门';
COMMENT ON COLUMN platform.ai_model_provider."create_time" IS '创建时间';
COMMENT ON COLUMN platform.ai_model_provider."create_by" IS '创建者';
COMMENT ON COLUMN platform.ai_model_provider."update_by" IS '更新者';
COMMENT ON COLUMN platform.ai_model_provider."update_time" IS '更新时间';
COMMENT ON COLUMN platform.ai_model_provider."remark" IS '备注';
COMMENT ON COLUMN platform.ai_model_provider."version" IS '版本';
COMMENT ON COLUMN platform.ai_model_provider."del_flag" IS '删除标志';
COMMENT ON COLUMN platform.ai_model_provider."update_ip" IS '更新IP';
COMMENT ON COLUMN platform.ai_model_provider."tenant_id" IS '租户Id';
CREATE INDEX IF NOT EXISTS idx_status ON platform.ai_model_provider (status);

-- ===== chat_session -> ai_conversation =====
CREATE TABLE IF NOT EXISTS platform.ai_conversation (
    "id" bigint NOT NULL,
    "user_id" bigint DEFAULT NULL,
    "session_title" varchar(255) DEFAULT NULL,
    "session_content" text,
    "create_dept" varchar(255) DEFAULT NULL,
    "create_by" bigint DEFAULT NULL,
    "create_time" timestamp DEFAULT NULL,
    "update_by" bigint DEFAULT NULL,
    "update_time" timestamp DEFAULT NULL,
    "remark" varchar(500) DEFAULT NULL,
    "conversation_id" varchar(32) DEFAULT NULL,
    "tenant_id" bigint NOT NULL DEFAULT 0,
    PRIMARY KEY ("id")
);
COMMENT ON TABLE platform.ai_conversation IS '会话管理';
COMMENT ON COLUMN platform.ai_conversation."id" IS '主键';
COMMENT ON COLUMN platform.ai_conversation."user_id" IS '用户id';
COMMENT ON COLUMN platform.ai_conversation."session_title" IS '会话标题';
COMMENT ON COLUMN platform.ai_conversation."session_content" IS '会话内容';
COMMENT ON COLUMN platform.ai_conversation."create_dept" IS '部门';
COMMENT ON COLUMN platform.ai_conversation."create_by" IS '创建者';
COMMENT ON COLUMN platform.ai_conversation."create_time" IS '创建时间';
COMMENT ON COLUMN platform.ai_conversation."update_by" IS '更新者';
COMMENT ON COLUMN platform.ai_conversation."update_time" IS '更新时间';
COMMENT ON COLUMN platform.ai_conversation."remark" IS '备注';
COMMENT ON COLUMN platform.ai_conversation."conversation_id" IS '会话ID';
COMMENT ON COLUMN platform.ai_conversation."tenant_id" IS '租户Id';

-- ===== chat_message -> ai_message =====
CREATE TABLE IF NOT EXISTS platform.ai_message (
    "id" bigint NOT NULL,
    "session_id" bigint DEFAULT NULL,
    "user_id" bigint NOT NULL,
    "content" text,
    "role" varchar(255) DEFAULT NULL,
    "total_tokens" integer DEFAULT 0,
    "model_name" varchar(255) DEFAULT NULL,
    "create_dept" bigint DEFAULT NULL,
    "create_by" bigint DEFAULT NULL,
    "create_time" timestamp DEFAULT NULL,
    "update_by" bigint DEFAULT NULL,
    "update_time" timestamp DEFAULT NULL,
    "remark" varchar(500) DEFAULT NULL,
    "tenant_id" bigint NOT NULL DEFAULT 0,
    PRIMARY KEY ("id")
);
COMMENT ON TABLE platform.ai_message IS '聊天消息表';
COMMENT ON COLUMN platform.ai_message."id" IS '主键';
COMMENT ON COLUMN platform.ai_message."session_id" IS '会话id';
COMMENT ON COLUMN platform.ai_message."user_id" IS '用户id';
COMMENT ON COLUMN platform.ai_message."content" IS '消息内容';
COMMENT ON COLUMN platform.ai_message."role" IS '对话角色';
COMMENT ON COLUMN platform.ai_message."total_tokens" IS '累计 Tokens';
COMMENT ON COLUMN platform.ai_message."model_name" IS '模型名称';
COMMENT ON COLUMN platform.ai_message."create_dept" IS '创建部门';
COMMENT ON COLUMN platform.ai_message."create_by" IS '创建者';
COMMENT ON COLUMN platform.ai_message."create_time" IS '创建时间';
COMMENT ON COLUMN platform.ai_message."update_by" IS '更新者';
COMMENT ON COLUMN platform.ai_message."update_time" IS '更新时间';
COMMENT ON COLUMN platform.ai_message."remark" IS '备注';
COMMENT ON COLUMN platform.ai_message."tenant_id" IS '租户Id';

-- ===== agent_info -> ai_agent_profile =====
CREATE TABLE IF NOT EXISTS platform.ai_agent_profile (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "tenant_id" bigint NOT NULL DEFAULT 0,
    "agent_name" varchar(200) NOT NULL,
    "agent_describe" varchar(500) DEFAULT NULL,
    "agent_show" varchar(255) DEFAULT NULL,
    "model_id" bigint NOT NULL,
    "enable_thinking" char(1) DEFAULT '0',
    "system_prompt" text,
    "mcp_tool_ids" varchar(1024) DEFAULT NULL,
    "skill_names" varchar(1024) DEFAULT NULL,
    "knowledge_ids" varchar(1024) DEFAULT NULL,
    "status" char(1) DEFAULT '0',
    "remark" varchar(500) DEFAULT NULL,
    "create_dept" bigint DEFAULT NULL,
    "create_by" bigint DEFAULT NULL,
    "create_time" timestamp DEFAULT NULL,
    "update_by" bigint DEFAULT NULL,
    "update_time" timestamp DEFAULT NULL,
    PRIMARY KEY ("id")
);
COMMENT ON TABLE platform.ai_agent_profile IS '智能体信息表';
COMMENT ON COLUMN platform.ai_agent_profile."id" IS '智能体ID';
COMMENT ON COLUMN platform.ai_agent_profile."tenant_id" IS '租户ID';
COMMENT ON COLUMN platform.ai_agent_profile."agent_name" IS '智能体名称';
COMMENT ON COLUMN platform.ai_agent_profile."agent_describe" IS '智能体描述（下拉展示用）';
COMMENT ON COLUMN platform.ai_agent_profile."agent_show" IS '展示图标/头像URL';
COMMENT ON COLUMN platform.ai_agent_profile."model_id" IS '绑定的聊天模型ID（chat_model.id, category=chat）';
COMMENT ON COLUMN platform.ai_agent_profile."enable_thinking" IS '是否启用深度思考(ReAct多子Agent)：0 否 1 是';
COMMENT ON COLUMN platform.ai_agent_profile."system_prompt" IS '自定义系统提示词';
COMMENT ON COLUMN platform.ai_agent_profile."mcp_tool_ids" IS '关联MCP工具ID列表（JSON数组，[Long]）';
COMMENT ON COLUMN platform.ai_agent_profile."skill_names" IS '关联磁盘技能名列表（JSON数组，[String]）';
COMMENT ON COLUMN platform.ai_agent_profile."knowledge_ids" IS '关联知识库ID列表（JSON数组，[Long]）';
COMMENT ON COLUMN platform.ai_agent_profile."status" IS '状态：0 正常 1 停用';
COMMENT ON COLUMN platform.ai_agent_profile."remark" IS '备注';
COMMENT ON COLUMN platform.ai_agent_profile."create_dept" IS '创建部门';
COMMENT ON COLUMN platform.ai_agent_profile."create_by" IS '创建者';
COMMENT ON COLUMN platform.ai_agent_profile."create_time" IS '创建时间';
COMMENT ON COLUMN platform.ai_agent_profile."update_by" IS '更新者';
COMMENT ON COLUMN platform.ai_agent_profile."update_time" IS '更新时间';
CREATE INDEX IF NOT EXISTS idx_agent_tenant_id ON platform.ai_agent_profile (tenant_id);
CREATE INDEX IF NOT EXISTS idx_agent_model_id ON platform.ai_agent_profile (model_id);

-- ===== knowledge_info -> ai_knowledge_base =====
CREATE TABLE IF NOT EXISTS platform.ai_knowledge_base (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "user_id" bigint NOT NULL DEFAULT 0,
    "name" varchar(50) NOT NULL,
    "share" smallint DEFAULT NULL,
    "description" varchar(1000) DEFAULT NULL,
    "separator" varchar(255) DEFAULT NULL,
    "overlap_char" integer DEFAULT NULL,
    "retrieve_limit" integer DEFAULT NULL,
    "similarity_threshold" double precision DEFAULT 0.5,
    "text_block_size" integer DEFAULT NULL,
    "vector_model" varchar(50) DEFAULT NULL,
    "embedding_model" varchar(50) DEFAULT NULL,
    "create_dept" varchar(255) DEFAULT NULL,
    "create_by" varchar(50) DEFAULT NULL,
    "create_time" timestamp DEFAULT NULL,
    "update_by" bigint DEFAULT NULL,
    "update_time" timestamp DEFAULT NULL,
    "remark" varchar(500) DEFAULT NULL,
    "tenant_id" bigint NOT NULL DEFAULT 0,
    "enable_rerank" smallint DEFAULT 0,
    "rerank_score_threshold" double precision DEFAULT NULL,
    "rerank_top_n" integer DEFAULT NULL,
    "rerank_model" varchar(100) DEFAULT NULL,
    "enable_hybrid" smallint DEFAULT 0,
    "hybrid_alpha" double precision DEFAULT 0.5,
    "system_prompt" text,
    PRIMARY KEY ("id")
);
COMMENT ON TABLE platform.ai_knowledge_base IS '知识库';
COMMENT ON COLUMN platform.ai_knowledge_base."id" IS '主键';
COMMENT ON COLUMN platform.ai_knowledge_base."user_id" IS '用户ID';
COMMENT ON COLUMN platform.ai_knowledge_base."name" IS '知识库名称';
COMMENT ON COLUMN platform.ai_knowledge_base."share" IS '是否公开知识库（0 否 1是）';
COMMENT ON COLUMN platform.ai_knowledge_base."description" IS '知识库描述';
COMMENT ON COLUMN platform.ai_knowledge_base."separator" IS '知识分隔符';
COMMENT ON COLUMN platform.ai_knowledge_base."overlap_char" IS '重叠字符数';
COMMENT ON COLUMN platform.ai_knowledge_base."retrieve_limit" IS '知识库中检索的条数';
COMMENT ON COLUMN platform.ai_knowledge_base."similarity_threshold" IS '相似度阈值';
COMMENT ON COLUMN platform.ai_knowledge_base."text_block_size" IS '文本块大小';
COMMENT ON COLUMN platform.ai_knowledge_base."vector_model" IS '向量库';
COMMENT ON COLUMN platform.ai_knowledge_base."embedding_model" IS '向量模型';
COMMENT ON COLUMN platform.ai_knowledge_base."create_dept" IS '部门';
COMMENT ON COLUMN platform.ai_knowledge_base."create_by" IS '创建人';
COMMENT ON COLUMN platform.ai_knowledge_base."create_time" IS '创建时间';
COMMENT ON COLUMN platform.ai_knowledge_base."update_by" IS '更新者';
COMMENT ON COLUMN platform.ai_knowledge_base."update_time" IS '更新时间';
COMMENT ON COLUMN platform.ai_knowledge_base."remark" IS '备注';
COMMENT ON COLUMN platform.ai_knowledge_base."tenant_id" IS '租户Id';
COMMENT ON COLUMN platform.ai_knowledge_base."enable_rerank" IS '是否启用重排序（0否 1是）';
COMMENT ON COLUMN platform.ai_knowledge_base."rerank_score_threshold" IS '重排序相关性分数阈值';
COMMENT ON COLUMN platform.ai_knowledge_base."rerank_top_n" IS '重排序后返回的文档数量';
COMMENT ON COLUMN platform.ai_knowledge_base."rerank_model" IS '重排序模型名称';
COMMENT ON COLUMN platform.ai_knowledge_base."enable_hybrid" IS '是否启用混合检索';
COMMENT ON COLUMN platform.ai_knowledge_base."hybrid_alpha" IS '混合检索权重比例 (0.0=纯向量, 1.0=纯关键词)';
COMMENT ON COLUMN platform.ai_knowledge_base."system_prompt" IS '系统提示词';
CREATE INDEX IF NOT EXISTS idx_tenant_user ON platform.ai_knowledge_base (tenant_id, user_id);
CREATE INDEX IF NOT EXISTS idx_tenant_share ON platform.ai_knowledge_base (tenant_id, share);

-- ===== knowledge_attach -> ai_knowledge_document =====
CREATE TABLE IF NOT EXISTS platform.ai_knowledge_document (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "knowledge_id" bigint NOT NULL,
    "oss_id" bigint DEFAULT NULL,
    "doc_id" varchar(32) DEFAULT NULL,
    "file_hash" varchar(64) DEFAULT NULL,
    "name" varchar(500) DEFAULT NULL,
    "type" varchar(50) NOT NULL,
    "create_dept" varchar(255) DEFAULT NULL,
    "create_by" varchar(50) DEFAULT NULL,
    "create_time" timestamp DEFAULT NULL,
    "update_by" bigint DEFAULT NULL,
    "update_time" timestamp DEFAULT NULL,
    "remark" varchar(500) DEFAULT NULL,
    "tenant_id" bigint NOT NULL DEFAULT 0,
    "status" smallint DEFAULT 0,
    PRIMARY KEY ("id"),
    CONSTRAINT idx_kname UNIQUE (knowledge_id, name),
    CONSTRAINT uk_knowledge_file_hash UNIQUE (knowledge_id, file_hash)
);
COMMENT ON TABLE platform.ai_knowledge_document IS '知识库附件';
COMMENT ON COLUMN platform.ai_knowledge_document."id" IS '主键';
COMMENT ON COLUMN platform.ai_knowledge_document."knowledge_id" IS '知识库ID';
COMMENT ON COLUMN platform.ai_knowledge_document."oss_id" IS '对象存储ID';
COMMENT ON COLUMN platform.ai_knowledge_document."doc_id" IS '文档ID';
COMMENT ON COLUMN platform.ai_knowledge_document."file_hash" IS '文件SHA-256摘要';
COMMENT ON COLUMN platform.ai_knowledge_document."name" IS '附件名称';
COMMENT ON COLUMN platform.ai_knowledge_document."type" IS '附件类型';
COMMENT ON COLUMN platform.ai_knowledge_document."create_dept" IS '部门';
COMMENT ON COLUMN platform.ai_knowledge_document."create_by" IS '创建人';
COMMENT ON COLUMN platform.ai_knowledge_document."create_time" IS '创建时间';
COMMENT ON COLUMN platform.ai_knowledge_document."update_by" IS '更新者';
COMMENT ON COLUMN platform.ai_knowledge_document."update_time" IS '更新时间';
COMMENT ON COLUMN platform.ai_knowledge_document."remark" IS '备注';
COMMENT ON COLUMN platform.ai_knowledge_document."tenant_id" IS '租户Id';
COMMENT ON COLUMN platform.ai_knowledge_document."status" IS '解析状态: 0待解析, 1解析中, 2已解析, 3解析失败';

-- ===== knowledge_fragment -> ai_knowledge_chunk =====
CREATE TABLE IF NOT EXISTS platform.ai_knowledge_chunk (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "fid" varchar(32) NOT NULL,
    "idx" integer NOT NULL,
    "doc_id" varchar(32) DEFAULT NULL,
    "content" text NOT NULL,
    "create_dept" varchar(255) DEFAULT NULL,
    "create_by" varchar(50) DEFAULT NULL,
    "create_time" timestamp DEFAULT NULL,
    "update_by" bigint DEFAULT NULL,
    "update_time" timestamp DEFAULT NULL,
    "remark" varchar(500) DEFAULT NULL,
    "tenant_id" bigint NOT NULL DEFAULT 0,
    "knowledge_id" bigint DEFAULT NULL,
    PRIMARY KEY ("id"),
    CONSTRAINT uk_fid UNIQUE (fid)
);
COMMENT ON TABLE platform.ai_knowledge_chunk IS '知识片段';
COMMENT ON COLUMN platform.ai_knowledge_chunk."id" IS '主键';
COMMENT ON COLUMN platform.ai_knowledge_chunk."fid" IS '向量库片段ID';
COMMENT ON COLUMN platform.ai_knowledge_chunk."idx" IS '片段索引下标';
COMMENT ON COLUMN platform.ai_knowledge_chunk."doc_id" IS '文档ID';
COMMENT ON COLUMN platform.ai_knowledge_chunk."content" IS '文档内容';
COMMENT ON COLUMN platform.ai_knowledge_chunk."create_dept" IS '部门';
COMMENT ON COLUMN platform.ai_knowledge_chunk."create_by" IS '创建人';
COMMENT ON COLUMN platform.ai_knowledge_chunk."create_time" IS '创建时间';
COMMENT ON COLUMN platform.ai_knowledge_chunk."update_by" IS '更新者';
COMMENT ON COLUMN platform.ai_knowledge_chunk."update_time" IS '更新时间';
COMMENT ON COLUMN platform.ai_knowledge_chunk."remark" IS '备注';
COMMENT ON COLUMN platform.ai_knowledge_chunk."tenant_id" IS '租户Id';
COMMENT ON COLUMN platform.ai_knowledge_chunk."knowledge_id" IS '知识库ID';
CREATE INDEX IF NOT EXISTS idx_doc_id ON platform.ai_knowledge_chunk (doc_id);
CREATE INDEX IF NOT EXISTS idx_knowledge_id ON platform.ai_knowledge_chunk (knowledge_id);

-- ===== mcp_market_info -> ai_mcp_market =====
CREATE TABLE IF NOT EXISTS platform.ai_mcp_market (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "name" varchar(200) NOT NULL,
    "url" varchar(500) NOT NULL,
    "description" text,
    "auth_config" text,
    "status" varchar(20) DEFAULT 'ENABLED',
    "tenant_id" varchar(20) DEFAULT '000000',
    "create_dept" bigint DEFAULT NULL,
    "create_by" bigint DEFAULT NULL,
    "create_time" timestamp DEFAULT NULL,
    "update_by" bigint DEFAULT NULL,
    "update_time" timestamp DEFAULT NULL,
    "del_flag" char(1) DEFAULT '0',
    PRIMARY KEY ("id")
);
COMMENT ON TABLE platform.ai_mcp_market IS 'MCP市场表';
COMMENT ON COLUMN platform.ai_mcp_market."id" IS '市场ID';
COMMENT ON COLUMN platform.ai_mcp_market."name" IS '市场名称';
COMMENT ON COLUMN platform.ai_mcp_market."url" IS '市场URL';
COMMENT ON COLUMN platform.ai_mcp_market."description" IS '市场描述';
COMMENT ON COLUMN platform.ai_mcp_market."auth_config" IS '认证配置（JSON格式）';
COMMENT ON COLUMN platform.ai_mcp_market."status" IS '状态：ENABLED-启用, DISABLED-禁用';
COMMENT ON COLUMN platform.ai_mcp_market."tenant_id" IS '租户编号';
COMMENT ON COLUMN platform.ai_mcp_market."create_dept" IS '创建部门';
COMMENT ON COLUMN platform.ai_mcp_market."create_by" IS '创建者';
COMMENT ON COLUMN platform.ai_mcp_market."create_time" IS '创建时间';
COMMENT ON COLUMN platform.ai_mcp_market."update_by" IS '更新者';
COMMENT ON COLUMN platform.ai_mcp_market."update_time" IS '更新时间';
COMMENT ON COLUMN platform.ai_mcp_market."del_flag" IS '删除标志（0代表存在 2代表删除）';
CREATE INDEX IF NOT EXISTS idx_name ON platform.ai_mcp_market (name);
CREATE INDEX IF NOT EXISTS idx_status ON platform.ai_mcp_market (status);
CREATE INDEX IF NOT EXISTS idx_tenant_id ON platform.ai_mcp_market (tenant_id);

-- ===== mcp_market_tool -> ai_mcp_market_tool =====
CREATE TABLE IF NOT EXISTS platform.ai_mcp_market_tool (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "market_id" bigint NOT NULL,
    "tool_name" varchar(200) NOT NULL,
    "tool_description" text,
    "tool_version" varchar(50) DEFAULT NULL,
    "tool_metadata" jsonb,
    "is_loaded" smallint DEFAULT 0,
    "local_tool_id" bigint DEFAULT NULL,
    "tenant_id" varchar(20) DEFAULT '000000',
    "create_dept" bigint DEFAULT NULL,
    "create_by" bigint DEFAULT NULL,
    "create_time" timestamp DEFAULT NULL,
    "update_by" bigint DEFAULT NULL,
    "update_time" timestamp DEFAULT NULL,
    PRIMARY KEY ("id")
);
COMMENT ON TABLE platform.ai_mcp_market_tool IS 'MCP市场工具关联表';
COMMENT ON COLUMN platform.ai_mcp_market_tool."id" IS 'ID';
COMMENT ON COLUMN platform.ai_mcp_market_tool."market_id" IS '市场ID';
COMMENT ON COLUMN platform.ai_mcp_market_tool."tool_name" IS '工具名称';
COMMENT ON COLUMN platform.ai_mcp_market_tool."tool_description" IS '工具描述';
COMMENT ON COLUMN platform.ai_mcp_market_tool."tool_version" IS '工具版本';
COMMENT ON COLUMN platform.ai_mcp_market_tool."tool_metadata" IS '工具元数据（JSON格式）';
COMMENT ON COLUMN platform.ai_mcp_market_tool."is_loaded" IS '是否已加载到本地';
COMMENT ON COLUMN platform.ai_mcp_market_tool."local_tool_id" IS '关联的本地工具ID';
COMMENT ON COLUMN platform.ai_mcp_market_tool."tenant_id" IS '租户编号';
COMMENT ON COLUMN platform.ai_mcp_market_tool."create_dept" IS '创建部门';
COMMENT ON COLUMN platform.ai_mcp_market_tool."create_by" IS '创建者';
COMMENT ON COLUMN platform.ai_mcp_market_tool."create_time" IS '创建时间';
COMMENT ON COLUMN platform.ai_mcp_market_tool."update_by" IS '更新者';
COMMENT ON COLUMN platform.ai_mcp_market_tool."update_time" IS '更新时间';
CREATE INDEX IF NOT EXISTS idx_market_id ON platform.ai_mcp_market_tool (market_id);
CREATE INDEX IF NOT EXISTS idx_tenant_market ON platform.ai_mcp_market_tool (tenant_id, market_id);
CREATE INDEX IF NOT EXISTS idx_tool_name ON platform.ai_mcp_market_tool (tool_name);
CREATE INDEX IF NOT EXISTS idx_is_loaded ON platform.ai_mcp_market_tool (is_loaded);

-- ===== mcp_tool_info -> ai_mcp_tool =====
CREATE TABLE IF NOT EXISTS platform.ai_mcp_tool (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "name" varchar(200) NOT NULL,
    "description" text,
    "type" varchar(20) DEFAULT 'LOCAL',
    "status" varchar(20) DEFAULT 'ENABLED',
    "config_json" text,
    "tenant_id" varchar(20) DEFAULT '000000',
    "create_dept" bigint DEFAULT NULL,
    "create_by" bigint DEFAULT NULL,
    "create_time" timestamp DEFAULT NULL,
    "update_by" bigint DEFAULT NULL,
    "update_time" timestamp DEFAULT NULL,
    "del_flag" char(1) DEFAULT '0',
    PRIMARY KEY ("id")
);
COMMENT ON TABLE platform.ai_mcp_tool IS 'MCP工具表';
COMMENT ON COLUMN platform.ai_mcp_tool."id" IS '工具ID';
COMMENT ON COLUMN platform.ai_mcp_tool."name" IS '工具名称';
COMMENT ON COLUMN platform.ai_mcp_tool."description" IS '工具描述';
COMMENT ON COLUMN platform.ai_mcp_tool."type" IS '工具类型：LOCAL-本地, REMOTE-远程, BUILTIN-内置';
COMMENT ON COLUMN platform.ai_mcp_tool."status" IS '状态：ENABLED-启用, DISABLED-禁用';
COMMENT ON COLUMN platform.ai_mcp_tool."config_json" IS '配置信息（JSON格式）';
COMMENT ON COLUMN platform.ai_mcp_tool."tenant_id" IS '租户编号';
COMMENT ON COLUMN platform.ai_mcp_tool."create_dept" IS '创建部门';
COMMENT ON COLUMN platform.ai_mcp_tool."create_by" IS '创建者';
COMMENT ON COLUMN platform.ai_mcp_tool."create_time" IS '创建时间';
COMMENT ON COLUMN platform.ai_mcp_tool."update_by" IS '更新者';
COMMENT ON COLUMN platform.ai_mcp_tool."update_time" IS '更新时间';
COMMENT ON COLUMN platform.ai_mcp_tool."del_flag" IS '删除标志（0代表存在 2代表删除）';
CREATE INDEX IF NOT EXISTS idx_name ON platform.ai_mcp_tool (name);
CREATE INDEX IF NOT EXISTS idx_type ON platform.ai_mcp_tool (type);
CREATE INDEX IF NOT EXISTS idx_status ON platform.ai_mcp_tool (status);
CREATE INDEX IF NOT EXISTS idx_tenant_id ON platform.ai_mcp_tool (tenant_id);

-- ===== t_workflow -> ai_flow_workflow =====
CREATE TABLE IF NOT EXISTS platform.ai_flow_workflow (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "uuid" varchar(32) NOT NULL DEFAULT 'uuid',
    "title" varchar(100) NOT NULL DEFAULT '标题',
    "user_id" bigint NOT NULL DEFAULT 0,
    "is_public" smallint NOT NULL DEFAULT 0,
    "is_enable" smallint NOT NULL DEFAULT 1,
    "create_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "update_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "remark" text,
    "is_deleted" smallint NOT NULL DEFAULT 0,
    "tenant_id" varchar(20) DEFAULT '000000',
    PRIMARY KEY ("id")
);
COMMENT ON TABLE platform.ai_flow_workflow IS '工作流定义（用户定义的工作流）| Workflow Definition';
COMMENT ON COLUMN platform.ai_flow_workflow."id" IS 'id';
COMMENT ON COLUMN platform.ai_flow_workflow."user_id" IS '用户ID';
COMMENT ON COLUMN platform.ai_flow_workflow."is_public" IS '是否公开';
COMMENT ON COLUMN platform.ai_flow_workflow."is_enable" IS '是否启用';
COMMENT ON COLUMN platform.ai_flow_workflow."create_time" IS '创建时间';
COMMENT ON COLUMN platform.ai_flow_workflow."update_time" IS '更新时间';
COMMENT ON COLUMN platform.ai_flow_workflow."remark" IS '备注';
COMMENT ON COLUMN platform.ai_flow_workflow."is_deleted" IS '逻辑删除 默认0不删除';
COMMENT ON COLUMN platform.ai_flow_workflow."tenant_id" IS '租户编号';

-- ===== t_workflow_component -> ai_flow_component =====
CREATE TABLE IF NOT EXISTS platform.ai_flow_component (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "uuid" varchar(32) NOT NULL DEFAULT '',
    "name" varchar(32) NOT NULL DEFAULT '',
    "title" varchar(100) NOT NULL DEFAULT '',
    "remark" text NOT NULL,
    "display_order" integer NOT NULL DEFAULT 0,
    "is_enable" smallint NOT NULL DEFAULT 0,
    "create_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "update_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "is_deleted" smallint NOT NULL DEFAULT 0,
    "tenant_id" varchar(20) DEFAULT '000000',
    PRIMARY KEY ("id")
);
COMMENT ON TABLE platform.ai_flow_component IS '工作流组件库 | Workflow Component';
COMMENT ON COLUMN platform.ai_flow_component."tenant_id" IS '租户编号';
CREATE INDEX IF NOT EXISTS idx_display_order ON platform.ai_flow_component (display_order);

-- ===== t_workflow_edge -> ai_flow_edge =====
CREATE TABLE IF NOT EXISTS platform.ai_flow_edge (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "uuid" varchar(32) NOT NULL DEFAULT '',
    "workflow_id" bigint NOT NULL DEFAULT 0,
    "source_node_uuid" varchar(32) NOT NULL DEFAULT '',
    "source_handle" varchar(32) NOT NULL DEFAULT '',
    "target_node_uuid" varchar(32) NOT NULL DEFAULT '',
    "create_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "update_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "is_deleted" smallint NOT NULL DEFAULT 0,
    "tenant_id" varchar(20) DEFAULT '000000',
    PRIMARY KEY ("id")
);
COMMENT ON TABLE platform.ai_flow_edge IS '工作流定义的边 | Edge of Workflow Definition';
COMMENT ON COLUMN platform.ai_flow_edge."id" IS '主键';
COMMENT ON COLUMN platform.ai_flow_edge."uuid" IS '边唯一标识';
COMMENT ON COLUMN platform.ai_flow_edge."workflow_id" IS '所属工作流定义 id';
COMMENT ON COLUMN platform.ai_flow_edge."source_node_uuid" IS '起始节点 uuid';
COMMENT ON COLUMN platform.ai_flow_edge."source_handle" IS '起始锚点标识';
COMMENT ON COLUMN platform.ai_flow_edge."target_node_uuid" IS '目标节点 uuid';
COMMENT ON COLUMN platform.ai_flow_edge."create_time" IS '创建时间';
COMMENT ON COLUMN platform.ai_flow_edge."update_time" IS '更新时间';
COMMENT ON COLUMN platform.ai_flow_edge."is_deleted" IS '逻辑删除：0 正常，1 已删';
COMMENT ON COLUMN platform.ai_flow_edge."tenant_id" IS '租户编号';
CREATE INDEX IF NOT EXISTS idx_workflow_edge_workflow_id ON platform.ai_flow_edge (workflow_id);

-- ===== t_workflow_node -> ai_flow_node =====
CREATE TABLE IF NOT EXISTS platform.ai_flow_node (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "uuid" varchar(32) NOT NULL DEFAULT '',
    "workflow_id" bigint NOT NULL DEFAULT 0,
    "workflow_component_id" bigint NOT NULL DEFAULT 0,
    "user_id" bigint NOT NULL DEFAULT 0,
    "title" varchar(100) NOT NULL DEFAULT '',
    "remark" varchar(500) NOT NULL DEFAULT '',
    "input_config" jsonb NOT NULL,
    "node_config" jsonb,
    "position_x" double precision NOT NULL DEFAULT 0,
    "position_y" double precision NOT NULL DEFAULT 0,
    "create_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "update_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "is_deleted" smallint NOT NULL DEFAULT 0,
    "tenant_id" varchar(20) DEFAULT '000000',
    PRIMARY KEY ("id")
);
COMMENT ON TABLE platform.ai_flow_node IS '工作流定义的节点 | Node of Workflow Definition';
COMMENT ON COLUMN platform.ai_flow_node."id" IS '主键';
COMMENT ON COLUMN platform.ai_flow_node."uuid" IS '节点唯一标识';
COMMENT ON COLUMN platform.ai_flow_node."workflow_id" IS '所属工作流定义 id';
COMMENT ON COLUMN platform.ai_flow_node."workflow_component_id" IS '引用的组件 id';
COMMENT ON COLUMN platform.ai_flow_node."user_id" IS '创建人';
COMMENT ON COLUMN platform.ai_flow_node."title" IS '节点标题';
COMMENT ON COLUMN platform.ai_flow_node."remark" IS '节点备注';
COMMENT ON COLUMN platform.ai_flow_node."input_config" IS '输入参数模板，例：{\"params\":[{\"name\":\"user_define_param01\",\"type\":\"string\"}]}';
COMMENT ON COLUMN platform.ai_flow_node."node_config" IS '节点执行配置，例：{\"params\":[{\"prompt\":\"Summarize the following content:{user_define_param01}\"}]}';
COMMENT ON COLUMN platform.ai_flow_node."position_x" IS '画布 x 坐标';
COMMENT ON COLUMN platform.ai_flow_node."position_y" IS '画布 y 坐标';
COMMENT ON COLUMN platform.ai_flow_node."create_time" IS '创建时间';
COMMENT ON COLUMN platform.ai_flow_node."update_time" IS '更新时间';
COMMENT ON COLUMN platform.ai_flow_node."is_deleted" IS '逻辑删除：0 正常，1 已删';
COMMENT ON COLUMN platform.ai_flow_node."tenant_id" IS '租户编号';
CREATE INDEX IF NOT EXISTS idx_workflow_node_workflow_id ON platform.ai_flow_node (workflow_id);

-- ===== t_workflow_runtime -> ai_flow_runtime =====
CREATE TABLE IF NOT EXISTS platform.ai_flow_runtime (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "uuid" varchar(32) NOT NULL DEFAULT '',
    "user_id" bigint NOT NULL DEFAULT 0,
    "workflow_id" bigint NOT NULL DEFAULT 0,
    "input" jsonb,
    "output" jsonb,
    "status" smallint NOT NULL DEFAULT 1,
    "status_remark" varchar(250) NOT NULL DEFAULT '',
    "create_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "update_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "is_deleted" smallint NOT NULL DEFAULT 0,
    "tenant_id" varchar(20) DEFAULT '000000',
    PRIMARY KEY ("id")
);
COMMENT ON TABLE platform.ai_flow_runtime IS '工作流实例（运行时）| Workflow Runtime';
COMMENT ON COLUMN platform.ai_flow_runtime."id" IS '主键';
COMMENT ON COLUMN platform.ai_flow_runtime."uuid" IS '运行实例唯一标识';
COMMENT ON COLUMN platform.ai_flow_runtime."user_id" IS '启动人';
COMMENT ON COLUMN platform.ai_flow_runtime."workflow_id" IS '对应工作流定义 id';
COMMENT ON COLUMN platform.ai_flow_runtime."input" IS '运行输入，例：{\"userInput01\":\"text01\",\"userInput02\":true,\"userInput03\":10,\"userInput04\":[\"selectedA\",\"selectedB\"],\"userInput05\":[\"https://a.com/a.xlsx\",\"https://a.com/b.png\"]}';
COMMENT ON COLUMN platform.ai_flow_runtime."output" IS '运行输出，成功或失败的结果';
COMMENT ON COLUMN platform.ai_flow_runtime."status" IS '执行状态：1 就绪，2 执行中，3 成功，4 失败';
COMMENT ON COLUMN platform.ai_flow_runtime."status_remark" IS '状态补充说明，如失败原因';
COMMENT ON COLUMN platform.ai_flow_runtime."create_time" IS '创建时间';
COMMENT ON COLUMN platform.ai_flow_runtime."update_time" IS '更新时间';
COMMENT ON COLUMN platform.ai_flow_runtime."is_deleted" IS '逻辑删除：0 正常，1 已删';
COMMENT ON COLUMN platform.ai_flow_runtime."tenant_id" IS '租户编号';
CREATE INDEX IF NOT EXISTS idx_workflow_runtime_workflow_id ON platform.ai_flow_runtime (workflow_id);
CREATE INDEX IF NOT EXISTS idx_workflow_runtime_user_id ON platform.ai_flow_runtime (user_id);

-- ===== t_workflow_runtime_node -> ai_flow_runtime_node =====
CREATE TABLE IF NOT EXISTS platform.ai_flow_runtime_node (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "uuid" varchar(32) NOT NULL DEFAULT '',
    "user_id" bigint NOT NULL DEFAULT 0,
    "workflow_runtime_id" bigint NOT NULL DEFAULT 0,
    "node_id" bigint NOT NULL DEFAULT 0,
    "input" jsonb,
    "output" jsonb,
    "status" smallint NOT NULL DEFAULT 1,
    "status_remark" varchar(250) NOT NULL DEFAULT '',
    "create_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "update_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "is_deleted" smallint NOT NULL DEFAULT 0,
    "tenant_id" varchar(20) DEFAULT '000000',
    PRIMARY KEY ("id")
);
COMMENT ON TABLE platform.ai_flow_runtime_node IS '工作流实例（运行时）- 节点 | Workflow Runtime Node';
COMMENT ON COLUMN platform.ai_flow_runtime_node."id" IS '主键';
COMMENT ON COLUMN platform.ai_flow_runtime_node."uuid" IS '节点运行实例唯一标识';
COMMENT ON COLUMN platform.ai_flow_runtime_node."user_id" IS '创建人';
COMMENT ON COLUMN platform.ai_flow_runtime_node."workflow_runtime_id" IS '所属运行实例 id';
COMMENT ON COLUMN platform.ai_flow_runtime_node."node_id" IS '对应工作流定义里的节点 id';
COMMENT ON COLUMN platform.ai_flow_runtime_node."input" IS '节点本次输入数据';
COMMENT ON COLUMN platform.ai_flow_runtime_node."output" IS '节点本次输出数据';
COMMENT ON COLUMN platform.ai_flow_runtime_node."status" IS '节点执行状态：1 进行中，2 失败，3 成功';
COMMENT ON COLUMN platform.ai_flow_runtime_node."status_remark" IS '状态补充说明，如失败堆栈';
COMMENT ON COLUMN platform.ai_flow_runtime_node."create_time" IS '创建时间';
COMMENT ON COLUMN platform.ai_flow_runtime_node."update_time" IS '更新时间';
COMMENT ON COLUMN platform.ai_flow_runtime_node."is_deleted" IS '逻辑删除：0 正常，1 已删';
COMMENT ON COLUMN platform.ai_flow_runtime_node."tenant_id" IS '租户编号';
CREATE INDEX IF NOT EXISTS idx_runtime_node_runtime_id ON platform.ai_flow_runtime_node (workflow_runtime_id);
CREATE INDEX IF NOT EXISTS idx_runtime_node_node_id ON platform.ai_flow_runtime_node (node_id);

-- ===== trace_run -> ai_flow_trace_run =====
CREATE TABLE IF NOT EXISTS platform.ai_flow_trace_run (
    "id" bigint NOT NULL,
    "trace_id" varchar(64) NOT NULL,
    "trace_name" varchar(128) NOT NULL,
    "business_type" varchar(64) NOT NULL,
    "business_id" varchar(128) DEFAULT NULL,
    "user_id" bigint DEFAULT NULL,
    "tenant_id" varchar(20) DEFAULT '000000',
    "status" varchar(32) NOT NULL,
    "start_time" timestamp NOT NULL,
    "end_time" timestamp DEFAULT NULL,
    "duration_ms" bigint DEFAULT NULL,
    "error_message" varchar(1000) DEFAULT NULL,
    "metadata" text DEFAULT NULL,
    "create_dept" bigint DEFAULT NULL,
    "create_by" bigint DEFAULT NULL,
    "create_time" timestamp DEFAULT NULL,
    "update_by" bigint DEFAULT NULL,
    "update_time" timestamp DEFAULT NULL,
    "del_flag" char(1) DEFAULT '0',
    PRIMARY KEY ("id"),
    CONSTRAINT uk_trace_run_trace_id UNIQUE (trace_id)
);
COMMENT ON TABLE platform.ai_flow_trace_run IS '链路追踪运行记录表';
COMMENT ON COLUMN platform.ai_flow_trace_run."id" IS '主键';
COMMENT ON COLUMN platform.ai_flow_trace_run."trace_id" IS '链路ID';
COMMENT ON COLUMN platform.ai_flow_trace_run."trace_name" IS '链路名称';
COMMENT ON COLUMN platform.ai_flow_trace_run."business_type" IS '业务类型';
COMMENT ON COLUMN platform.ai_flow_trace_run."business_id" IS '业务ID';
COMMENT ON COLUMN platform.ai_flow_trace_run."user_id" IS '用户ID';
COMMENT ON COLUMN platform.ai_flow_trace_run."tenant_id" IS '租户编号';
COMMENT ON COLUMN platform.ai_flow_trace_run."status" IS '状态';
COMMENT ON COLUMN platform.ai_flow_trace_run."start_time" IS '开始时间';
COMMENT ON COLUMN platform.ai_flow_trace_run."end_time" IS '结束时间';
COMMENT ON COLUMN platform.ai_flow_trace_run."duration_ms" IS '耗时毫秒';
COMMENT ON COLUMN platform.ai_flow_trace_run."error_message" IS '错误摘要';
COMMENT ON COLUMN platform.ai_flow_trace_run."metadata" IS '元数据JSON';
COMMENT ON COLUMN platform.ai_flow_trace_run."create_dept" IS '创建部门';
COMMENT ON COLUMN platform.ai_flow_trace_run."create_by" IS '创建者';
COMMENT ON COLUMN platform.ai_flow_trace_run."create_time" IS '创建时间';
COMMENT ON COLUMN platform.ai_flow_trace_run."update_by" IS '更新者';
COMMENT ON COLUMN platform.ai_flow_trace_run."update_time" IS '更新时间';
COMMENT ON COLUMN platform.ai_flow_trace_run."del_flag" IS '删除标志（0代表存在 2代表删除）';
CREATE INDEX IF NOT EXISTS idx_trace_run_business ON platform.ai_flow_trace_run (business_type, business_id);
CREATE INDEX IF NOT EXISTS idx_trace_run_status_time ON platform.ai_flow_trace_run (status, start_time);
CREATE INDEX IF NOT EXISTS idx_trace_run_tenant_time ON platform.ai_flow_trace_run (tenant_id, start_time);

-- ===== trace_node -> ai_flow_trace_node =====
CREATE TABLE IF NOT EXISTS platform.ai_flow_trace_node (
    "id" bigint NOT NULL,
    "trace_id" varchar(64) NOT NULL,
    "node_id" varchar(64) NOT NULL,
    "tenant_id" varchar(20) DEFAULT '000000',
    "parent_node_id" varchar(64) DEFAULT NULL,
    "node_name" varchar(128) NOT NULL,
    "node_type" varchar(64) NOT NULL,
    "depth" integer DEFAULT 0,
    "sort_order" integer DEFAULT 0,
    "class_name" varchar(255) DEFAULT NULL,
    "method_name" varchar(128) DEFAULT NULL,
    "status" varchar(32) NOT NULL,
    "start_time" timestamp NOT NULL,
    "end_time" timestamp DEFAULT NULL,
    "duration_ms" bigint DEFAULT NULL,
    "error_message" varchar(1000) DEFAULT NULL,
    "input_payload" text DEFAULT NULL,
    "output_payload" text DEFAULT NULL,
    "metadata" text DEFAULT NULL,
    "create_dept" bigint DEFAULT NULL,
    "create_by" bigint DEFAULT NULL,
    "create_time" timestamp DEFAULT NULL,
    "update_by" bigint DEFAULT NULL,
    "update_time" timestamp DEFAULT NULL,
    "del_flag" char(1) DEFAULT '0',
    PRIMARY KEY ("id")
);
COMMENT ON TABLE platform.ai_flow_trace_node IS '链路追踪节点记录表';
COMMENT ON COLUMN platform.ai_flow_trace_node."id" IS '主键';
COMMENT ON COLUMN platform.ai_flow_trace_node."trace_id" IS '链路ID';
COMMENT ON COLUMN platform.ai_flow_trace_node."node_id" IS '节点ID';
COMMENT ON COLUMN platform.ai_flow_trace_node."tenant_id" IS '租户编号';
COMMENT ON COLUMN platform.ai_flow_trace_node."parent_node_id" IS '父节点ID';
COMMENT ON COLUMN platform.ai_flow_trace_node."node_name" IS '节点名称';
COMMENT ON COLUMN platform.ai_flow_trace_node."node_type" IS '节点类型';
COMMENT ON COLUMN platform.ai_flow_trace_node."depth" IS '节点深度';
COMMENT ON COLUMN platform.ai_flow_trace_node."sort_order" IS '排序';
COMMENT ON COLUMN platform.ai_flow_trace_node."class_name" IS '类名';
COMMENT ON COLUMN platform.ai_flow_trace_node."method_name" IS '方法名';
COMMENT ON COLUMN platform.ai_flow_trace_node."status" IS '状态';
COMMENT ON COLUMN platform.ai_flow_trace_node."start_time" IS '开始时间';
COMMENT ON COLUMN platform.ai_flow_trace_node."end_time" IS '结束时间';
COMMENT ON COLUMN platform.ai_flow_trace_node."duration_ms" IS '耗时毫秒';
COMMENT ON COLUMN platform.ai_flow_trace_node."error_message" IS '错误摘要';
COMMENT ON COLUMN platform.ai_flow_trace_node."input_payload" IS '输入JSON';
COMMENT ON COLUMN platform.ai_flow_trace_node."output_payload" IS '输出JSON';
COMMENT ON COLUMN platform.ai_flow_trace_node."metadata" IS '元数据JSON';
COMMENT ON COLUMN platform.ai_flow_trace_node."create_dept" IS '创建部门';
COMMENT ON COLUMN platform.ai_flow_trace_node."create_by" IS '创建者';
COMMENT ON COLUMN platform.ai_flow_trace_node."create_time" IS '创建时间';
COMMENT ON COLUMN platform.ai_flow_trace_node."update_by" IS '更新者';
COMMENT ON COLUMN platform.ai_flow_trace_node."update_time" IS '更新时间';
COMMENT ON COLUMN platform.ai_flow_trace_node."del_flag" IS '删除标志（0代表存在 2代表删除）';
CREATE INDEX IF NOT EXISTS idx_trace_node_trace_id ON platform.ai_flow_trace_node (trace_id);
CREATE INDEX IF NOT EXISTS idx_trace_node_parent ON platform.ai_flow_trace_node (trace_id, parent_node_id);
CREATE INDEX IF NOT EXISTS idx_trace_node_time ON platform.ai_flow_trace_node (trace_id, start_time);
CREATE INDEX IF NOT EXISTS idx_trace_node_tenant_time ON platform.ai_flow_trace_node (tenant_id, start_time);
CREATE INDEX IF NOT EXISTS idx_trace_node_type_status ON platform.ai_flow_trace_node (node_type, status);

-- ===== short_drama_project -> ai_short_drama_project =====
CREATE TABLE IF NOT EXISTS platform.ai_short_drama_project (
    "id" bigint NOT NULL,
    "user_id" bigint NOT NULL,
    "project_name" varchar(200) NOT NULL,
    "description" text,
    "status" varchar(32) NOT NULL DEFAULT 'draft',
    "create_dept" bigint DEFAULT NULL,
    "create_by" bigint DEFAULT NULL,
    "create_time" timestamp DEFAULT CURRENT_TIMESTAMP,
    "update_by" bigint DEFAULT NULL,
    "update_time" timestamp DEFAULT CURRENT_TIMESTAMP,
    "tenant_id" bigint NOT NULL DEFAULT 0,
    "art_style" varchar(32) DEFAULT 'realistic',
    "composed_video_oss_id" bigint DEFAULT NULL,
    "compose_status" varchar(32) DEFAULT NULL,
    "compose_job_id" varchar(64) DEFAULT NULL,
    "compose_progress" integer NOT NULL DEFAULT 0,
    "compose_transition_type" varchar(32) NOT NULL DEFAULT 'dissolve',
    "compose_transition_duration_seconds" numeric NOT NULL DEFAULT 0.500,
    "compose_aspect_ratio" varchar(16) NOT NULL DEFAULT '9:16',
    "composed_video_duration_seconds" numeric DEFAULT NULL,
    "compose_error_message" varchar(1000) DEFAULT NULL,
    "composed_at" timestamp DEFAULT NULL,
    PRIMARY KEY ("id")
);
COMMENT ON TABLE platform.ai_short_drama_project IS '短剧项目表';
COMMENT ON COLUMN platform.ai_short_drama_project."id" IS '主键';
COMMENT ON COLUMN platform.ai_short_drama_project."user_id" IS '用户ID';
COMMENT ON COLUMN platform.ai_short_drama_project."project_name" IS '项目名称';
COMMENT ON COLUMN platform.ai_short_drama_project."description" IS '项目描述';
COMMENT ON COLUMN platform.ai_short_drama_project."status" IS '状态：draft/active/archived';
COMMENT ON COLUMN platform.ai_short_drama_project."create_dept" IS '创建部门';
COMMENT ON COLUMN platform.ai_short_drama_project."create_by" IS '创建者';
COMMENT ON COLUMN platform.ai_short_drama_project."create_time" IS '创建时间';
COMMENT ON COLUMN platform.ai_short_drama_project."update_by" IS '更新者';
COMMENT ON COLUMN platform.ai_short_drama_project."update_time" IS '更新时间';
COMMENT ON COLUMN platform.ai_short_drama_project."tenant_id" IS '租户Id';
COMMENT ON COLUMN platform.ai_short_drama_project."art_style" IS '视觉风格：american-comic=美漫, chinese-comic=国漫, japanese-anime=日系, realistic=写实';
COMMENT ON COLUMN platform.ai_short_drama_project."composed_video_oss_id" IS '最新成片OSS对象ID';
COMMENT ON COLUMN platform.ai_short_drama_project."compose_status" IS '合成状态：NULL未合成，pending/processing/done/failed';
COMMENT ON COLUMN platform.ai_short_drama_project."compose_job_id" IS '当前合成任务标识（并发防重）';
COMMENT ON COLUMN platform.ai_short_drama_project."compose_progress" IS '合成进度：0-100';
COMMENT ON COLUMN platform.ai_short_drama_project."compose_transition_type" IS '转场类型：none/dissolve/fade/slide';
COMMENT ON COLUMN platform.ai_short_drama_project."compose_transition_duration_seconds" IS '单次转场时长（秒）';
COMMENT ON COLUMN platform.ai_short_drama_project."compose_aspect_ratio" IS '成片画幅：9:16/16:9/1:1';
COMMENT ON COLUMN platform.ai_short_drama_project."composed_video_duration_seconds" IS '最终成片实际时长（秒，ffprobe测量）';
COMMENT ON COLUMN platform.ai_short_drama_project."compose_error_message" IS '最近一次合成失败原因';
COMMENT ON COLUMN platform.ai_short_drama_project."composed_at" IS '最近一次合成完成时间';
CREATE INDEX IF NOT EXISTS idx_user_id ON platform.ai_short_drama_project (user_id);
CREATE INDEX IF NOT EXISTS idx_tenant_id ON platform.ai_short_drama_project (tenant_id);

-- ===== short_drama_script -> ai_short_drama_script =====
CREATE TABLE IF NOT EXISTS platform.ai_short_drama_script (
    "id" bigint NOT NULL,
    "project_id" bigint NOT NULL,
    "script_name" varchar(200) NOT NULL,
    "script_text" text,
    "outline_text" text,
    "tone" varchar(100) DEFAULT NULL,
    "source_type" varchar(32) NOT NULL DEFAULT 'manual',
    "create_dept" bigint DEFAULT NULL,
    "create_by" bigint DEFAULT NULL,
    "create_time" timestamp DEFAULT CURRENT_TIMESTAMP,
    "update_by" bigint DEFAULT NULL,
    "update_time" timestamp DEFAULT CURRENT_TIMESTAMP,
    "tenant_id" bigint NOT NULL DEFAULT 0,
    PRIMARY KEY ("id")
);
COMMENT ON TABLE platform.ai_short_drama_script IS '短剧剧本表';
COMMENT ON COLUMN platform.ai_short_drama_script."id" IS '主键';
COMMENT ON COLUMN platform.ai_short_drama_script."project_id" IS '项目ID';
COMMENT ON COLUMN platform.ai_short_drama_script."script_name" IS '剧本名称';
COMMENT ON COLUMN platform.ai_short_drama_script."script_text" IS '剧本文本';
COMMENT ON COLUMN platform.ai_short_drama_script."outline_text" IS '大纲文本';
COMMENT ON COLUMN platform.ai_short_drama_script."tone" IS '风格/基调';
COMMENT ON COLUMN platform.ai_short_drama_script."source_type" IS '来源：manual/ai';
COMMENT ON COLUMN platform.ai_short_drama_script."create_dept" IS '创建部门';
COMMENT ON COLUMN platform.ai_short_drama_script."create_by" IS '创建者';
COMMENT ON COLUMN platform.ai_short_drama_script."create_time" IS '创建时间';
COMMENT ON COLUMN platform.ai_short_drama_script."update_by" IS '更新者';
COMMENT ON COLUMN platform.ai_short_drama_script."update_time" IS '更新时间';
COMMENT ON COLUMN platform.ai_short_drama_script."tenant_id" IS '租户Id';
CREATE INDEX IF NOT EXISTS idx_project_id ON platform.ai_short_drama_script (project_id);
CREATE INDEX IF NOT EXISTS idx_tenant_id ON platform.ai_short_drama_script (tenant_id);

-- ===== short_drama_storyboard -> ai_short_drama_storyboard =====
CREATE TABLE IF NOT EXISTS platform.ai_short_drama_storyboard (
    "id" bigint NOT NULL,
    "project_id" bigint NOT NULL,
    "script_id" bigint NOT NULL,
    "scene_no" integer NOT NULL,
    "scene_title" varchar(200) DEFAULT NULL,
    "scene_text" text,
    "scene_type" varchar(32) DEFAULT 'daily',
    "shot_type" varchar(64) DEFAULT NULL,
    "camera_move" varchar(64) DEFAULT NULL,
    "characters_json" text,
    "location_name" varchar(200) DEFAULT NULL,
    "photography_rules" text,
    "acting_notes" text,
    "continuity_json" text,
    "source_text" text,
    "image_prompt" text,
    "duration_seconds" integer NOT NULL DEFAULT 15,
    "video_prompt" text,
    "video_url" text,
    "video_id" varchar(128) DEFAULT NULL,
    "video_status" varchar(32) NOT NULL DEFAULT 'pending',
    "last_frame_url" text,
    "create_dept" bigint DEFAULT NULL,
    "create_by" bigint DEFAULT NULL,
    "create_time" timestamp DEFAULT CURRENT_TIMESTAMP,
    "update_by" bigint DEFAULT NULL,
    "update_time" timestamp DEFAULT CURRENT_TIMESTAMP,
    "tenant_id" bigint NOT NULL DEFAULT 0,
    PRIMARY KEY ("id"),
    CONSTRAINT uk_script_scene UNIQUE (script_id, scene_no)
);
COMMENT ON TABLE platform.ai_short_drama_storyboard IS '短剧分镜表';
COMMENT ON COLUMN platform.ai_short_drama_storyboard."id" IS '主键';
COMMENT ON COLUMN platform.ai_short_drama_storyboard."project_id" IS '项目ID';
COMMENT ON COLUMN platform.ai_short_drama_storyboard."script_id" IS '剧本ID';
COMMENT ON COLUMN platform.ai_short_drama_storyboard."scene_no" IS '分镜序号';
COMMENT ON COLUMN platform.ai_short_drama_storyboard."scene_title" IS '分镜标题';
COMMENT ON COLUMN platform.ai_short_drama_storyboard."scene_text" IS '分镜说明';
COMMENT ON COLUMN platform.ai_short_drama_storyboard."scene_type" IS '场景类型：daily/emotion/action/epic/suspense';
COMMENT ON COLUMN platform.ai_short_drama_storyboard."shot_type" IS '镜头景别：如平视中景/俯拍远景';
COMMENT ON COLUMN platform.ai_short_drama_storyboard."camera_move" IS '镜头运动：如缓推/固定/跟随/环绕';
COMMENT ON COLUMN platform.ai_short_drama_storyboard."characters_json" IS '镜头角色列表JSON：[{name,appearance,slot}]';
COMMENT ON COLUMN platform.ai_short_drama_storyboard."location_name" IS '场景名称（匹配资产库）';
COMMENT ON COLUMN platform.ai_short_drama_storyboard."photography_rules" IS '摄影规则JSON';
COMMENT ON COLUMN platform.ai_short_drama_storyboard."acting_notes" IS '表演指导JSON';
COMMENT ON COLUMN platform.ai_short_drama_storyboard."continuity_json" IS '镜头连续性JSON：起始状态、结束状态、动作承接、空间锚点、在场人物';
COMMENT ON COLUMN platform.ai_short_drama_storyboard."source_text" IS '原文片段';
COMMENT ON COLUMN platform.ai_short_drama_storyboard."image_prompt" IS '图片生成提示词';
COMMENT ON COLUMN platform.ai_short_drama_storyboard."duration_seconds" IS '时长秒数';
COMMENT ON COLUMN platform.ai_short_drama_storyboard."video_prompt" IS '视频提示词';
COMMENT ON COLUMN platform.ai_short_drama_storyboard."video_url" IS '视频地址';
COMMENT ON COLUMN platform.ai_short_drama_storyboard."video_id" IS '视频生成任务ID';
COMMENT ON COLUMN platform.ai_short_drama_storyboard."video_status" IS '视频状态：pending/generating/done/failed';
COMMENT ON COLUMN platform.ai_short_drama_storyboard."last_frame_url" IS '上一镜末帧URL（同场景连续镜头首帧承接用）';
COMMENT ON COLUMN platform.ai_short_drama_storyboard."create_dept" IS '创建部门';
COMMENT ON COLUMN platform.ai_short_drama_storyboard."create_by" IS '创建者';
COMMENT ON COLUMN platform.ai_short_drama_storyboard."create_time" IS '创建时间';
COMMENT ON COLUMN platform.ai_short_drama_storyboard."update_by" IS '更新者';
COMMENT ON COLUMN platform.ai_short_drama_storyboard."update_time" IS '更新时间';
COMMENT ON COLUMN platform.ai_short_drama_storyboard."tenant_id" IS '租户Id';
CREATE INDEX IF NOT EXISTS idx_project_id ON platform.ai_short_drama_storyboard (project_id);
CREATE INDEX IF NOT EXISTS idx_script_id ON platform.ai_short_drama_storyboard (script_id);
CREATE INDEX IF NOT EXISTS idx_tenant_id ON platform.ai_short_drama_storyboard (tenant_id);

-- ===== short_drama_character -> ai_short_drama_character =====
CREATE TABLE IF NOT EXISTS platform.ai_short_drama_character (
    "id" bigint NOT NULL,
    "project_id" bigint NOT NULL,
    "name" varchar(100) NOT NULL,
    "aliases" varchar(500) DEFAULT NULL,
    "introduction" text,
    "role_level" varchar(8) DEFAULT 'B',
    "gender" varchar(10) DEFAULT NULL,
    "age_range" varchar(50) DEFAULT NULL,
    "personality_tags" varchar(500) DEFAULT NULL,
    "costume_tier" integer DEFAULT 2,
    "visual_description" text,
    "reference_image_url" text,
    "create_dept" bigint DEFAULT NULL,
    "create_by" bigint DEFAULT NULL,
    "create_time" timestamp DEFAULT CURRENT_TIMESTAMP,
    "update_by" bigint DEFAULT NULL,
    "update_time" timestamp DEFAULT CURRENT_TIMESTAMP,
    "tenant_id" bigint NOT NULL DEFAULT 0,
    PRIMARY KEY ("id")
);
COMMENT ON TABLE platform.ai_short_drama_character IS '短剧角色表';
COMMENT ON COLUMN platform.ai_short_drama_character."id" IS '主键';
COMMENT ON COLUMN platform.ai_short_drama_character."project_id" IS '项目ID';
COMMENT ON COLUMN platform.ai_short_drama_character."name" IS '角色名';
COMMENT ON COLUMN platform.ai_short_drama_character."aliases" IS '别名/称呼（逗号分隔）';
COMMENT ON COLUMN platform.ai_short_drama_character."introduction" IS '角色介绍（身份、关系、称呼映射）';
COMMENT ON COLUMN platform.ai_short_drama_character."role_level" IS '角色层级：S/A/B/C/D';
COMMENT ON COLUMN platform.ai_short_drama_character."gender" IS '性别';
COMMENT ON COLUMN platform.ai_short_drama_character."age_range" IS '年龄段（如：约二十五岁）';
COMMENT ON COLUMN platform.ai_short_drama_character."personality_tags" IS '性格标签（逗号分隔）';
COMMENT ON COLUMN platform.ai_short_drama_character."costume_tier" IS '服装华丽度1-5';
COMMENT ON COLUMN platform.ai_short_drama_character."visual_description" IS '视觉外貌描述（详细，用于图片生成）';
COMMENT ON COLUMN platform.ai_short_drama_character."reference_image_url" IS '角色参考图URL';
COMMENT ON COLUMN platform.ai_short_drama_character."create_dept" IS '创建部门';
COMMENT ON COLUMN platform.ai_short_drama_character."create_by" IS '创建者';
COMMENT ON COLUMN platform.ai_short_drama_character."create_time" IS '创建时间';
COMMENT ON COLUMN platform.ai_short_drama_character."update_by" IS '更新者';
COMMENT ON COLUMN platform.ai_short_drama_character."update_time" IS '更新时间';
COMMENT ON COLUMN platform.ai_short_drama_character."tenant_id" IS '租户Id';
CREATE INDEX IF NOT EXISTS idx_project_id ON platform.ai_short_drama_character (project_id);
CREATE INDEX IF NOT EXISTS idx_tenant_id ON platform.ai_short_drama_character (tenant_id);

-- ===== short_drama_character_appearance -> ai_short_drama_character_appearance =====
CREATE TABLE IF NOT EXISTS platform.ai_short_drama_character_appearance (
    "id" bigint NOT NULL,
    "character_id" bigint NOT NULL,
    "appearance_index" integer NOT NULL DEFAULT 0,
    "change_reason" varchar(200) DEFAULT '初始形象',
    "description" text,
    "reference_image_url" text,
    "create_dept" bigint DEFAULT NULL,
    "create_by" bigint DEFAULT NULL,
    "create_time" timestamp DEFAULT CURRENT_TIMESTAMP,
    "update_by" bigint DEFAULT NULL,
    "update_time" timestamp DEFAULT CURRENT_TIMESTAMP,
    "tenant_id" bigint NOT NULL DEFAULT 0,
    "image_urls" text,
    "image_descriptions" text,
    "selected_image_index" integer DEFAULT 0,
    "previous_image_urls" text,
    "previous_descriptions" text,
    "voice" varchar(100) DEFAULT NULL,
    PRIMARY KEY ("id"),
    CONSTRAINT uk_character_appearance UNIQUE (character_id, appearance_index)
);
COMMENT ON TABLE platform.ai_short_drama_character_appearance IS '短剧角色子形象表';
COMMENT ON COLUMN platform.ai_short_drama_character_appearance."id" IS '主键';
COMMENT ON COLUMN platform.ai_short_drama_character_appearance."character_id" IS '角色ID';
COMMENT ON COLUMN platform.ai_short_drama_character_appearance."appearance_index" IS '形象序号（0=主形象）';
COMMENT ON COLUMN platform.ai_short_drama_character_appearance."change_reason" IS '变化原因';
COMMENT ON COLUMN platform.ai_short_drama_character_appearance."description" IS '形象视觉描述';
COMMENT ON COLUMN platform.ai_short_drama_character_appearance."reference_image_url" IS '形象参考图URL';
COMMENT ON COLUMN platform.ai_short_drama_character_appearance."create_dept" IS '创建部门';
COMMENT ON COLUMN platform.ai_short_drama_character_appearance."create_by" IS '创建者';
COMMENT ON COLUMN platform.ai_short_drama_character_appearance."create_time" IS '创建时间';
COMMENT ON COLUMN platform.ai_short_drama_character_appearance."update_by" IS '更新者';
COMMENT ON COLUMN platform.ai_short_drama_character_appearance."update_time" IS '更新时间';
COMMENT ON COLUMN platform.ai_short_drama_character_appearance."tenant_id" IS '租户Id';
COMMENT ON COLUMN platform.ai_short_drama_character_appearance."image_urls" IS '生成图片URL列表（JSON数组）';
COMMENT ON COLUMN platform.ai_short_drama_character_appearance."image_descriptions" IS '每张图片对应的提示词（JSON数组）';
COMMENT ON COLUMN platform.ai_short_drama_character_appearance."selected_image_index" IS '当前选中的图片索引';
COMMENT ON COLUMN platform.ai_short_drama_character_appearance."previous_image_urls" IS '上一轮图片URL列表（撤销用，JSON数组）';
COMMENT ON COLUMN platform.ai_short_drama_character_appearance."previous_descriptions" IS '上一轮提示词列表（撤销用，JSON数组）';
COMMENT ON COLUMN platform.ai_short_drama_character_appearance."voice" IS '音色名（如 zh_male_taocheng_uranus_bigtts），用于该形象对白配音';
CREATE INDEX IF NOT EXISTS idx_character_id ON platform.ai_short_drama_character_appearance (character_id);
CREATE INDEX IF NOT EXISTS idx_tenant_id ON platform.ai_short_drama_character_appearance (tenant_id);

-- ===== short_drama_location -> ai_short_drama_location =====
CREATE TABLE IF NOT EXISTS platform.ai_short_drama_location (
    "id" bigint NOT NULL,
    "project_id" bigint NOT NULL,
    "name" varchar(200) NOT NULL,
    "summary" varchar(500) DEFAULT NULL,
    "has_crowd" smallint DEFAULT 0,
    "crowd_description" varchar(500) DEFAULT NULL,
    "available_slots" text,
    "descriptions" text,
    "reference_image_url" text,
    "create_dept" bigint DEFAULT NULL,
    "create_by" bigint DEFAULT NULL,
    "create_time" timestamp DEFAULT CURRENT_TIMESTAMP,
    "update_by" bigint DEFAULT NULL,
    "update_time" timestamp DEFAULT CURRENT_TIMESTAMP,
    "tenant_id" bigint NOT NULL DEFAULT 0,
    "image_urls" text,
    "image_descriptions" text,
    "selected_image_index" integer DEFAULT 0,
    "previous_image_urls" text,
    "previous_descriptions" text,
    PRIMARY KEY ("id")
);
COMMENT ON TABLE platform.ai_short_drama_location IS '短剧场景表';
COMMENT ON COLUMN platform.ai_short_drama_location."id" IS '主键';
COMMENT ON COLUMN platform.ai_short_drama_location."project_id" IS '项目ID';
COMMENT ON COLUMN platform.ai_short_drama_location."name" IS '场景名（如：客厅_白天）';
COMMENT ON COLUMN platform.ai_short_drama_location."summary" IS '场景简要说明';
COMMENT ON COLUMN platform.ai_short_drama_location."has_crowd" IS '是否有背景人群';
COMMENT ON COLUMN platform.ai_short_drama_location."crowd_description" IS '背景人群描述';
COMMENT ON COLUMN platform.ai_short_drama_location."available_slots" IS '可站位置列表（JSON数组）';
COMMENT ON COLUMN platform.ai_short_drama_location."descriptions" IS '场景描述列表（JSON数组，3条差异化描述）';
COMMENT ON COLUMN platform.ai_short_drama_location."reference_image_url" IS '场景全景参考图URL';
COMMENT ON COLUMN platform.ai_short_drama_location."create_dept" IS '创建部门';
COMMENT ON COLUMN platform.ai_short_drama_location."create_by" IS '创建者';
COMMENT ON COLUMN platform.ai_short_drama_location."create_time" IS '创建时间';
COMMENT ON COLUMN platform.ai_short_drama_location."update_by" IS '更新者';
COMMENT ON COLUMN platform.ai_short_drama_location."update_time" IS '更新时间';
COMMENT ON COLUMN platform.ai_short_drama_location."tenant_id" IS '租户Id';
COMMENT ON COLUMN platform.ai_short_drama_location."image_urls" IS '生成图片URL列表（JSON数组）';
COMMENT ON COLUMN platform.ai_short_drama_location."image_descriptions" IS '每张图片对应的提示词（JSON数组）';
COMMENT ON COLUMN platform.ai_short_drama_location."selected_image_index" IS '当前选中的图片索引';
COMMENT ON COLUMN platform.ai_short_drama_location."previous_image_urls" IS '上一轮图片URL列表（撤销用，JSON数组）';
COMMENT ON COLUMN platform.ai_short_drama_location."previous_descriptions" IS '上一轮提示词列表（撤销用，JSON数组）';
CREATE INDEX IF NOT EXISTS idx_project_id ON platform.ai_short_drama_location (project_id);
CREATE INDEX IF NOT EXISTS idx_tenant_id ON platform.ai_short_drama_location (tenant_id);

-- ===== short_drama_audio -> ai_short_drama_audio =====
CREATE TABLE IF NOT EXISTS platform.ai_short_drama_audio (
    "id" bigint NOT NULL,
    "project_id" bigint NOT NULL,
    "name" varchar(200) NOT NULL,
    "audio_type" varchar(32) NOT NULL DEFAULT 'narration',
    "text" text NOT NULL,
    "voice" varchar(100) DEFAULT NULL,
    "audio_oss_id" bigint DEFAULT NULL,
    "audio_url" text,
    "linked_storyboard_id" bigint DEFAULT NULL,
    "duration_seconds" integer DEFAULT NULL,
    "create_dept" bigint DEFAULT NULL,
    "create_by" bigint DEFAULT NULL,
    "create_time" timestamp DEFAULT CURRENT_TIMESTAMP,
    "update_by" bigint DEFAULT NULL,
    "update_time" timestamp DEFAULT CURRENT_TIMESTAMP,
    "tenant_id" bigint NOT NULL DEFAULT 0,
    PRIMARY KEY ("id")
);
COMMENT ON TABLE platform.ai_short_drama_audio IS '短剧语音资产表';
COMMENT ON COLUMN platform.ai_short_drama_audio."id" IS '主键';
COMMENT ON COLUMN platform.ai_short_drama_audio."project_id" IS '项目ID';
COMMENT ON COLUMN platform.ai_short_drama_audio."name" IS '语音资产名称';
COMMENT ON COLUMN platform.ai_short_drama_audio."audio_type" IS '语音类型：narration(旁白)/dialogue(对白)';
COMMENT ON COLUMN platform.ai_short_drama_audio."text" IS '语音文案（生成语音用的文本）';
COMMENT ON COLUMN platform.ai_short_drama_audio."voice" IS '音色（如 alloy/onyx）';
COMMENT ON COLUMN platform.ai_short_drama_audio."audio_oss_id" IS '音频文件OSS ID';
COMMENT ON COLUMN platform.ai_short_drama_audio."audio_url" IS '音频文件URL';
COMMENT ON COLUMN platform.ai_short_drama_audio."linked_storyboard_id" IS '对白关联的分镜ID（NULL=全局旁白）';
COMMENT ON COLUMN platform.ai_short_drama_audio."duration_seconds" IS '音频时长（秒）';
COMMENT ON COLUMN platform.ai_short_drama_audio."create_dept" IS '创建部门';
COMMENT ON COLUMN platform.ai_short_drama_audio."create_by" IS '创建者';
COMMENT ON COLUMN platform.ai_short_drama_audio."create_time" IS '创建时间';
COMMENT ON COLUMN platform.ai_short_drama_audio."update_by" IS '更新者';
COMMENT ON COLUMN platform.ai_short_drama_audio."update_time" IS '更新时间';
COMMENT ON COLUMN platform.ai_short_drama_audio."tenant_id" IS '租户Id';
CREATE INDEX IF NOT EXISTS idx_project_id ON platform.ai_short_drama_audio (project_id);
CREATE INDEX IF NOT EXISTS idx_linked_storyboard_id ON platform.ai_short_drama_audio (linked_storyboard_id);
CREATE INDEX IF NOT EXISTS idx_tenant_id ON platform.ai_short_drama_audio (tenant_id);

-- ===== chat_config -> ai_model_config =====
-- 该表在任何已交付脚本里都没有 DDL：ruoyi-ai 的 MySQL 安装脚本、update/ 增量与 platform 的
-- PostgreSQL 迁移中都没有 CREATE TABLE chat_config，但实体/服务/控制器都存在
-- （org.ruoyi.system.domain.ChatConfig extends TenantEntity），说明建表语句只存在于作者的开发库。
-- 因此本表按 Java 实体字段补齐（含 TenantEntity 的 tenant_id 与 BaseEntity 的审计列），不做 SQL 转换。
-- E0 表映射把本表来源标注为 java-entity 以保持可追溯。
--
-- tenant_id 类型是 E2 待决项 E2-D1：platform 的 sys_tenant.tenant_id 为 varchar(20)，
-- 而 AI 域既有表（含本文件其余表）用 bigint。统一租户表示需要真实 ID 映射；
-- 在决定之前这里沿用 AI 域的 bigint，不做静默类型强转。
CREATE TABLE IF NOT EXISTS platform.ai_model_config (
    "id" bigint NOT NULL,
    "tenant_id" bigint NOT NULL DEFAULT 0,
    "category" varchar(64) DEFAULT NULL,
    "config_name" varchar(128) NOT NULL,
    "config_value" varchar(1024) DEFAULT NULL,
    "config_dict" varchar(512) DEFAULT NULL,
    "remark" varchar(500) DEFAULT NULL,
    "version" bigint DEFAULT NULL,
    "del_flag" char(1) NOT NULL DEFAULT '0',
    "update_ip" varchar(64) DEFAULT NULL,
    "create_dept" bigint DEFAULT NULL,
    "create_by" bigint DEFAULT NULL,
    "create_time" timestamp DEFAULT NULL,
    "update_by" bigint DEFAULT NULL,
    "update_time" timestamp DEFAULT NULL,
    PRIMARY KEY ("id"),
    CONSTRAINT uk_model_config_tenant UNIQUE (tenant_id, category, config_name, del_flag)
);
COMMENT ON TABLE platform.ai_model_config IS '模型/系统配置（按实体补齐，原仓库无 DDL）';
COMMENT ON COLUMN platform.ai_model_config."tenant_id" IS '租户Id（E2-D1 待统一类型）';
CREATE INDEX IF NOT EXISTS idx_model_config_tenant ON platform.ai_model_config (tenant_id);

