-- ---------------------------------------------------------------------------
-- E2 legacy MySQL AI domain: staging (landing zone) for the row-data migration V11.
--
-- Generated by scripts/db/generate-legacy-ai-copy.py. This file is NOT a Flyway migration:
-- the operator runs it once, before the platform migration chain reaches V11.
--
-- Usage:
--   1. create the staging schema and tables:  psql -f 10-legacy-ai-domain-staging.sql
--   2. load the MySQL rows with their original column names (pgloader or CSV + COPY):
--        pgloader mysql://user@host/ruoyi_ai postgresql:///unified?schema=legacy_mysql
--      or, per table:
--        mysql -e "SELECT * FROM chat_model" --batch --raw > chat_model.tsv
--        psql -c "\copy legacy_mysql.chat_model FROM 'chat_model.tsv'"
--   3. run the platform migration chain (Flyway applies V11 and moves the rows)
--   4. verify, then drop the landing zone:  DROP SCHEMA legacy_mysql CASCADE;
--
-- Column names are the MySQL names on purpose: V11's mapping registry names them
-- explicitly, and a mismatch is refused rather than resolved by position. Types are the
-- MySQL types mapped to PostgreSQL *without* the tenant normalisation V9 applies, so the
-- casts the copy performs stay visible in the migration.
-- ---------------------------------------------------------------------------

CREATE SCHEMA IF NOT EXISTS legacy_mysql;

-- ===== agent_info  -- 智能体信息表 =====
CREATE TABLE IF NOT EXISTS legacy_mysql.agent_info (
    "id" bigint NOT NULL,
    "tenant_id" bigint NOT NULL DEFAULT 0,
    "agent_name" varchar(200) NOT NULL,
    "agent_describe" varchar(500) DEFAULT NULL,
    "agent_show" varchar(255) DEFAULT NULL,
    "model_id" bigint NOT NULL,
    "enable_thinking" char(1) DEFAULT '0',
    "system_prompt" text,
    "mcp_tool_ids" varchar(1024) DEFAULT NULL,
    "skill_names" varchar(1024) DEFAULT NULL,
    "knowledge_ids" varchar(1024) DEFAULT NULL,
    "status" char(1) DEFAULT '0',
    "remark" varchar(500) DEFAULT NULL,
    "create_dept" bigint DEFAULT NULL,
    "create_by" bigint DEFAULT NULL,
    "create_time" timestamp DEFAULT NULL,
    "update_by" bigint DEFAULT NULL,
    "update_time" timestamp DEFAULT NULL
);
-- ===== chat_config: no DDL in the shipped MySQL script (entity-only table, see V10);
--       create it from the live MySQL catalog, keeping the column names
--       V11 maps (category, config_dict, config_name, config_value, create_by, create_dept, create_time, del_flag, id, remark, tenant_id, update_by, update_ip, update_time, version).
-- ===== chat_message  -- 聊天消息表 =====
CREATE TABLE IF NOT EXISTS legacy_mysql.chat_message (
    "id" bigint NOT NULL,
    "session_id" bigint DEFAULT NULL,
    "user_id" bigint NOT NULL,
    "content" text,
    "role" varchar(255) DEFAULT NULL,
    "total_tokens" integer DEFAULT 0,
    "model_name" varchar(255) DEFAULT NULL,
    "create_dept" bigint DEFAULT NULL,
    "create_by" bigint DEFAULT NULL,
    "create_time" timestamp DEFAULT NULL,
    "update_by" bigint DEFAULT NULL,
    "update_time" timestamp DEFAULT NULL,
    "remark" varchar(500) DEFAULT NULL,
    "tenant_id" bigint NOT NULL DEFAULT 0
);
-- ===== chat_model  -- 模型管理 =====
CREATE TABLE IF NOT EXISTS legacy_mysql.chat_model (
    "id" bigint NOT NULL,
    "category" varchar(20) DEFAULT NULL,
    "model_name" varchar(50) DEFAULT NULL,
    "provider_code" varchar(20) DEFAULT NULL,
    "model_describe" varchar(255) DEFAULT NULL,
    "model_dimension" integer DEFAULT NULL,
    "model_show" char(1) DEFAULT NULL,
    "api_host" varchar(255) DEFAULT NULL,
    "api_key" varchar(255) DEFAULT NULL,
    "create_dept" bigint DEFAULT NULL,
    "create_by" bigint DEFAULT NULL,
    "create_time" timestamp DEFAULT NULL,
    "update_by" bigint DEFAULT NULL,
    "update_time" timestamp DEFAULT NULL,
    "remark" varchar(500) DEFAULT NULL,
    "tenant_id" bigint NOT NULL DEFAULT 0
);
-- ===== chat_provider  -- 厂商管理表 =====
CREATE TABLE IF NOT EXISTS legacy_mysql.chat_provider (
    "id" bigint NOT NULL,
    "provider_name" varchar(100) NOT NULL,
    "provider_code" varchar(50) NOT NULL,
    "provider_icon" varchar(1000) DEFAULT NULL,
    "provider_desc" varchar(500) DEFAULT NULL,
    "api_host" varchar(255) DEFAULT NULL,
    "status" char(1) DEFAULT '0',
    "sort_order" integer DEFAULT 0,
    "create_dept" bigint DEFAULT NULL,
    "create_time" timestamp DEFAULT NULL,
    "create_by" varchar(64) DEFAULT '',
    "update_by" varchar(64) DEFAULT '',
    "update_time" timestamp DEFAULT NULL,
    "remark" varchar(500) DEFAULT NULL,
    "version" integer DEFAULT NULL,
    "del_flag" char(1) DEFAULT '0',
    "update_ip" varchar(128) DEFAULT NULL,
    "tenant_id" bigint NOT NULL DEFAULT 0
);
-- ===== chat_session  -- 会话管理 =====
CREATE TABLE IF NOT EXISTS legacy_mysql.chat_session (
    "id" bigint NOT NULL,
    "user_id" bigint DEFAULT NULL,
    "session_title" varchar(255) DEFAULT NULL,
    "session_content" text,
    "create_dept" varchar(255) DEFAULT NULL,
    "create_by" bigint DEFAULT NULL,
    "create_time" timestamp DEFAULT NULL,
    "update_by" bigint DEFAULT NULL,
    "update_time" timestamp DEFAULT NULL,
    "remark" varchar(500) DEFAULT NULL,
    "conversation_id" varchar(32) DEFAULT NULL,
    "tenant_id" bigint NOT NULL DEFAULT 0
);
-- ===== knowledge_attach  -- 知识库附件 =====
CREATE TABLE IF NOT EXISTS legacy_mysql.knowledge_attach (
    "id" bigint NOT NULL,
    "knowledge_id" bigint NOT NULL,
    "oss_id" bigint DEFAULT NULL,
    "doc_id" varchar(32) DEFAULT NULL,
    "file_hash" varchar(64) DEFAULT NULL,
    "name" varchar(500) DEFAULT NULL,
    "type" varchar(50) NOT NULL,
    "create_dept" varchar(255) DEFAULT NULL,
    "create_by" varchar(50) DEFAULT NULL,
    "create_time" timestamp DEFAULT NULL,
    "update_by" bigint DEFAULT NULL,
    "update_time" timestamp DEFAULT NULL,
    "remark" varchar(500) DEFAULT NULL,
    "tenant_id" bigint NOT NULL DEFAULT 0,
    "status" smallint DEFAULT 0
);
-- ===== knowledge_fragment  -- 知识片段 =====
CREATE TABLE IF NOT EXISTS legacy_mysql.knowledge_fragment (
    "id" bigint NOT NULL,
    "fid" varchar(32) NOT NULL,
    "idx" integer NOT NULL,
    "doc_id" varchar(32) DEFAULT NULL,
    "content" text NOT NULL,
    "create_dept" varchar(255) DEFAULT NULL,
    "create_by" varchar(50) DEFAULT NULL,
    "create_time" timestamp DEFAULT NULL,
    "update_by" bigint DEFAULT NULL,
    "update_time" timestamp DEFAULT NULL,
    "remark" varchar(500) DEFAULT NULL,
    "tenant_id" bigint NOT NULL DEFAULT 0,
    "knowledge_id" bigint DEFAULT NULL
);
-- ===== knowledge_info  -- 知识库 =====
CREATE TABLE IF NOT EXISTS legacy_mysql.knowledge_info (
    "id" bigint NOT NULL,
    "user_id" bigint NOT NULL DEFAULT 0,
    "name" varchar(50) NOT NULL,
    "share" smallint DEFAULT NULL,
    "description" varchar(1000) DEFAULT NULL,
    "separator" varchar(255) DEFAULT NULL,
    "overlap_char" integer DEFAULT NULL,
    "retrieve_limit" integer DEFAULT NULL,
    "similarity_threshold" double precision DEFAULT 0.5,
    "text_block_size" integer DEFAULT NULL,
    "vector_model" varchar(50) DEFAULT NULL,
    "embedding_model" varchar(50) DEFAULT NULL,
    "create_dept" varchar(255) DEFAULT NULL,
    "create_by" varchar(50) DEFAULT NULL,
    "create_time" timestamp DEFAULT NULL,
    "update_by" bigint DEFAULT NULL,
    "update_time" timestamp DEFAULT NULL,
    "remark" varchar(500) DEFAULT NULL,
    "tenant_id" bigint NOT NULL DEFAULT 0,
    "enable_rerank" smallint DEFAULT 0,
    "rerank_score_threshold" double precision DEFAULT NULL,
    "rerank_top_n" integer DEFAULT NULL,
    "rerank_model" varchar(100) DEFAULT NULL,
    "enable_hybrid" smallint DEFAULT 0,
    "hybrid_alpha" double precision DEFAULT 0.5,
    "system_prompt" text
);
-- ===== mcp_market_info  -- MCP市场表 =====
CREATE TABLE IF NOT EXISTS legacy_mysql.mcp_market_info (
    "id" bigint NOT NULL,
    "name" varchar(200) NOT NULL,
    "url" varchar(500) NOT NULL,
    "description" text,
    "auth_config" text,
    "status" varchar(20) DEFAULT 'ENABLED',
    "tenant_id" varchar(20) DEFAULT '000000',
    "create_dept" bigint DEFAULT NULL,
    "create_by" bigint DEFAULT NULL,
    "create_time" timestamp DEFAULT NULL,
    "update_by" bigint DEFAULT NULL,
    "update_time" timestamp DEFAULT NULL,
    "del_flag" char(1) DEFAULT '0'
);
-- ===== mcp_market_tool  -- MCP市场工具关联表 =====
CREATE TABLE IF NOT EXISTS legacy_mysql.mcp_market_tool (
    "id" bigint NOT NULL,
    "market_id" bigint NOT NULL,
    "tool_name" varchar(200) NOT NULL,
    "tool_description" text,
    "tool_version" varchar(50) DEFAULT NULL,
    "tool_metadata" jsonb,
    "is_loaded" smallint DEFAULT 0,
    "local_tool_id" bigint DEFAULT NULL,
    "tenant_id" varchar(20) DEFAULT '000000',
    "create_dept" bigint DEFAULT NULL,
    "create_by" bigint DEFAULT NULL,
    "create_time" timestamp DEFAULT NULL,
    "update_by" bigint DEFAULT NULL,
    "update_time" timestamp DEFAULT NULL
);
-- ===== mcp_tool_info  -- MCP工具表 =====
CREATE TABLE IF NOT EXISTS legacy_mysql.mcp_tool_info (
    "id" bigint NOT NULL,
    "name" varchar(200) NOT NULL,
    "description" text,
    "type" varchar(20) DEFAULT 'LOCAL',
    "status" varchar(20) DEFAULT 'ENABLED',
    "config_json" text,
    "tenant_id" varchar(20) DEFAULT '000000',
    "create_dept" bigint DEFAULT NULL,
    "create_by" bigint DEFAULT NULL,
    "create_time" timestamp DEFAULT NULL,
    "update_by" bigint DEFAULT NULL,
    "update_time" timestamp DEFAULT NULL,
    "del_flag" char(1) DEFAULT '0'
);
-- ===== short_drama_audio  -- 短剧语音资产表 =====
CREATE TABLE IF NOT EXISTS legacy_mysql.short_drama_audio (
    "id" bigint NOT NULL,
    "project_id" bigint NOT NULL,
    "name" varchar(200) NOT NULL,
    "audio_type" varchar(32) NOT NULL DEFAULT 'narration',
    "text" text NOT NULL,
    "voice" varchar(100) DEFAULT NULL,
    "audio_oss_id" bigint DEFAULT NULL,
    "audio_url" text,
    "linked_storyboard_id" bigint DEFAULT NULL,
    "duration_seconds" integer DEFAULT NULL,
    "create_dept" bigint DEFAULT NULL,
    "create_by" bigint DEFAULT NULL,
    "create_time" timestamp DEFAULT CURRENT_TIMESTAMP,
    "update_by" bigint DEFAULT NULL,
    "update_time" timestamp DEFAULT CURRENT_TIMESTAMP,
    "tenant_id" bigint NOT NULL DEFAULT 0
);
-- ===== short_drama_character  -- 短剧角色表 =====
CREATE TABLE IF NOT EXISTS legacy_mysql.short_drama_character (
    "id" bigint NOT NULL,
    "project_id" bigint NOT NULL,
    "name" varchar(100) NOT NULL,
    "aliases" varchar(500) DEFAULT NULL,
    "introduction" text,
    "role_level" varchar(8) DEFAULT 'B',
    "gender" varchar(10) DEFAULT NULL,
    "age_range" varchar(50) DEFAULT NULL,
    "personality_tags" varchar(500) DEFAULT NULL,
    "costume_tier" integer DEFAULT 2,
    "visual_description" text,
    "reference_image_url" text,
    "create_dept" bigint DEFAULT NULL,
    "create_by" bigint DEFAULT NULL,
    "create_time" timestamp DEFAULT CURRENT_TIMESTAMP,
    "update_by" bigint DEFAULT NULL,
    "update_time" timestamp DEFAULT CURRENT_TIMESTAMP,
    "tenant_id" bigint NOT NULL DEFAULT 0
);
-- ===== short_drama_character_appearance  -- 短剧角色子形象表 =====
CREATE TABLE IF NOT EXISTS legacy_mysql.short_drama_character_appearance (
    "id" bigint NOT NULL,
    "character_id" bigint NOT NULL,
    "appearance_index" integer NOT NULL DEFAULT 0,
    "change_reason" varchar(200) DEFAULT '初始形象',
    "description" text,
    "reference_image_url" text,
    "create_dept" bigint DEFAULT NULL,
    "create_by" bigint DEFAULT NULL,
    "create_time" timestamp DEFAULT CURRENT_TIMESTAMP,
    "update_by" bigint DEFAULT NULL,
    "update_time" timestamp DEFAULT CURRENT_TIMESTAMP,
    "tenant_id" bigint NOT NULL DEFAULT 0,
    "image_urls" text,
    "image_descriptions" text,
    "selected_image_index" integer DEFAULT 0,
    "previous_image_urls" text,
    "previous_descriptions" text,
    "voice" varchar(100) DEFAULT NULL
);
-- ===== short_drama_location  -- 短剧场景表 =====
CREATE TABLE IF NOT EXISTS legacy_mysql.short_drama_location (
    "id" bigint NOT NULL,
    "project_id" bigint NOT NULL,
    "name" varchar(200) NOT NULL,
    "summary" varchar(500) DEFAULT NULL,
    "has_crowd" smallint DEFAULT 0,
    "crowd_description" varchar(500) DEFAULT NULL,
    "available_slots" text,
    "descriptions" text,
    "reference_image_url" text,
    "create_dept" bigint DEFAULT NULL,
    "create_by" bigint DEFAULT NULL,
    "create_time" timestamp DEFAULT CURRENT_TIMESTAMP,
    "update_by" bigint DEFAULT NULL,
    "update_time" timestamp DEFAULT CURRENT_TIMESTAMP,
    "tenant_id" bigint NOT NULL DEFAULT 0,
    "image_urls" text,
    "image_descriptions" text,
    "selected_image_index" integer DEFAULT 0,
    "previous_image_urls" text,
    "previous_descriptions" text
);
-- ===== short_drama_project  -- 短剧项目表 =====
CREATE TABLE IF NOT EXISTS legacy_mysql.short_drama_project (
    "id" bigint NOT NULL,
    "user_id" bigint NOT NULL,
    "project_name" varchar(200) NOT NULL,
    "description" text,
    "status" varchar(32) NOT NULL DEFAULT 'draft',
    "create_dept" bigint DEFAULT NULL,
    "create_by" bigint DEFAULT NULL,
    "create_time" timestamp DEFAULT CURRENT_TIMESTAMP,
    "update_by" bigint DEFAULT NULL,
    "update_time" timestamp DEFAULT CURRENT_TIMESTAMP,
    "tenant_id" bigint NOT NULL DEFAULT 0,
    "art_style" varchar(32) DEFAULT 'realistic',
    "composed_video_oss_id" bigint DEFAULT NULL,
    "compose_status" varchar(32) DEFAULT NULL,
    "compose_job_id" varchar(64) DEFAULT NULL,
    "compose_progress" integer NOT NULL DEFAULT 0,
    "compose_transition_type" varchar(32) NOT NULL DEFAULT 'dissolve',
    "compose_transition_duration_seconds" numeric NOT NULL DEFAULT 0.500,
    "compose_aspect_ratio" varchar(16) NOT NULL DEFAULT '9:16',
    "composed_video_duration_seconds" numeric DEFAULT NULL,
    "compose_error_message" varchar(1000) DEFAULT NULL,
    "composed_at" timestamp DEFAULT NULL
);
-- ===== short_drama_script  -- 短剧剧本表 =====
CREATE TABLE IF NOT EXISTS legacy_mysql.short_drama_script (
    "id" bigint NOT NULL,
    "project_id" bigint NOT NULL,
    "script_name" varchar(200) NOT NULL,
    "script_text" text,
    "outline_text" text,
    "tone" varchar(100) DEFAULT NULL,
    "source_type" varchar(32) NOT NULL DEFAULT 'manual',
    "create_dept" bigint DEFAULT NULL,
    "create_by" bigint DEFAULT NULL,
    "create_time" timestamp DEFAULT CURRENT_TIMESTAMP,
    "update_by" bigint DEFAULT NULL,
    "update_time" timestamp DEFAULT CURRENT_TIMESTAMP,
    "tenant_id" bigint NOT NULL DEFAULT 0
);
-- ===== short_drama_storyboard  -- 短剧分镜表 =====
CREATE TABLE IF NOT EXISTS legacy_mysql.short_drama_storyboard (
    "id" bigint NOT NULL,
    "project_id" bigint NOT NULL,
    "script_id" bigint NOT NULL,
    "scene_no" integer NOT NULL,
    "scene_title" varchar(200) DEFAULT NULL,
    "scene_text" text,
    "scene_type" varchar(32) DEFAULT 'daily',
    "shot_type" varchar(64) DEFAULT NULL,
    "camera_move" varchar(64) DEFAULT NULL,
    "characters_json" text,
    "location_name" varchar(200) DEFAULT NULL,
    "photography_rules" text,
    "acting_notes" text,
    "continuity_json" text,
    "source_text" text,
    "image_prompt" text,
    "duration_seconds" integer NOT NULL DEFAULT 15,
    "video_prompt" text,
    "video_url" text,
    "video_id" varchar(128) DEFAULT NULL,
    "video_status" varchar(32) NOT NULL DEFAULT 'pending',
    "last_frame_url" text,
    "create_dept" bigint DEFAULT NULL,
    "create_by" bigint DEFAULT NULL,
    "create_time" timestamp DEFAULT CURRENT_TIMESTAMP,
    "update_by" bigint DEFAULT NULL,
    "update_time" timestamp DEFAULT CURRENT_TIMESTAMP,
    "tenant_id" bigint NOT NULL DEFAULT 0
);
-- ===== t_workflow  -- 工作流定义（用户定义的工作流）| Workflow Definition =====
CREATE TABLE IF NOT EXISTS legacy_mysql.t_workflow (
    "id" bigint NOT NULL,
    "uuid" varchar(32) NOT NULL DEFAULT 'uuid',
    "title" varchar(100) NOT NULL DEFAULT '标题',
    "user_id" bigint NOT NULL DEFAULT 0,
    "is_public" smallint NOT NULL DEFAULT 0,
    "is_enable" smallint NOT NULL DEFAULT 1,
    "create_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "update_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "remark" text,
    "is_deleted" smallint NOT NULL DEFAULT 0,
    "tenant_id" varchar(20) DEFAULT '000000'
);
-- ===== t_workflow_component  -- 工作流组件库 | Workflow Component =====
CREATE TABLE IF NOT EXISTS legacy_mysql.t_workflow_component (
    "id" bigint NOT NULL,
    "uuid" varchar(32) NOT NULL DEFAULT '',
    "name" varchar(32) NOT NULL DEFAULT '',
    "title" varchar(100) NOT NULL DEFAULT '',
    "remark" text NOT NULL,
    "display_order" integer NOT NULL DEFAULT 0,
    "is_enable" smallint NOT NULL DEFAULT 0,
    "create_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "update_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "is_deleted" smallint NOT NULL DEFAULT 0,
    "tenant_id" varchar(20) DEFAULT '000000'
);
-- ===== t_workflow_edge  -- 工作流定义的边 | Edge of Workflow Definition =====
CREATE TABLE IF NOT EXISTS legacy_mysql.t_workflow_edge (
    "id" bigint NOT NULL,
    "uuid" varchar(32) NOT NULL DEFAULT '',
    "workflow_id" bigint NOT NULL DEFAULT 0,
    "source_node_uuid" varchar(32) NOT NULL DEFAULT '',
    "source_handle" varchar(32) NOT NULL DEFAULT '',
    "target_node_uuid" varchar(32) NOT NULL DEFAULT '',
    "create_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "update_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "is_deleted" smallint NOT NULL DEFAULT 0,
    "tenant_id" varchar(20) DEFAULT '000000'
);
-- ===== t_workflow_node  -- 工作流定义的节点 | Node of Workflow Definition =====
CREATE TABLE IF NOT EXISTS legacy_mysql.t_workflow_node (
    "id" bigint NOT NULL,
    "uuid" varchar(32) NOT NULL DEFAULT '',
    "workflow_id" bigint NOT NULL DEFAULT 0,
    "workflow_component_id" bigint NOT NULL DEFAULT 0,
    "user_id" bigint NOT NULL DEFAULT 0,
    "title" varchar(100) NOT NULL DEFAULT '',
    "remark" varchar(500) NOT NULL DEFAULT '',
    "input_config" jsonb NOT NULL,
    "node_config" jsonb,
    "position_x" double precision NOT NULL DEFAULT 0,
    "position_y" double precision NOT NULL DEFAULT 0,
    "create_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "update_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "is_deleted" smallint NOT NULL DEFAULT 0,
    "tenant_id" varchar(20) DEFAULT '000000'
);
-- ===== t_workflow_runtime  -- 工作流实例（运行时）| Workflow Runtime =====
CREATE TABLE IF NOT EXISTS legacy_mysql.t_workflow_runtime (
    "id" bigint NOT NULL,
    "uuid" varchar(32) NOT NULL DEFAULT '',
    "user_id" bigint NOT NULL DEFAULT 0,
    "workflow_id" bigint NOT NULL DEFAULT 0,
    "input" jsonb,
    "output" jsonb,
    "status" smallint NOT NULL DEFAULT 1,
    "status_remark" varchar(250) NOT NULL DEFAULT '',
    "create_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "update_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "is_deleted" smallint NOT NULL DEFAULT 0,
    "tenant_id" varchar(20) DEFAULT '000000'
);
-- ===== t_workflow_runtime_node  -- 工作流实例（运行时）- 节点 | Workflow Runtime Node =====
CREATE TABLE IF NOT EXISTS legacy_mysql.t_workflow_runtime_node (
    "id" bigint NOT NULL,
    "uuid" varchar(32) NOT NULL DEFAULT '',
    "user_id" bigint NOT NULL DEFAULT 0,
    "workflow_runtime_id" bigint NOT NULL DEFAULT 0,
    "node_id" bigint NOT NULL DEFAULT 0,
    "input" jsonb,
    "output" jsonb,
    "status" smallint NOT NULL DEFAULT 1,
    "status_remark" varchar(250) NOT NULL DEFAULT '',
    "create_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "update_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "is_deleted" smallint NOT NULL DEFAULT 0,
    "tenant_id" varchar(20) DEFAULT '000000'
);
-- ===== trace_node  -- 链路追踪节点记录表 =====
CREATE TABLE IF NOT EXISTS legacy_mysql.trace_node (
    "id" bigint NOT NULL,
    "trace_id" varchar(64) NOT NULL,
    "node_id" varchar(64) NOT NULL,
    "tenant_id" varchar(20) DEFAULT '000000',
    "parent_node_id" varchar(64) DEFAULT NULL,
    "node_name" varchar(128) NOT NULL,
    "node_type" varchar(64) NOT NULL,
    "depth" integer DEFAULT 0,
    "sort_order" integer DEFAULT 0,
    "class_name" varchar(255) DEFAULT NULL,
    "method_name" varchar(128) DEFAULT NULL,
    "status" varchar(32) NOT NULL,
    "start_time" timestamp NOT NULL,
    "end_time" timestamp DEFAULT NULL,
    "duration_ms" bigint DEFAULT NULL,
    "error_message" varchar(1000) DEFAULT NULL,
    "input_payload" text DEFAULT NULL,
    "output_payload" text DEFAULT NULL,
    "metadata" text DEFAULT NULL,
    "create_dept" bigint DEFAULT NULL,
    "create_by" bigint DEFAULT NULL,
    "create_time" timestamp DEFAULT NULL,
    "update_by" bigint DEFAULT NULL,
    "update_time" timestamp DEFAULT NULL,
    "del_flag" char(1) DEFAULT '0'
);
-- ===== trace_run  -- 链路追踪运行记录表 =====
CREATE TABLE IF NOT EXISTS legacy_mysql.trace_run (
    "id" bigint NOT NULL,
    "trace_id" varchar(64) NOT NULL,
    "trace_name" varchar(128) NOT NULL,
    "business_type" varchar(64) NOT NULL,
    "business_id" varchar(128) DEFAULT NULL,
    "user_id" bigint DEFAULT NULL,
    "tenant_id" varchar(20) DEFAULT '000000',
    "status" varchar(32) NOT NULL,
    "start_time" timestamp NOT NULL,
    "end_time" timestamp DEFAULT NULL,
    "duration_ms" bigint DEFAULT NULL,
    "error_message" varchar(1000) DEFAULT NULL,
    "metadata" text DEFAULT NULL,
    "create_dept" bigint DEFAULT NULL,
    "create_by" bigint DEFAULT NULL,
    "create_time" timestamp DEFAULT NULL,
    "update_by" bigint DEFAULT NULL,
    "update_time" timestamp DEFAULT NULL,
    "del_flag" char(1) DEFAULT '0'
);
