-- ---------------------------------------------------------------------------
-- E2 legacy MySQL AI domain: landing-zone adaptation and validation (E5).
--
-- Generated by scripts/db/generate-legacy-ai-copy.py. This file is NOT a Flyway migration:
-- the landing-zone owner (DBA) runs it once, after the MySQL rows are loaded and *before*
-- the platform migration chain reaches V11. It materialises the derived columns the merged
-- tables need -- the values no legacy column carries -- and refuses to hand V11 incomplete
-- data.
--
-- Why here and not inside V11: the V11 driver stays table-agnostic (every table-specific
-- fact lives in its registry) and the migration identity only holds USAGE+SELECT on the
-- landing zone. The derivation is therefore computed by the landing-zone owner from the
-- sources named below, and V11 then copies the column like any other one -- including the
-- source-width pre-check when the derived value is wider than the unified column.
--
-- Contract:
--   * every derived value names its sources and its rule; nothing is invented and no default
--     is substituted for a missing source. Missing identity, broken / ambiguous /
--     cross-tenant association and blank required values abort with the row count and
--     samples instead of copying a repaired-looking row;
--   * load order: the parent rows (chat_session) are loaded before this file runs, because a
--     message's public conversation id is resolved from them;
--   * the whole file runs in one transaction: a refusal leaves the landing zone untouched;
--   * it is re-runnable: derived columns are recomputed and re-tightened.
-- ---------------------------------------------------------------------------

BEGIN;

-- =======================================================================
-- chat_message -> platform.ai_message
-- =======================================================================
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.tables t
                    WHERE t.table_schema = 'legacy_mysql' AND t.table_name = 'chat_message') THEN
        RAISE EXCEPTION '落地区表 legacy_mysql.chat_message 不存在：请先执行 '
            'legacy_mysql/10-legacy-ai-domain-staging.sql 并装载 MySQL 行数据';
    END IF;
END $$;
ALTER TABLE legacy_mysql.chat_message ADD COLUMN IF NOT EXISTS "member_id" varchar(160);
-- 派生 member_id：成员身份：canonical platform:<tenantId>:<userId>，与所属会话的 member_id 必须一致（V7 的 fk_message_conversation 按 tenant_id+conversation_id+member_id 引用 ai_conversation）；tenant_id/user_id 任一缺失即拒绝
DO $$
DECLARE
    v_bad     bigint;
    v_samples text;
BEGIN
    SELECT count(*) INTO v_bad FROM legacy_mysql.chat_message q WHERE q.tenant_id IS NULL OR q.user_id IS NULL;
    IF v_bad > 0 THEN
        SELECT string_agg(format('id=%s tenant_id=%s user_id=%s', s.id, s.tenant_id, s.user_id), ' | ') INTO v_samples
          FROM (SELECT * FROM legacy_mysql.chat_message q WHERE q.tenant_id IS NULL OR q.user_id IS NULL ORDER BY q.id LIMIT 5) s;
        RAISE EXCEPTION 'chat_message：缺少成员身份来源（tenant_id/user_id），拒绝派生 member_id，不造默认值（% 行）；样本：%', v_bad, v_samples;
    END IF;
END $$;
UPDATE legacy_mysql.chat_message q SET "member_id" = 'platform:' || q.tenant_id::text || ':' || q.user_id::text;
ALTER TABLE legacy_mysql.chat_message ADD COLUMN IF NOT EXISTS "conversation_id" varchar(32);
-- 派生 conversation_id：公开会话标识：按同租户、同成员的 legacy chat_session 行（session_id → id）取 conversation_id；不假设 session_id 与会话主键或 conversation_id 相等。断关联/跨租户/成员不一致/父值缺失/父键歧义均拒绝，不造默认值
DO $$
DECLARE
    v_bad     bigint;
    v_samples text;
BEGIN
    SELECT count(*) INTO v_bad FROM legacy_mysql.chat_message q WHERE q.session_id IS NULL;
    IF v_bad > 0 THEN
        SELECT string_agg(format('id=%s session_id=%s', s.id, s.session_id), ' | ') INTO v_samples
          FROM (SELECT * FROM legacy_mysql.chat_message q WHERE q.session_id IS NULL ORDER BY q.id LIMIT 5) s;
        RAISE EXCEPTION 'chat_message：消息缺少会话关联键（session_id），拒绝派生 conversation_id（% 行）；样本：%', v_bad, v_samples;
    END IF;
END $$;
DO $$
DECLARE
    v_bad     bigint;
    v_samples text;
BEGIN
    SELECT count(*) INTO v_bad FROM legacy_mysql.chat_message q WHERE q.session_id IN (SELECT p.id FROM legacy_mysql.chat_session p GROUP BY p.id HAVING count(*) > 1);
    IF v_bad > 0 THEN
        SELECT string_agg(format('id=%s session_id=%s', s.id, s.session_id), ' | ') INTO v_samples
          FROM (SELECT * FROM legacy_mysql.chat_message q WHERE q.session_id IN (SELECT p.id FROM legacy_mysql.chat_session p GROUP BY p.id HAVING count(*) > 1) ORDER BY q.id LIMIT 5) s;
        RAISE EXCEPTION 'chat_message：落地区 chat_session 中同一 id 有多行，会话关联歧义，拒绝派生 conversation_id（% 行）；样本：%', v_bad, v_samples;
    END IF;
END $$;
DO $$
DECLARE
    v_bad     bigint;
    v_samples text;
BEGIN
    SELECT count(*) INTO v_bad FROM legacy_mysql.chat_message q WHERE NOT EXISTS (SELECT 1 FROM legacy_mysql.chat_session p WHERE p.id = q.session_id);
    IF v_bad > 0 THEN
        SELECT string_agg(format('id=%s session_id=%s', s.id, s.session_id), ' | ') INTO v_samples
          FROM (SELECT * FROM legacy_mysql.chat_message q WHERE NOT EXISTS (SELECT 1 FROM legacy_mysql.chat_session p WHERE p.id = q.session_id) ORDER BY q.id LIMIT 5) s;
        RAISE EXCEPTION 'chat_message：消息引用的会话在落地区 chat_session 中不存在（断关联），拒绝派生 conversation_id（% 行）；样本：%', v_bad, v_samples;
    END IF;
END $$;
DO $$
DECLARE
    v_bad     bigint;
    v_samples text;
BEGIN
    SELECT count(*) INTO v_bad FROM legacy_mysql.chat_message q WHERE EXISTS (SELECT 1 FROM legacy_mysql.chat_session p WHERE p.id = q.session_id AND p.tenant_id::text IS DISTINCT FROM q.tenant_id::text);
    IF v_bad > 0 THEN
        SELECT string_agg(format('id=%s session_id=%s tenant_id=%s', s.id, s.session_id, s.tenant_id), ' | ') INTO v_samples
          FROM (SELECT * FROM legacy_mysql.chat_message q WHERE EXISTS (SELECT 1 FROM legacy_mysql.chat_session p WHERE p.id = q.session_id AND p.tenant_id::text IS DISTINCT FROM q.tenant_id::text) ORDER BY q.id LIMIT 5) s;
        RAISE EXCEPTION 'chat_message：消息与其会话的 tenant_id 不一致（跨租户/跨成员关联），拒绝派生 conversation_id（% 行）；样本：%', v_bad, v_samples;
    END IF;
END $$;
DO $$
DECLARE
    v_bad     bigint;
    v_samples text;
BEGIN
    SELECT count(*) INTO v_bad FROM legacy_mysql.chat_message q WHERE EXISTS (SELECT 1 FROM legacy_mysql.chat_session p WHERE p.id = q.session_id AND p.user_id::text IS DISTINCT FROM q.user_id::text);
    IF v_bad > 0 THEN
        SELECT string_agg(format('id=%s session_id=%s user_id=%s', s.id, s.session_id, s.user_id), ' | ') INTO v_samples
          FROM (SELECT * FROM legacy_mysql.chat_message q WHERE EXISTS (SELECT 1 FROM legacy_mysql.chat_session p WHERE p.id = q.session_id AND p.user_id::text IS DISTINCT FROM q.user_id::text) ORDER BY q.id LIMIT 5) s;
        RAISE EXCEPTION 'chat_message：消息与其会话的 user_id 不一致（跨租户/跨成员关联），拒绝派生 conversation_id（% 行）；样本：%', v_bad, v_samples;
    END IF;
END $$;
DO $$
DECLARE
    v_bad     bigint;
    v_samples text;
BEGIN
    SELECT count(*) INTO v_bad FROM legacy_mysql.chat_message q WHERE EXISTS (SELECT 1 FROM legacy_mysql.chat_session p WHERE p.id = q.session_id AND (p.conversation_id IS NULL OR btrim(p.conversation_id) = ''));
    IF v_bad > 0 THEN
        SELECT string_agg(format('id=%s session_id=%s', s.id, s.session_id), ' | ') INTO v_samples
          FROM (SELECT * FROM legacy_mysql.chat_message q WHERE EXISTS (SELECT 1 FROM legacy_mysql.chat_session p WHERE p.id = q.session_id AND (p.conversation_id IS NULL OR btrim(p.conversation_id) = '')) ORDER BY q.id LIMIT 5) s;
        RAISE EXCEPTION 'chat_message：会话的 conversation_id 缺失或为空，无法作为消息的公开会话标识（% 行）；样本：%', v_bad, v_samples;
    END IF;
END $$;
UPDATE legacy_mysql.chat_message q SET "conversation_id" = p.conversation_id
  FROM legacy_mysql.chat_session p
 WHERE p.id = q.session_id AND p.tenant_id::text = q.tenant_id::text AND p.user_id::text = q.user_id::text;
DO $$
DECLARE
    v_bad     bigint;
    v_samples text;
BEGIN
    SELECT count(*) INTO v_bad FROM legacy_mysql.chat_message q WHERE q.content IS NULL;
    IF v_bad > 0 THEN
        SELECT string_agg(format('id=%s content=%s', s.id, s.content), ' | ') INTO v_samples
          FROM (SELECT * FROM legacy_mysql.chat_message q WHERE q.content IS NULL ORDER BY q.id LIMIT 5) s;
        RAISE EXCEPTION 'chat_message：统一列 content 的必填来源 content 缺失（NULL），拒绝复制，不造默认值（% 行）；样本：%', v_bad, v_samples;
    END IF;
END $$;
DO $$
DECLARE
    v_bad     bigint;
    v_samples text;
BEGIN
    SELECT count(*) INTO v_bad FROM legacy_mysql.chat_message q WHERE q.id IS NULL;
    IF v_bad > 0 THEN
        SELECT string_agg(format('id=%s', s.id), ' | ') INTO v_samples
          FROM (SELECT * FROM legacy_mysql.chat_message q WHERE q.id IS NULL ORDER BY q.id LIMIT 5) s;
        RAISE EXCEPTION 'chat_message：统一列 id 的必填来源 id 缺失（NULL），拒绝复制，不造默认值（% 行）；样本：%', v_bad, v_samples;
    END IF;
END $$;
DO $$
DECLARE
    v_bad     bigint;
    v_samples text;
BEGIN
    SELECT count(*) INTO v_bad FROM legacy_mysql.chat_message q WHERE q.role IS NULL OR btrim(q.role::text) = '';
    IF v_bad > 0 THEN
        SELECT string_agg(format('id=%s role=%s', s.id, s.role), ' | ') INTO v_samples
          FROM (SELECT * FROM legacy_mysql.chat_message q WHERE q.role IS NULL OR btrim(q.role::text) = '' ORDER BY q.id LIMIT 5) s;
        RAISE EXCEPTION 'chat_message：统一列 role 的必填来源 role 缺失（NULL 或空串），拒绝复制，不造默认值（% 行）；样本：%', v_bad, v_samples;
    END IF;
END $$;
DO $$
DECLARE
    v_bad     bigint;
    v_samples text;
BEGIN
    SELECT count(*) INTO v_bad FROM legacy_mysql.chat_message q WHERE q.user_id IS NULL;
    IF v_bad > 0 THEN
        SELECT string_agg(format('id=%s user_id=%s', s.id, s.user_id), ' | ') INTO v_samples
          FROM (SELECT * FROM legacy_mysql.chat_message q WHERE q.user_id IS NULL ORDER BY q.id LIMIT 5) s;
        RAISE EXCEPTION 'chat_message：统一列 user_id 的必填来源 user_id 缺失（NULL），拒绝复制，不造默认值（% 行）；样本：%', v_bad, v_samples;
    END IF;
END $$;
ALTER TABLE legacy_mysql.chat_message ALTER COLUMN "member_id" SET NOT NULL;
ALTER TABLE legacy_mysql.chat_message ALTER COLUMN "conversation_id" SET NOT NULL;

-- =======================================================================
-- chat_session -> platform.ai_conversation
-- =======================================================================
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.tables t
                    WHERE t.table_schema = 'legacy_mysql' AND t.table_name = 'chat_session') THEN
        RAISE EXCEPTION '落地区表 legacy_mysql.chat_session 不存在：请先执行 '
            'legacy_mysql/10-legacy-ai-domain-staging.sql 并装载 MySQL 行数据';
    END IF;
END $$;
ALTER TABLE legacy_mysql.chat_session ADD COLUMN IF NOT EXISTS "member_id" varchar(160);
-- 派生 member_id：成员身份：canonical platform:<tenantId>:<userId>（framework ExecutionPrincipal.membershipId / AiResourceWriteService 的 "platform:" + tenantId + ":" 前缀校验）；tenant_id/user_id 任一缺失即拒绝，不造默认值；数值租户按文本参与，0 → 'platform:0:<userId>'，不并入 '000000'
DO $$
DECLARE
    v_bad     bigint;
    v_samples text;
BEGIN
    SELECT count(*) INTO v_bad FROM legacy_mysql.chat_session q WHERE q.tenant_id IS NULL OR q.user_id IS NULL;
    IF v_bad > 0 THEN
        SELECT string_agg(format('id=%s tenant_id=%s user_id=%s', s.id, s.tenant_id, s.user_id), ' | ') INTO v_samples
          FROM (SELECT * FROM legacy_mysql.chat_session q WHERE q.tenant_id IS NULL OR q.user_id IS NULL ORDER BY q.id LIMIT 5) s;
        RAISE EXCEPTION 'chat_session：缺少成员身份来源（tenant_id/user_id），拒绝派生 member_id，不造默认值（% 行）；样本：%', v_bad, v_samples;
    END IF;
END $$;
UPDATE legacy_mysql.chat_session q SET "member_id" = 'platform:' || q.tenant_id::text || ':' || q.user_id::text;
DO $$
DECLARE
    v_bad     bigint;
    v_samples text;
BEGIN
    SELECT count(*) INTO v_bad FROM legacy_mysql.chat_session q WHERE q.conversation_id IS NULL OR btrim(q.conversation_id::text) = '';
    IF v_bad > 0 THEN
        SELECT string_agg(format('id=%s conversation_id=%s', s.id, s.conversation_id), ' | ') INTO v_samples
          FROM (SELECT * FROM legacy_mysql.chat_session q WHERE q.conversation_id IS NULL OR btrim(q.conversation_id::text) = '' ORDER BY q.id LIMIT 5) s;
        RAISE EXCEPTION 'chat_session：统一列 conversation_id 的必填来源 conversation_id 缺失（NULL 或空串），拒绝复制，不造默认值（% 行）；样本：%', v_bad, v_samples;
    END IF;
END $$;
DO $$
DECLARE
    v_bad     bigint;
    v_samples text;
BEGIN
    SELECT count(*) INTO v_bad FROM legacy_mysql.chat_session q WHERE q.id IS NULL;
    IF v_bad > 0 THEN
        SELECT string_agg(format('id=%s', s.id), ' | ') INTO v_samples
          FROM (SELECT * FROM legacy_mysql.chat_session q WHERE q.id IS NULL ORDER BY q.id LIMIT 5) s;
        RAISE EXCEPTION 'chat_session：统一列 id 的必填来源 id 缺失（NULL），拒绝复制，不造默认值（% 行）；样本：%', v_bad, v_samples;
    END IF;
END $$;
DO $$
DECLARE
    v_bad     bigint;
    v_samples text;
BEGIN
    SELECT count(*) INTO v_bad FROM legacy_mysql.chat_session q WHERE q.session_title IS NULL OR btrim(q.session_title::text) = '';
    IF v_bad > 0 THEN
        SELECT string_agg(format('id=%s session_title=%s', s.id, s.session_title), ' | ') INTO v_samples
          FROM (SELECT * FROM legacy_mysql.chat_session q WHERE q.session_title IS NULL OR btrim(q.session_title::text) = '' ORDER BY q.id LIMIT 5) s;
        RAISE EXCEPTION 'chat_session：统一列 title 的必填来源 session_title 缺失（NULL 或空串），拒绝复制，不造默认值（% 行）；样本：%', v_bad, v_samples;
    END IF;
END $$;
DO $$
DECLARE
    v_bad     bigint;
    v_samples text;
BEGIN
    SELECT count(*) INTO v_bad FROM legacy_mysql.chat_session q WHERE q.user_id IS NULL;
    IF v_bad > 0 THEN
        SELECT string_agg(format('id=%s user_id=%s', s.id, s.user_id), ' | ') INTO v_samples
          FROM (SELECT * FROM legacy_mysql.chat_session q WHERE q.user_id IS NULL ORDER BY q.id LIMIT 5) s;
        RAISE EXCEPTION 'chat_session：统一列 user_id 的必填来源 user_id 缺失（NULL），拒绝复制，不造默认值（% 行）；样本：%', v_bad, v_samples;
    END IF;
END $$;
ALTER TABLE legacy_mysql.chat_session ALTER COLUMN "member_id" SET NOT NULL;
COMMIT;
