/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.nageoffer.ai.ragent.flow.dao.entity;

import com.baomidou.mybatisplus.annotation.FieldFill;
import com.baomidou.mybatisplus.annotation.IdType;
import com.baomidou.mybatisplus.annotation.TableField;
import com.baomidou.mybatisplus.annotation.TableId;
import com.baomidou.mybatisplus.annotation.TableName;
import lombok.Data;

import java.util.Date;

/**
 * 可视化工作流定义（AIFlow）。
 *
 * <p>表 {@code platform.ai_flow_workflow} 由<b>冻结迁移 V9</b> 建立
 * （{@code V9__legacy_ai_domain_ddl.sql:418}），本卡<b>不新增迁移、不改冻结 DDL</b>。
 * 列类型逐列取自该 DDL：{@code id bigint identity} / {@code uuid varchar(32)} /
 * {@code title varchar(100)} / {@code user_id bigint} / {@code is_public smallint} /
 * {@code is_enable smallint} / {@code remark text} / {@code is_deleted smallint} /
 * {@code tenant_id varchar(64)}。
 *
 * <p>{@code tenant_id} 与 {@code user_id} 是资源边界的<b>两个独立维度</b>：
 * 前者由主体 tenant 决定（跨租户不可见），后者用于「我的工作流」限定。
 * 二者都必须在 SQL 谓词里显式出现，不得只靠其一。
 */
@Data
@TableName("ai_flow_workflow")
public class AiFlowWorkflowDO {

    /** 主键；DDL 为 bigint GENERATED BY DEFAULT AS IDENTITY。 */
    @TableId(type = IdType.ASSIGN_ID)
    private Long id;

    /** 对外标识（32 位）；公开面以此为路径变量。 */
    private String uuid;

    /** 标题。 */
    private String title;

    /** 属主用户 id（bigint）。 */
    private Long userId;

    /** 是否公开：0 否 1 是。 */
    private Integer isPublic;

    /** 是否启用：0 停放 1 启用。 */
    private Integer isEnable;

    /** 备注 / 基础信息。 */
    private String remark;

    /** 逻辑删除：0 未删 1 已删。 */
    private Integer isDeleted;

    /** 租户编号。 */
    private String tenantId;

    /**
     * 创建时间。
     *
     * <p>必须是 {@link Date} 且带 {@code FieldFill.INSERT}：{@code InjectionMetaObjectHandler}
     * 用的是 {@code strictInsertFill(metaObject, "createTime", Date.class, …)}，而 MyBatis-Plus 的
     * strict 填充按<b>字段类型逐字匹配</b>（{@code fieldType.equals(propertyType)}）。
     * 用 {@code LocalDateTime} 不会报错，只会<b>静默不填充</b>。仓内 25 个同类实体全部是
     * {@code Date}（如 {@code KnowledgeChunkDO.java:110-111}），本类跟随该约定。
     */
    @TableField(fill = FieldFill.INSERT)
    private Date createTime;

    /**
     * 更新时间；由 UPDATE 填充。
     *
     * <p>「我的工作流搜索」按 {@code updateTime} 倒序（{@code FlowWorkflowServiceImpl} 的
     * {@code orderByDesc(updateTime)}），没有这个填充则更新后排序不反映最近编辑。
     */
    @TableField(fill = FieldFill.INSERT_UPDATE)
    private Date updateTime;
}
